// Auto-generated tests for account_reports
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const test = require("node:test");
const assert = require("node:assert");
const account_reportsModule = require("../tools/account_reports");

test("get_accounts_account_id_reports calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = account_reportsModule.handlers.get_accounts_account_id_reports;
  assert.ok(handler, "Handler get_accounts_account_id_reports should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "include[]": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/reports");
  assert.deepStrictEqual(calledConfig.params, {"include[]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("post_accounts_account_id_reports_report calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = account_reportsModule.handlers.post_accounts_account_id_reports_report;
  assert.ok(handler, "Handler post_accounts_account_id_reports_report should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "report": "test_report", "parameters[]": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/reports/test_report");
  assert.deepStrictEqual(calledConfig.data, {"parameters[]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_accounts_account_id_reports_report calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = account_reportsModule.handlers.get_accounts_account_id_reports_report;
  assert.ok(handler, "Handler get_accounts_account_id_reports_report should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "report": "test_report"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/reports/test_report");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_accounts_account_id_reports_report_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = account_reportsModule.handlers.get_accounts_account_id_reports_report_id;
  assert.ok(handler, "Handler get_accounts_account_id_reports_report_id should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "report": "test_report", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/reports/test_report/test_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_accounts_account_id_reports_report_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = account_reportsModule.handlers.delete_accounts_account_id_reports_report_id;
  assert.ok(handler, "Handler delete_accounts_account_id_reports_report_id should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "report": "test_report", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/reports/test_report/test_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_accounts_account_id_reports_report_id_abort calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = account_reportsModule.handlers.put_accounts_account_id_reports_report_id_abort;
  assert.ok(handler, "Handler put_accounts_account_id_reports_report_id_abort should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "report": "test_report", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/reports/test_report/test_id/abort");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});
