// Auto-generated tests for announcement_external_feeds
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const test = require("node:test");
const assert = require("node:assert");
const announcement_external_feedsModule = require("../tools/announcement_external_feeds");

test("get_courses_course_id_external_feeds calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = announcement_external_feedsModule.handlers.get_courses_course_id_external_feeds;
  assert.ok(handler, "Handler get_courses_course_id_external_feeds should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/external_feeds");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_groups_group_id_external_feeds calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = announcement_external_feedsModule.handlers.get_groups_group_id_external_feeds;
  assert.ok(handler, "Handler get_groups_group_id_external_feeds should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/external_feeds");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_courses_course_id_external_feeds calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = announcement_external_feedsModule.handlers.post_courses_course_id_external_feeds;
  assert.ok(handler, "Handler post_courses_course_id_external_feeds should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/external_feeds");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_groups_group_id_external_feeds calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = announcement_external_feedsModule.handlers.post_groups_group_id_external_feeds;
  assert.ok(handler, "Handler post_groups_group_id_external_feeds should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "url": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/external_feeds");
  assert.deepStrictEqual(calledConfig.data, {"url": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_courses_course_id_external_feeds_external_feed_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = announcement_external_feedsModule.handlers.delete_courses_course_id_external_feeds_external_feed_id;
  assert.ok(handler, "Handler delete_courses_course_id_external_feeds_external_feed_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "external_feed_id": "test_external_feed_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/external_feeds/test_external_feed_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_groups_group_id_external_feeds_external_feed_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = announcement_external_feedsModule.handlers.delete_groups_group_id_external_feeds_external_feed_id;
  assert.ok(handler, "Handler delete_groups_group_id_external_feeds_external_feed_id should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "external_feed_id": "test_external_feed_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/external_feeds/test_external_feed_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});
