// Auto-generated tests for api_token_scopes
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const test = require("node:test");
const assert = require("node:assert");
const api_token_scopesModule = require("../tools/api_token_scopes");

test("get_accounts_account_id_scopes calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = api_token_scopesModule.handlers.get_accounts_account_id_scopes;
  assert.ok(handler, "Handler get_accounts_account_id_scopes should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "group_by": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/scopes");
  assert.deepStrictEqual(calledConfig.params, {"group_by": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});
