// Auto-generated tests for bookmarks
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const test = require("node:test");
const assert = require("node:assert");
const bookmarksModule = require("../tools/bookmarks");

test("get_users_self_bookmarks calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = bookmarksModule.handlers.get_users_self_bookmarks;
  assert.ok(handler, "Handler get_users_self_bookmarks should be defined");

  const result = await handler(mockClient, {});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/users/self/bookmarks");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_users_self_bookmarks calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = bookmarksModule.handlers.post_users_self_bookmarks;
  assert.ok(handler, "Handler post_users_self_bookmarks should be defined");

  const result = await handler(mockClient, {"name": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/users/self/bookmarks");
  assert.deepStrictEqual(calledConfig.data, {"name": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_users_self_bookmarks_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = bookmarksModule.handlers.get_users_self_bookmarks_id;
  assert.ok(handler, "Handler get_users_self_bookmarks_id should be defined");

  const result = await handler(mockClient, {"id": "test_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/users/self/bookmarks/test_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_users_self_bookmarks_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = bookmarksModule.handlers.put_users_self_bookmarks_id;
  assert.ok(handler, "Handler put_users_self_bookmarks_id should be defined");

  const result = await handler(mockClient, {"id": "test_id", "name": "test_val"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/users/self/bookmarks/test_id");
  assert.deepStrictEqual(calledConfig.data, {"name": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_users_self_bookmarks_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = bookmarksModule.handlers.delete_users_self_bookmarks_id;
  assert.ok(handler, "Handler delete_users_self_bookmarks_id should be defined");

  const result = await handler(mockClient, {"id": "test_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/users/self/bookmarks/test_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});
