// Auto-generated tests for conferences
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const test = require("node:test");
const assert = require("node:assert");
const conferencesModule = require("../tools/conferences");

test("get_courses_course_id_conferences calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = conferencesModule.handlers.get_courses_course_id_conferences;
  assert.ok(handler, "Handler get_courses_course_id_conferences should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/conferences");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_groups_group_id_conferences calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = conferencesModule.handlers.get_groups_group_id_conferences;
  assert.ok(handler, "Handler get_groups_group_id_conferences should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/conferences");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_conferences calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = conferencesModule.handlers.get_conferences;
  assert.ok(handler, "Handler get_conferences should be defined");

  const result = await handler(mockClient, {"state": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/conferences");
  assert.deepStrictEqual(calledConfig.params, {"state": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});
