// Auto-generated tests for feature_flags
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const test = require("node:test");
const assert = require("node:assert");
const feature_flagsModule = require("../tools/feature_flags");

test("get_courses_course_id_features calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = feature_flagsModule.handlers.get_courses_course_id_features;
  assert.ok(handler, "Handler get_courses_course_id_features should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/features");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_accounts_account_id_features calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = feature_flagsModule.handlers.get_accounts_account_id_features;
  assert.ok(handler, "Handler get_accounts_account_id_features should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/features");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_users_user_id_features calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = feature_flagsModule.handlers.get_users_user_id_features;
  assert.ok(handler, "Handler get_users_user_id_features should be defined");

  const result = await handler(mockClient, {"user_id": "test_user_id", "hide_inherited_enabled": true});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_user_id/features");
  assert.deepStrictEqual(calledConfig.params, {"hide_inherited_enabled": true});
  assert.deepStrictEqual(result, { success: true });
});

test("get_courses_course_id_features_enabled calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = feature_flagsModule.handlers.get_courses_course_id_features_enabled;
  assert.ok(handler, "Handler get_courses_course_id_features_enabled should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/features/enabled");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_accounts_account_id_features_enabled calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = feature_flagsModule.handlers.get_accounts_account_id_features_enabled;
  assert.ok(handler, "Handler get_accounts_account_id_features_enabled should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/features/enabled");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_users_user_id_features_enabled calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = feature_flagsModule.handlers.get_users_user_id_features_enabled;
  assert.ok(handler, "Handler get_users_user_id_features_enabled should be defined");

  const result = await handler(mockClient, {"user_id": "test_user_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_user_id/features/enabled");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_features_environment calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = feature_flagsModule.handlers.get_features_environment;
  assert.ok(handler, "Handler get_features_environment should be defined");

  const result = await handler(mockClient, {});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/features/environment");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_courses_course_id_features_flags_feature calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = feature_flagsModule.handlers.get_courses_course_id_features_flags_feature;
  assert.ok(handler, "Handler get_courses_course_id_features_flags_feature should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "feature": "test_feature"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/features/flags/test_feature");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_accounts_account_id_features_flags_feature calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = feature_flagsModule.handlers.get_accounts_account_id_features_flags_feature;
  assert.ok(handler, "Handler get_accounts_account_id_features_flags_feature should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "feature": "test_feature"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/features/flags/test_feature");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_users_user_id_features_flags_feature calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = feature_flagsModule.handlers.get_users_user_id_features_flags_feature;
  assert.ok(handler, "Handler get_users_user_id_features_flags_feature should be defined");

  const result = await handler(mockClient, {"user_id": "test_user_id", "feature": "test_feature"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_user_id/features/flags/test_feature");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_courses_course_id_features_flags_feature calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = feature_flagsModule.handlers.put_courses_course_id_features_flags_feature;
  assert.ok(handler, "Handler put_courses_course_id_features_flags_feature should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "feature": "test_feature"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/features/flags/test_feature");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_accounts_account_id_features_flags_feature calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = feature_flagsModule.handlers.put_accounts_account_id_features_flags_feature;
  assert.ok(handler, "Handler put_accounts_account_id_features_flags_feature should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "feature": "test_feature"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/features/flags/test_feature");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_users_user_id_features_flags_feature calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = feature_flagsModule.handlers.put_users_user_id_features_flags_feature;
  assert.ok(handler, "Handler put_users_user_id_features_flags_feature should be defined");

  const result = await handler(mockClient, {"user_id": "test_user_id", "feature": "test_feature", "state": "test_val"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_user_id/features/flags/test_feature");
  assert.deepStrictEqual(calledConfig.data, {"state": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_courses_course_id_features_flags_feature calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = feature_flagsModule.handlers.delete_courses_course_id_features_flags_feature;
  assert.ok(handler, "Handler delete_courses_course_id_features_flags_feature should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "feature": "test_feature"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/features/flags/test_feature");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_accounts_account_id_features_flags_feature calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = feature_flagsModule.handlers.delete_accounts_account_id_features_flags_feature;
  assert.ok(handler, "Handler delete_accounts_account_id_features_flags_feature should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "feature": "test_feature"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/features/flags/test_feature");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_users_user_id_features_flags_feature calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = feature_flagsModule.handlers.delete_users_user_id_features_flags_feature;
  assert.ok(handler, "Handler delete_users_user_id_features_flags_feature should be defined");

  const result = await handler(mockClient, {"user_id": "test_user_id", "feature": "test_feature"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_user_id/features/flags/test_feature");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});
