// Auto-generated tests for modules
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const test = require("node:test");
const assert = require("node:assert");
const modulesModule = require("../tools/modules");

test("get_courses_course_id_modules calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = modulesModule.handlers.get_courses_course_id_modules;
  assert.ok(handler, "Handler get_courses_course_id_modules should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "include[]": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/modules");
  assert.deepStrictEqual(calledConfig.params, {"include[]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_courses_course_id_modules_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = modulesModule.handlers.get_courses_course_id_modules_id;
  assert.ok(handler, "Handler get_courses_course_id_modules_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "id": "test_id", "include[]": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/modules/test_id");
  assert.deepStrictEqual(calledConfig.params, {"include[]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("post_courses_course_id_modules calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = modulesModule.handlers.post_courses_course_id_modules;
  assert.ok(handler, "Handler post_courses_course_id_modules should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "module[name]": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/modules");
  assert.deepStrictEqual(calledConfig.data, {"module[name]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("put_courses_course_id_modules_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = modulesModule.handlers.put_courses_course_id_modules_id;
  assert.ok(handler, "Handler put_courses_course_id_modules_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "id": "test_id", "module[name]": "test_val"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/modules/test_id");
  assert.deepStrictEqual(calledConfig.data, {"module[name]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_courses_course_id_modules_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = modulesModule.handlers.delete_courses_course_id_modules_id;
  assert.ok(handler, "Handler delete_courses_course_id_modules_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/modules/test_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_courses_course_id_modules_id_relock calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = modulesModule.handlers.put_courses_course_id_modules_id_relock;
  assert.ok(handler, "Handler put_courses_course_id_modules_id_relock should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/modules/test_id/relock");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_courses_course_id_modules_module_id_items calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = modulesModule.handlers.get_courses_course_id_modules_module_id_items;
  assert.ok(handler, "Handler get_courses_course_id_modules_module_id_items should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "module_id": "test_module_id", "include[]": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/modules/test_module_id/items");
  assert.deepStrictEqual(calledConfig.params, {"include[]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_courses_course_id_modules_module_id_items_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = modulesModule.handlers.get_courses_course_id_modules_module_id_items_id;
  assert.ok(handler, "Handler get_courses_course_id_modules_module_id_items_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "module_id": "test_module_id", "id": "test_id", "include[]": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/modules/test_module_id/items/test_id");
  assert.deepStrictEqual(calledConfig.params, {"include[]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("post_courses_course_id_modules_module_id_items calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = modulesModule.handlers.post_courses_course_id_modules_module_id_items;
  assert.ok(handler, "Handler post_courses_course_id_modules_module_id_items should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "module_id": "test_module_id", "module_item[title]": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/modules/test_module_id/items");
  assert.deepStrictEqual(calledConfig.data, {"module_item[title]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("put_courses_course_id_modules_module_id_items_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = modulesModule.handlers.put_courses_course_id_modules_module_id_items_id;
  assert.ok(handler, "Handler put_courses_course_id_modules_module_id_items_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "module_id": "test_module_id", "id": "test_id", "module_item[title]": "test_val"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/modules/test_module_id/items/test_id");
  assert.deepStrictEqual(calledConfig.data, {"module_item[title]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("post_courses_course_id_modules_module_id_items_id_select_mastery_path calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = modulesModule.handlers.post_courses_course_id_modules_module_id_items_id_select_mastery_path;
  assert.ok(handler, "Handler post_courses_course_id_modules_module_id_items_id_select_mastery_path should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "module_id": "test_module_id", "id": "test_id", "assignment_set_id": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/modules/test_module_id/items/test_id/select_mastery_path");
  assert.deepStrictEqual(calledConfig.data, {"assignment_set_id": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_courses_course_id_modules_module_id_items_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = modulesModule.handlers.delete_courses_course_id_modules_module_id_items_id;
  assert.ok(handler, "Handler delete_courses_course_id_modules_module_id_items_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "module_id": "test_module_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/modules/test_module_id/items/test_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_courses_course_id_modules_module_id_items_id_done calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = modulesModule.handlers.put_courses_course_id_modules_module_id_items_id_done;
  assert.ok(handler, "Handler put_courses_course_id_modules_module_id_items_id_done should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "module_id": "test_module_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/modules/test_module_id/items/test_id/done");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_courses_course_id_module_item_sequence calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = modulesModule.handlers.get_courses_course_id_module_item_sequence;
  assert.ok(handler, "Handler get_courses_course_id_module_item_sequence should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "asset_type": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/module_item_sequence");
  assert.deepStrictEqual(calledConfig.params, {"asset_type": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("post_courses_course_id_modules_module_id_items_id_mark_read calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = modulesModule.handlers.post_courses_course_id_modules_module_id_items_id_mark_read;
  assert.ok(handler, "Handler post_courses_course_id_modules_module_id_items_id_mark_read should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "module_id": "test_module_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/modules/test_module_id/items/test_id/mark_read");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_courses_course_id_modules_context_module_id_assignment_overrides calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = modulesModule.handlers.get_courses_course_id_modules_context_module_id_assignment_overrides;
  assert.ok(handler, "Handler get_courses_course_id_modules_context_module_id_assignment_overrides should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "context_module_id": "test_context_module_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/modules/test_context_module_id/assignment_overrides");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_courses_course_id_modules_context_module_id_assignment_overrides calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = modulesModule.handlers.put_courses_course_id_modules_context_module_id_assignment_overrides;
  assert.ok(handler, "Handler put_courses_course_id_modules_context_module_id_assignment_overrides should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "context_module_id": "test_context_module_id", "overrides[]": ["test_val"]});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/modules/test_context_module_id/assignment_overrides");
  assert.deepStrictEqual(calledConfig.data, {"overrides[]": ["test_val"]});
  assert.deepStrictEqual(result, { success: true });
});
