// Auto-generated tests for new_quizzes_accommodations
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const test = require("node:test");
const assert = require("node:assert");
const new_quizzes_accommodationsModule = require("../tools/new_quizzes_accommodations");

test("post_quiz_v1_courses_course_id_quizzes_assignment_id_accommodations calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = new_quizzes_accommodationsModule.handlers.post_quiz_v1_courses_course_id_quizzes_assignment_id_accommodations;
  assert.ok(handler, "Handler post_quiz_v1_courses_course_id_quizzes_assignment_id_accommodations should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "assignment_id": "test_assignment_id", "user_id": 123});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/quiz/v1/courses/test_course_id/quizzes/test_assignment_id/accommodations");
  assert.deepStrictEqual(calledConfig.data, {"user_id": 123});
  assert.deepStrictEqual(result, { success: true });
});

test("post_quiz_v1_courses_course_id_accommodations calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = new_quizzes_accommodationsModule.handlers.post_quiz_v1_courses_course_id_accommodations;
  assert.ok(handler, "Handler post_quiz_v1_courses_course_id_accommodations should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "user_id": 123});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/quiz/v1/courses/test_course_id/accommodations");
  assert.deepStrictEqual(calledConfig.data, {"user_id": 123});
  assert.deepStrictEqual(result, { success: true });
});
