// Auto-generated tests for notification_preferences
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const test = require("node:test");
const assert = require("node:assert");
const notification_preferencesModule = require("../tools/notification_preferences");

test("get_users_user_id_communication_channels_communication_channel_id_notification_preferences calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = notification_preferencesModule.handlers.get_users_user_id_communication_channels_communication_channel_id_notification_preferences;
  assert.ok(handler, "Handler get_users_user_id_communication_channels_communication_channel_id_notification_preferences should be defined");

  const result = await handler(mockClient, {"user_id": "test_user_id", "communication_channel_id": "test_communication_channel_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_user_id/communication_channels/test_communication_channel_id/notification_preferences");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_users_user_id_communication_channels_type_address_notification_preferences calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = notification_preferencesModule.handlers.get_users_user_id_communication_channels_type_address_notification_preferences;
  assert.ok(handler, "Handler get_users_user_id_communication_channels_type_address_notification_preferences should be defined");

  const result = await handler(mockClient, {"user_id": "test_user_id", "type": "test_type", "address": "test_address"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_user_id/communication_channels/test_type/test_address/notification_preferences");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_users_user_id_communication_channels_communication_channel_id_notification_preference_categories calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = notification_preferencesModule.handlers.get_users_user_id_communication_channels_communication_channel_id_notification_preference_categories;
  assert.ok(handler, "Handler get_users_user_id_communication_channels_communication_channel_id_notification_preference_categories should be defined");

  const result = await handler(mockClient, {"user_id": "test_user_id", "communication_channel_id": "test_communication_channel_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_user_id/communication_channels/test_communication_channel_id/notification_preference_categories");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_users_user_id_communication_channels_communication_channel_id_notification_preferences_notification calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = notification_preferencesModule.handlers.get_users_user_id_communication_channels_communication_channel_id_notification_preferences_notification;
  assert.ok(handler, "Handler get_users_user_id_communication_channels_communication_channel_id_notification_preferences_notification should be defined");

  const result = await handler(mockClient, {"user_id": "test_user_id", "communication_channel_id": "test_communication_channel_id", "notification": "test_notification"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_user_id/communication_channels/test_communication_channel_id/notification_preferences/test_notification");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_users_user_id_communication_channels_type_address_notification_preferences_notification calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = notification_preferencesModule.handlers.get_users_user_id_communication_channels_type_address_notification_preferences_notification;
  assert.ok(handler, "Handler get_users_user_id_communication_channels_type_address_notification_preferences_notification should be defined");

  const result = await handler(mockClient, {"user_id": "test_user_id", "type": "test_type", "address": "test_address", "notification": "test_notification"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_user_id/communication_channels/test_type/test_address/notification_preferences/test_notification");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_users_self_communication_channels_communication_channel_id_notification_preferences_notification calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = notification_preferencesModule.handlers.put_users_self_communication_channels_communication_channel_id_notification_preferences_notification;
  assert.ok(handler, "Handler put_users_self_communication_channels_communication_channel_id_notification_preferences_notification should be defined");

  const result = await handler(mockClient, {"communication_channel_id": "test_communication_channel_id", "notification": "test_notification"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/users/self/communication_channels/test_communication_channel_id/notification_preferences/test_notification");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_users_self_communication_channels_type_address_notification_preferences_notification calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = notification_preferencesModule.handlers.put_users_self_communication_channels_type_address_notification_preferences_notification;
  assert.ok(handler, "Handler put_users_self_communication_channels_type_address_notification_preferences_notification should be defined");

  const result = await handler(mockClient, {"type": "test_type", "address": "test_address", "notification": "test_notification", "notification_preferences[frequency]": "test_val"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/users/self/communication_channels/test_type/test_address/notification_preferences/test_notification");
  assert.deepStrictEqual(calledConfig.data, {"notification_preferences[frequency]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("put_users_self_communication_channels_communication_channel_id_notification_preference_categories_category calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = notification_preferencesModule.handlers.put_users_self_communication_channels_communication_channel_id_notification_preference_categories_category;
  assert.ok(handler, "Handler put_users_self_communication_channels_communication_channel_id_notification_preference_categories_category should be defined");

  const result = await handler(mockClient, {"communication_channel_id": "test_communication_channel_id", "category": "test_category", "notification_preferences[frequency]": "test_val"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/users/self/communication_channels/test_communication_channel_id/notification_preference_categories/test_category");
  assert.deepStrictEqual(calledConfig.data, {"notification_preferences[frequency]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("put_users_self_communication_channels_communication_channel_id_notification_preferences calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = notification_preferencesModule.handlers.put_users_self_communication_channels_communication_channel_id_notification_preferences;
  assert.ok(handler, "Handler put_users_self_communication_channels_communication_channel_id_notification_preferences should be defined");

  const result = await handler(mockClient, {"communication_channel_id": "test_communication_channel_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/users/self/communication_channels/test_communication_channel_id/notification_preferences");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_users_self_communication_channels_type_address_notification_preferences calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = notification_preferencesModule.handlers.put_users_self_communication_channels_type_address_notification_preferences;
  assert.ok(handler, "Handler put_users_self_communication_channels_type_address_notification_preferences should be defined");

  const result = await handler(mockClient, {"type": "test_type", "address": "test_address", "notification_preferences[<X>][frequency]": "test_val"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/users/self/communication_channels/test_type/test_address/notification_preferences");
  assert.deepStrictEqual(calledConfig.data, {"notification_preferences[<X>][frequency]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});
