// Auto-generated tests for pages
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const test = require("node:test");
const assert = require("node:assert");
const pagesModule = require("../tools/pages");

test("get_courses_course_id_front_page calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = pagesModule.handlers.get_courses_course_id_front_page;
  assert.ok(handler, "Handler get_courses_course_id_front_page should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/front_page");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_groups_group_id_front_page calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = pagesModule.handlers.get_groups_group_id_front_page;
  assert.ok(handler, "Handler get_groups_group_id_front_page should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/front_page");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_courses_course_id_pages_url_or_id_duplicate calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = pagesModule.handlers.post_courses_course_id_pages_url_or_id_duplicate;
  assert.ok(handler, "Handler post_courses_course_id_pages_url_or_id_duplicate should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "url_or_id": "test_url_or_id"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/pages/test_url_or_id/duplicate");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_courses_course_id_front_page calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = pagesModule.handlers.put_courses_course_id_front_page;
  assert.ok(handler, "Handler put_courses_course_id_front_page should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/front_page");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_groups_group_id_front_page calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = pagesModule.handlers.put_groups_group_id_front_page;
  assert.ok(handler, "Handler put_groups_group_id_front_page should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "wiki_page[title]": "test_val"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/front_page");
  assert.deepStrictEqual(calledConfig.data, {"wiki_page[title]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_courses_course_id_pages calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = pagesModule.handlers.get_courses_course_id_pages;
  assert.ok(handler, "Handler get_courses_course_id_pages should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/pages");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_groups_group_id_pages calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = pagesModule.handlers.get_groups_group_id_pages;
  assert.ok(handler, "Handler get_groups_group_id_pages should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "sort": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/pages");
  assert.deepStrictEqual(calledConfig.params, {"sort": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("post_courses_course_id_pages calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = pagesModule.handlers.post_courses_course_id_pages;
  assert.ok(handler, "Handler post_courses_course_id_pages should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/pages");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_groups_group_id_pages calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = pagesModule.handlers.post_groups_group_id_pages;
  assert.ok(handler, "Handler post_groups_group_id_pages should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "wiki_page[title]": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/pages");
  assert.deepStrictEqual(calledConfig.data, {"wiki_page[title]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_courses_course_id_pages_url_or_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = pagesModule.handlers.get_courses_course_id_pages_url_or_id;
  assert.ok(handler, "Handler get_courses_course_id_pages_url_or_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "url_or_id": "test_url_or_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/pages/test_url_or_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_groups_group_id_pages_url_or_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = pagesModule.handlers.get_groups_group_id_pages_url_or_id;
  assert.ok(handler, "Handler get_groups_group_id_pages_url_or_id should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "url_or_id": "test_url_or_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/pages/test_url_or_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_courses_course_id_pages_url_or_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = pagesModule.handlers.put_courses_course_id_pages_url_or_id;
  assert.ok(handler, "Handler put_courses_course_id_pages_url_or_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "url_or_id": "test_url_or_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/pages/test_url_or_id");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_groups_group_id_pages_url_or_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = pagesModule.handlers.put_groups_group_id_pages_url_or_id;
  assert.ok(handler, "Handler put_groups_group_id_pages_url_or_id should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "url_or_id": "test_url_or_id", "wiki_page[title]": "test_val"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/pages/test_url_or_id");
  assert.deepStrictEqual(calledConfig.data, {"wiki_page[title]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_courses_course_id_pages_url_or_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = pagesModule.handlers.delete_courses_course_id_pages_url_or_id;
  assert.ok(handler, "Handler delete_courses_course_id_pages_url_or_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "url_or_id": "test_url_or_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/pages/test_url_or_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_groups_group_id_pages_url_or_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = pagesModule.handlers.delete_groups_group_id_pages_url_or_id;
  assert.ok(handler, "Handler delete_groups_group_id_pages_url_or_id should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "url_or_id": "test_url_or_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/pages/test_url_or_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_courses_course_id_pages_url_or_id_revisions calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = pagesModule.handlers.get_courses_course_id_pages_url_or_id_revisions;
  assert.ok(handler, "Handler get_courses_course_id_pages_url_or_id_revisions should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "url_or_id": "test_url_or_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/pages/test_url_or_id/revisions");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_groups_group_id_pages_url_or_id_revisions calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = pagesModule.handlers.get_groups_group_id_pages_url_or_id_revisions;
  assert.ok(handler, "Handler get_groups_group_id_pages_url_or_id_revisions should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "url_or_id": "test_url_or_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/pages/test_url_or_id/revisions");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_courses_course_id_pages_url_or_id_revisions_latest calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = pagesModule.handlers.get_courses_course_id_pages_url_or_id_revisions_latest;
  assert.ok(handler, "Handler get_courses_course_id_pages_url_or_id_revisions_latest should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "url_or_id": "test_url_or_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/pages/test_url_or_id/revisions/latest");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_groups_group_id_pages_url_or_id_revisions_latest calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = pagesModule.handlers.get_groups_group_id_pages_url_or_id_revisions_latest;
  assert.ok(handler, "Handler get_groups_group_id_pages_url_or_id_revisions_latest should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "url_or_id": "test_url_or_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/pages/test_url_or_id/revisions/latest");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_courses_course_id_pages_url_or_id_revisions_revision_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = pagesModule.handlers.get_courses_course_id_pages_url_or_id_revisions_revision_id;
  assert.ok(handler, "Handler get_courses_course_id_pages_url_or_id_revisions_revision_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "url_or_id": "test_url_or_id", "revision_id": "test_revision_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/pages/test_url_or_id/revisions/test_revision_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_groups_group_id_pages_url_or_id_revisions_revision_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = pagesModule.handlers.get_groups_group_id_pages_url_or_id_revisions_revision_id;
  assert.ok(handler, "Handler get_groups_group_id_pages_url_or_id_revisions_revision_id should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "url_or_id": "test_url_or_id", "revision_id": "test_revision_id", "summary": true});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/pages/test_url_or_id/revisions/test_revision_id");
  assert.deepStrictEqual(calledConfig.params, {"summary": true});
  assert.deepStrictEqual(result, { success: true });
});

test("post_courses_course_id_pages_url_or_id_revisions_revision_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = pagesModule.handlers.post_courses_course_id_pages_url_or_id_revisions_revision_id;
  assert.ok(handler, "Handler post_courses_course_id_pages_url_or_id_revisions_revision_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "url_or_id": "test_url_or_id", "revision_id": "test_revision_id"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/pages/test_url_or_id/revisions/test_revision_id");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_groups_group_id_pages_url_or_id_revisions_revision_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = pagesModule.handlers.post_groups_group_id_pages_url_or_id_revisions_revision_id;
  assert.ok(handler, "Handler post_groups_group_id_pages_url_or_id_revisions_revision_id should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "url_or_id": "test_url_or_id", "revision_id": "test_revision_id"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/pages/test_url_or_id/revisions/test_revision_id");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});
