// Auto-generated tests for planner
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const test = require("node:test");
const assert = require("node:assert");
const plannerModule = require("../tools/planner");

test("get_planner_items calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = plannerModule.handlers.get_planner_items;
  assert.ok(handler, "Handler get_planner_items should be defined");

  const result = await handler(mockClient, {});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/planner/items");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_users_user_id_planner_items calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = plannerModule.handlers.get_users_user_id_planner_items;
  assert.ok(handler, "Handler get_users_user_id_planner_items should be defined");

  const result = await handler(mockClient, {"user_id": "test_user_id", "start_date": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_user_id/planner/items");
  assert.deepStrictEqual(calledConfig.params, {"start_date": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_planner_notes calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = plannerModule.handlers.get_planner_notes;
  assert.ok(handler, "Handler get_planner_notes should be defined");

  const result = await handler(mockClient, {"start_date": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/planner_notes");
  assert.deepStrictEqual(calledConfig.params, {"start_date": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_planner_notes_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = plannerModule.handlers.get_planner_notes_id;
  assert.ok(handler, "Handler get_planner_notes_id should be defined");

  const result = await handler(mockClient, {"id": "test_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/planner_notes/test_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_planner_notes_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = plannerModule.handlers.put_planner_notes_id;
  assert.ok(handler, "Handler put_planner_notes_id should be defined");

  const result = await handler(mockClient, {"id": "test_id", "title": "test_val"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/planner_notes/test_id");
  assert.deepStrictEqual(calledConfig.data, {"title": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("post_planner_notes calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = plannerModule.handlers.post_planner_notes;
  assert.ok(handler, "Handler post_planner_notes should be defined");

  const result = await handler(mockClient, {"title": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/planner_notes");
  assert.deepStrictEqual(calledConfig.data, {"title": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_planner_notes_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = plannerModule.handlers.delete_planner_notes_id;
  assert.ok(handler, "Handler delete_planner_notes_id should be defined");

  const result = await handler(mockClient, {"id": "test_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/planner_notes/test_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_planner_overrides calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = plannerModule.handlers.get_planner_overrides;
  assert.ok(handler, "Handler get_planner_overrides should be defined");

  const result = await handler(mockClient, {});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/planner/overrides");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_planner_overrides_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = plannerModule.handlers.get_planner_overrides_id;
  assert.ok(handler, "Handler get_planner_overrides_id should be defined");

  const result = await handler(mockClient, {"id": "test_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/planner/overrides/test_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_planner_overrides_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = plannerModule.handlers.put_planner_overrides_id;
  assert.ok(handler, "Handler put_planner_overrides_id should be defined");

  const result = await handler(mockClient, {"id": "test_id", "marked_complete": "test_val"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/planner/overrides/test_id");
  assert.deepStrictEqual(calledConfig.data, {"marked_complete": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("post_planner_overrides calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = plannerModule.handlers.post_planner_overrides;
  assert.ok(handler, "Handler post_planner_overrides should be defined");

  const result = await handler(mockClient, {"plannable_type": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/planner/overrides");
  assert.deepStrictEqual(calledConfig.data, {"plannable_type": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_planner_overrides_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = plannerModule.handlers.delete_planner_overrides_id;
  assert.ok(handler, "Handler delete_planner_overrides_id should be defined");

  const result = await handler(mockClient, {"id": "test_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/planner/overrides/test_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});
