// Auto-generated tests for proficiency_ratings
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const test = require("node:test");
const assert = require("node:assert");
const proficiency_ratingsModule = require("../tools/proficiency_ratings");

test("post_accounts_account_id_outcome_proficiency calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = proficiency_ratingsModule.handlers.post_accounts_account_id_outcome_proficiency;
  assert.ok(handler, "Handler post_accounts_account_id_outcome_proficiency should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/outcome_proficiency");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_courses_course_id_outcome_proficiency calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = proficiency_ratingsModule.handlers.post_courses_course_id_outcome_proficiency;
  assert.ok(handler, "Handler post_courses_course_id_outcome_proficiency should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "ratings[][description]": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/outcome_proficiency");
  assert.deepStrictEqual(calledConfig.data, {"ratings[][description]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_accounts_account_id_outcome_proficiency calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = proficiency_ratingsModule.handlers.get_accounts_account_id_outcome_proficiency;
  assert.ok(handler, "Handler get_accounts_account_id_outcome_proficiency should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/outcome_proficiency");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_courses_course_id_outcome_proficiency calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = proficiency_ratingsModule.handlers.get_courses_course_id_outcome_proficiency;
  assert.ok(handler, "Handler get_courses_course_id_outcome_proficiency should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/outcome_proficiency");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});
