// Auto-generated tests for progress
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const test = require("node:test");
const assert = require("node:assert");
const progressModule = require("../tools/progress");

test("get_progress_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = progressModule.handlers.get_progress_id;
  assert.ok(handler, "Handler get_progress_id should be defined");

  const result = await handler(mockClient, {"id": "test_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/progress/test_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_progress_id_cancel calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = progressModule.handlers.post_progress_id_cancel;
  assert.ok(handler, "Handler post_progress_id_cancel should be defined");

  const result = await handler(mockClient, {"id": "test_id"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/progress/test_id/cancel");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_courses_course_id_progress_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = progressModule.handlers.get_courses_course_id_progress_id;
  assert.ok(handler, "Handler get_courses_course_id_progress_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/lti/courses/test_course_id/progress/test_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});
