// Auto-generated tests for quizzes
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const test = require("node:test");
const assert = require("node:assert");
const quizzesModule = require("../tools/quizzes");

test("get_courses_course_id_quizzes calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = quizzesModule.handlers.get_courses_course_id_quizzes;
  assert.ok(handler, "Handler get_courses_course_id_quizzes should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "search_term": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/quizzes");
  assert.deepStrictEqual(calledConfig.params, {"search_term": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_courses_course_id_quizzes_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = quizzesModule.handlers.get_courses_course_id_quizzes_id;
  assert.ok(handler, "Handler get_courses_course_id_quizzes_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/quizzes/test_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_courses_course_id_quizzes calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = quizzesModule.handlers.post_courses_course_id_quizzes;
  assert.ok(handler, "Handler post_courses_course_id_quizzes should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "quiz[title]": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/quizzes");
  assert.deepStrictEqual(calledConfig.data, {"quiz[title]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("put_courses_course_id_quizzes_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = quizzesModule.handlers.put_courses_course_id_quizzes_id;
  assert.ok(handler, "Handler put_courses_course_id_quizzes_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "id": "test_id", "quiz[notify_of_update]": true});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/quizzes/test_id");
  assert.deepStrictEqual(calledConfig.data, {"quiz[notify_of_update]": true});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_courses_course_id_quizzes_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = quizzesModule.handlers.delete_courses_course_id_quizzes_id;
  assert.ok(handler, "Handler delete_courses_course_id_quizzes_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/quizzes/test_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_courses_course_id_quizzes_id_reorder calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = quizzesModule.handlers.post_courses_course_id_quizzes_id_reorder;
  assert.ok(handler, "Handler post_courses_course_id_quizzes_id_reorder should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "id": "test_id", "order[][id]": 123});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/quizzes/test_id/reorder");
  assert.deepStrictEqual(calledConfig.data, {"order[][id]": 123});
  assert.deepStrictEqual(result, { success: true });
});

test("post_courses_course_id_quizzes_id_validate_access_code calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = quizzesModule.handlers.post_courses_course_id_quizzes_id_validate_access_code;
  assert.ok(handler, "Handler post_courses_course_id_quizzes_id_validate_access_code should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "id": "test_id", "access_code": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/quizzes/test_id/validate_access_code");
  assert.deepStrictEqual(calledConfig.data, {"access_code": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});
