// Auto-generated tests for quiz_submission_files
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const test = require("node:test");
const assert = require("node:assert");
const quiz_submission_filesModule = require("../tools/quiz_submission_files");

test("post_courses_course_id_quizzes_quiz_id_submissions_self_files calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = quiz_submission_filesModule.handlers.post_courses_course_id_quizzes_quiz_id_submissions_self_files;
  assert.ok(handler, "Handler post_courses_course_id_quizzes_quiz_id_submissions_self_files should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "quiz_id": "test_quiz_id", "name": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/quizzes/test_quiz_id/submissions/self/files");
  assert.deepStrictEqual(calledConfig.data, {"name": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});
