// Auto-generated tests for smart_search
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const test = require("node:test");
const assert = require("node:assert");
const smart_searchModule = require("../tools/smart_search");

test("get_courses_course_id_smartsearch calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = smart_searchModule.handlers.get_courses_course_id_smartsearch;
  assert.ok(handler, "Handler get_courses_course_id_smartsearch should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "q": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/smartsearch");
  assert.deepStrictEqual(calledConfig.params, {"q": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});
