// Auto-generated tests for temporary_enrollment_pairings
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const test = require("node:test");
const assert = require("node:assert");
const temporary_enrollment_pairingsModule = require("../tools/temporary_enrollment_pairings");

test("get_accounts_account_id_temporary_enrollment_pairings calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = temporary_enrollment_pairingsModule.handlers.get_accounts_account_id_temporary_enrollment_pairings;
  assert.ok(handler, "Handler get_accounts_account_id_temporary_enrollment_pairings should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "include_deleted": true});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/temporary_enrollment_pairings");
  assert.deepStrictEqual(calledConfig.params, {"include_deleted": true});
  assert.deepStrictEqual(result, { success: true });
});

test("get_accounts_account_id_temporary_enrollment_pairings_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = temporary_enrollment_pairingsModule.handlers.get_accounts_account_id_temporary_enrollment_pairings_id;
  assert.ok(handler, "Handler get_accounts_account_id_temporary_enrollment_pairings_id should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/temporary_enrollment_pairings/test_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_accounts_account_id_temporary_enrollment_pairings_new calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = temporary_enrollment_pairingsModule.handlers.get_accounts_account_id_temporary_enrollment_pairings_new;
  assert.ok(handler, "Handler get_accounts_account_id_temporary_enrollment_pairings_new should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/temporary_enrollment_pairings/new");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_accounts_account_id_temporary_enrollment_pairings calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = temporary_enrollment_pairingsModule.handlers.post_accounts_account_id_temporary_enrollment_pairings;
  assert.ok(handler, "Handler post_accounts_account_id_temporary_enrollment_pairings should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "workflow_state": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/temporary_enrollment_pairings");
  assert.deepStrictEqual(calledConfig.data, {"workflow_state": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_accounts_account_id_temporary_enrollment_pairings_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = temporary_enrollment_pairingsModule.handlers.delete_accounts_account_id_temporary_enrollment_pairings_id;
  assert.ok(handler, "Handler delete_accounts_account_id_temporary_enrollment_pairings_id should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/temporary_enrollment_pairings/test_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});
