// Auto-generated MCP Tools for Canvas LMS API
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const { genericHandler } = require("./helper");

const definitions = [
  {
    "name": "get_users_user_id_user_generated_tokens",
    "description": "**Scope:** `url:GET|/api/v1/users/:user_id/user_generated_tokens` Returns a list of manually generated access tokens for the specified user. Note that the actual token values are only returned when the token is first created. Returns a list of [Token](#token) objects. [TokensController#show](https://github.com/instructure/canvas-lms/blob/master/app/controllers/tokens_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "user_id": {
          "type": "string",
          "description": "Path parameter: user_id"
        },
        "per_page": {
          "type": "number",
          "description": "The number of results to return per page. Defaults to 10. Maximum of 100."
        }
      },
      "required": [
        "user_id"
      ]
    }
  },
  {
    "name": "get_users_user_id_tokens_id",
    "description": "**Scope:** `url:GET|/api/v1/users/:user_id/tokens/:id` The ID can be the actual database ID of the token, or the 'token\\_hint' value. [TokensController#create](https://github.com/instructure/canvas-lms/blob/master/app/controllers/tokens_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "user_id": {
          "type": "string",
          "description": "Path parameter: user_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        }
      },
      "required": [
        "user_id",
        "id"
      ]
    }
  },
  {
    "name": "post_users_user_id_tokens",
    "description": "**Scope:** `url:POST|/api/v1/users/:user_id/tokens` Create a new access token for the specified user. If the user is not the current user, the token will be created as \"pending\", and must be activated by the user before it can be used. [TokensController#update](https://github.com/instructure/canvas-lms/blob/master/app/controllers/tokens_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "user_id": {
          "type": "string",
          "description": "Path parameter: user_id"
        },
        "token[purpose]": {
          "type": "string",
          "description": "The purpose of the token."
        },
        "token[expires_at]": {
          "type": "string",
          "description": "The time at which the token will expire."
        },
        "token[scopes][]": {
          "type": "array",
          "description": "<p>The scopes to associate with the token.<br>Ignored if the default developer key does not have the \"enable scopes\" option enabled.<br>In such cases, the token will inherit the user's permissions instead.</p>"
        }
      },
      "required": [
        "user_id",
        "token[purpose]"
      ]
    }
  },
  {
    "name": "put_users_user_id_tokens_id",
    "description": "**Scope:** `url:PUT|/api/v1/users/:user_id/tokens/:id` Update an existing access token. The ID can be the actual database ID of the token, or the 'token\\_hint' value. Regenerating an expired token requires a new expiration date. [TokensController#destroy](https://github.com/instructure/canvas-lms/blob/master/app/controllers/tokens_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "user_id": {
          "type": "string",
          "description": "Path parameter: user_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        },
        "token[purpose]": {
          "type": "string",
          "description": "The purpose of the token."
        },
        "token[expires_at]": {
          "type": "string",
          "description": "The time at which the token will expire."
        },
        "token[scopes][]": {
          "type": "array",
          "description": "The scopes to associate with the token."
        },
        "token[regenerate]": {
          "type": "boolean",
          "description": "Regenerate the actual token."
        }
      },
      "required": [
        "user_id",
        "id"
      ]
    }
  },
  {
    "name": "delete_users_user_id_tokens_id",
    "description": "**Scope:** `url:DELETE|/api/v1/users/:user_id/tokens/:id` The ID can be the actual database ID of the token, or the 'token\\_hint' value. *** This documentation is generated directly from the Canvas LMS source code, available [on Github](https://github.com/instructure/canvas-lms). --- This documentation is published with GitBook. GitBook is the documentation platform designed so that both humans and AI agents can read, navigate, and reason over technical content effectively. Learn more at gitb...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "user_id": {
          "type": "string",
          "description": "Path parameter: user_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        }
      },
      "required": [
        "user_id",
        "id"
      ]
    }
  }
];

const handlers = {
  get_users_user_id_user_generated_tokens: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/users/:user_id/user_generated_tokens", args);
  },
  get_users_user_id_tokens_id: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/users/:user_id/tokens/:id", args);
  },
  post_users_user_id_tokens: async (client, args) => {
    return genericHandler(client, "POST", "/api/v1/users/:user_id/tokens", args);
  },
  put_users_user_id_tokens_id: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/users/:user_id/tokens/:id", args);
  },
  delete_users_user_id_tokens_id: async (client, args) => {
    return genericHandler(client, "DELETE", "/api/v1/users/:user_id/tokens/:id", args);
  }
};

module.exports = {
  definitions,
  handlers
};
