// Auto-generated MCP Tools for Canvas LMS API
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const { genericHandler } = require("./helper");

const definitions = [
  {
    "name": "get_accounts_account_id",
    "description": "**Scope:** `url:GET|/api/lti/accounts/:account_id` Retrieve information on an individual account, given by local or global ID. Returns an [Account](#account) object. *** This documentation is generated directly from the Canvas LMS source code, available [on Github](https://github.com/instructure/canvas-lms). --- This documentation is published with GitBook. GitBook is the documentation platform designed so that both humans and AI agents can read, navigate, and reason over technical content ef...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "account_id"
      ]
    }
  }
];

const handlers = {
  get_accounts_account_id: async (client, args) => {
    return genericHandler(client, "GET", "/api/lti/accounts/:account_id", args);
  }
};

module.exports = {
  definitions,
  handlers
};
