// Auto-generated MCP Tools for Canvas LMS API
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const { genericHandler } = require("./helper");

const definitions = [
  {
    "name": "get_courses_course_id_block_editor_templates",
    "description": "**Scope:** `url:GET|/api/v1/courses/:course_id/block_editor_templates` A list of the block templates available to the current user. ```bash curl -H 'Authorization: Bearer ' \\ https:///api/v1/courses/123/block_editor_templates?sort=name&order=asc&drafts=true ``` Returns a list of [BlockEditorTemplate](#blockeditortemplate) objects. *** This documentation is generated directly from the Canvas LMS source code, available [on Github](https://github.com/instructure/canvas-lms). --- This documentati...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "sort": {
          "type": "string",
          "description": "Sort results by this field. Allowed values: `name`, `created_at`, `updated_at`"
        },
        "order": {
          "type": "string",
          "description": "The sorting order. Defaults to 'asc'. Allowed values: `asc`, `desc`"
        },
        "drafts": {
          "type": "boolean",
          "description": "<p>If true, include draft templates. If false or omitted<br>only published templates will be returned.</p>"
        },
        "type[]": {
          "type": "string",
          "description": "What type of templates should be returned. Allowed values: `page`, `section`, `block`"
        },
        "include[]": {
          "type": "string",
          "description": "no description Allowed values: `node_tree`, `thumbnail`"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "course_id"
      ]
    }
  }
];

const handlers = {
  get_courses_course_id_block_editor_templates: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/courses/:course_id/block_editor_templates", args);
  }
};

module.exports = {
  definitions,
  handlers
};
