// Auto-generated MCP Tools for Canvas LMS API
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const { genericHandler } = require("./helper");

const definitions = [
  {
    "name": "get_courses_course_id_collaborations",
    "description": "**Scope:** `url:GET|/api/v1/courses/:course_id/collaborations`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        }
      },
      "required": [
        "course_id"
      ]
    }
  },
  {
    "name": "get_groups_group_id_collaborations",
    "description": "**Scope:** `url:GET|/api/v1/groups/:group_id/collaborations` A paginated list of collaborations the current user has access to in the context of the course provided in the url. NOTE: this only returns ExternalToolCollaboration type collaborations. curl https\\://\\/api/v1/courses/1/collaborations/ Returns a list of [Collaboration](#collaboration) objects. [CollaborationsController#members](https://github.com/instructure/canvas-lms/blob/master/app/controllers/collaborations_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_id": {
          "type": "string",
          "description": "Path parameter: group_id"
        }
      },
      "required": [
        "group_id"
      ]
    }
  },
  {
    "name": "get_collaborations_id_members",
    "description": "**Scope:** `url:GET|/api/v1/collaborations/:id/members` A paginated list of the collaborators of a given collaboration ```bash curl https:///api/v1/courses/1/collaborations/1/members ``` Returns a list of [Collaborator](#collaborator) objects. [CollaborationsController#potential\\_collaborators](https://github.com/instructure/canvas-lms/blob/master/app/controllers/collaborations_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        },
        "include[]": {
          "type": "string",
          "description": "<p>- \"collaborator\\_lti\\_id\": Optional information to include with each member.<br>Represents an identifier to be used for the member in an LTI context.<br>- \"avatar\\_image\\_url\": Optional information to include with each member.<br>The url for the avatar of a collaborator with type 'user'. Allowed values: <code>collaborator\\_lti\\_id</code>, <code>avatar\\_image\\_url</code></p>"
        }
      },
      "required": [
        "id"
      ]
    }
  },
  {
    "name": "get_courses_course_id_potential_collaborators",
    "description": "**Scope:** `url:GET|/api/v1/courses/:course_id/potential_collaborators`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        }
      },
      "required": [
        "course_id"
      ]
    }
  },
  {
    "name": "get_groups_group_id_potential_collaborators",
    "description": "**Scope:** `url:GET|/api/v1/groups/:group_id/potential_collaborators` A paginated list of the users who can potentially be added to a collaboration in the given context. For courses, this consists of all enrolled users. For groups, it is comprised of the group members plus the admins of the course containing the group. Returns a list of [User](users.md#user) objects. *** This documentation is generated directly from the Canvas LMS source code, available [on Github](https://github.com/instruct...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_id": {
          "type": "string",
          "description": "Path parameter: group_id"
        }
      },
      "required": [
        "group_id"
      ]
    }
  }
];

const handlers = {
  get_courses_course_id_collaborations: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/courses/:course_id/collaborations", args);
  },
  get_groups_group_id_collaborations: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/groups/:group_id/collaborations", args);
  },
  get_collaborations_id_members: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/collaborations/:id/members", args);
  },
  get_courses_course_id_potential_collaborators: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/courses/:course_id/potential_collaborators", args);
  },
  get_groups_group_id_potential_collaborators: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/groups/:group_id/potential_collaborators", args);
  }
};

module.exports = {
  definitions,
  handlers
};
