// Auto-generated MCP Tools for Canvas LMS API
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const { genericHandler } = require("./helper");

const definitions = [
  {
    "name": "get_comm_messages",
    "description": "**Scope:** `url:GET|/api/v1/comm_messages` Retrieve a paginated list of messages sent to a user. Returns a list of [CommMessage](#commmessage) objects. *** This documentation is generated directly from the Canvas LMS source code, available [on Github](https://github.com/instructure/canvas-lms). --- This documentation is published with GitBook. GitBook is the documentation platform designed so that both humans and AI agents can read, navigate, and reason over technical content effectively. Lea...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "user_id": {
          "type": "string",
          "description": "The user id for whom you want to retrieve CommMessages"
        },
        "start_time": {
          "type": "string",
          "description": "<p>The beginning of the time range you want to retrieve message from.<br>Up to a year prior to the current date is available.</p>"
        },
        "end_time": {
          "type": "string",
          "description": "<p>The end of the time range you want to retrieve messages for.<br>Up to a year prior to the current date is available.</p>"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "user_id"
      ]
    }
  }
];

const handlers = {
  get_comm_messages: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/comm_messages", args);
  }
};

module.exports = {
  definitions,
  handlers
};
