// Auto-generated MCP Tools for Canvas LMS API
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const { genericHandler } = require("./helper");

const definitions = [
  {
    "name": "get_accounts_account_id_content_migrations_content_migration_id_migration_issues",
    "description": "**Scope:** `url:GET|/api/v1/accounts/:account_id/content_migrations/:content_migration_id/migration_issues`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        },
        "content_migration_id": {
          "type": "string",
          "description": "Path parameter: content_migration_id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "account_id",
        "content_migration_id"
      ]
    }
  },
  {
    "name": "get_courses_course_id_content_migrations_content_migration_id_migration_issues",
    "description": "**Scope:** `url:GET|/api/v1/courses/:course_id/content_migrations/:content_migration_id/migration_issues`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "content_migration_id": {
          "type": "string",
          "description": "Path parameter: content_migration_id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "course_id",
        "content_migration_id"
      ]
    }
  },
  {
    "name": "get_groups_group_id_content_migrations_content_migration_id_migration_issues",
    "description": "**Scope:** `url:GET|/api/v1/groups/:group_id/content_migrations/:content_migration_id/migration_issues`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_id": {
          "type": "string",
          "description": "Path parameter: group_id"
        },
        "content_migration_id": {
          "type": "string",
          "description": "Path parameter: content_migration_id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "group_id",
        "content_migration_id"
      ]
    }
  },
  {
    "name": "get_users_user_id_content_migrations_content_migration_id_migration_issues",
    "description": "**Scope:** `url:GET|/api/v1/users/:user_id/content_migrations/:content_migration_id/migration_issues` Returns paginated migration issues ```bash curl https:///api/v1/courses//content_migrations//migration_issues \\ -H 'Authorization: Bearer ' ``` Returns a list of [MigrationIssue](#migrationissue) objects. [MigrationIssuesController#show](https://github.com/instructure/canvas-lms/blob/master/app/controllers/migration_issues_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "user_id": {
          "type": "string",
          "description": "Path parameter: user_id"
        },
        "content_migration_id": {
          "type": "string",
          "description": "Path parameter: content_migration_id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "user_id",
        "content_migration_id"
      ]
    }
  },
  {
    "name": "get_accounts_account_id_content_migrations_content_migration_id_migration_issues_id",
    "description": "**Scope:** `url:GET|/api/v1/accounts/:account_id/content_migrations/:content_migration_id/migration_issues/:id`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        },
        "content_migration_id": {
          "type": "string",
          "description": "Path parameter: content_migration_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "account_id",
        "content_migration_id",
        "id"
      ]
    }
  },
  {
    "name": "get_courses_course_id_content_migrations_content_migration_id_migration_issues_id",
    "description": "**Scope:** `url:GET|/api/v1/courses/:course_id/content_migrations/:content_migration_id/migration_issues/:id`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "content_migration_id": {
          "type": "string",
          "description": "Path parameter: content_migration_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "course_id",
        "content_migration_id",
        "id"
      ]
    }
  },
  {
    "name": "get_groups_group_id_content_migrations_content_migration_id_migration_issues_id",
    "description": "**Scope:** `url:GET|/api/v1/groups/:group_id/content_migrations/:content_migration_id/migration_issues/:id`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_id": {
          "type": "string",
          "description": "Path parameter: group_id"
        },
        "content_migration_id": {
          "type": "string",
          "description": "Path parameter: content_migration_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "group_id",
        "content_migration_id",
        "id"
      ]
    }
  },
  {
    "name": "get_users_user_id_content_migrations_content_migration_id_migration_issues_id",
    "description": "**Scope:** `url:GET|/api/v1/users/:user_id/content_migrations/:content_migration_id/migration_issues/:id` Returns data on an individual migration issue ```bash curl https:///api/v1/courses//content_migrations//migration_issues/ \\ -H 'Authorization: Bearer ' ``` Returns a [MigrationIssue](#migrationissue) object. [MigrationIssuesController#update](https://github.com/instructure/canvas-lms/blob/master/app/controllers/migration_issues_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "user_id": {
          "type": "string",
          "description": "Path parameter: user_id"
        },
        "content_migration_id": {
          "type": "string",
          "description": "Path parameter: content_migration_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "user_id",
        "content_migration_id",
        "id"
      ]
    }
  },
  {
    "name": "put_accounts_account_id_content_migrations_content_migration_id_migration_issues_id",
    "description": "**Scope:** `url:PUT|/api/v1/accounts/:account_id/content_migrations/:content_migration_id/migration_issues/:id`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        },
        "content_migration_id": {
          "type": "string",
          "description": "Path parameter: content_migration_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        }
      },
      "required": [
        "account_id",
        "content_migration_id",
        "id"
      ]
    }
  },
  {
    "name": "put_courses_course_id_content_migrations_content_migration_id_migration_issues_id",
    "description": "**Scope:** `url:PUT|/api/v1/courses/:course_id/content_migrations/:content_migration_id/migration_issues/:id`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "content_migration_id": {
          "type": "string",
          "description": "Path parameter: content_migration_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        }
      },
      "required": [
        "course_id",
        "content_migration_id",
        "id"
      ]
    }
  },
  {
    "name": "put_groups_group_id_content_migrations_content_migration_id_migration_issues_id",
    "description": "**Scope:** `url:PUT|/api/v1/groups/:group_id/content_migrations/:content_migration_id/migration_issues/:id`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_id": {
          "type": "string",
          "description": "Path parameter: group_id"
        },
        "content_migration_id": {
          "type": "string",
          "description": "Path parameter: content_migration_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        }
      },
      "required": [
        "group_id",
        "content_migration_id",
        "id"
      ]
    }
  },
  {
    "name": "put_users_user_id_content_migrations_content_migration_id_migration_issues_id",
    "description": "**Scope:** `url:PUT|/api/v1/users/:user_id/content_migrations/:content_migration_id/migration_issues/:id` Update the workflow\\_state of a migration issue ```bash curl -X PUT https:///api/v1/courses//content_migrations//migration_issues/ \\ -H 'Authorization: Bearer ' \\ -F 'workflow_state=resolved' ``` Returns a [MigrationIssue](#migrationissue) object. [ContentMigrationsController#index](https://github.com/instructure/canvas-lms/blob/master/app/controllers/content_migrations_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "user_id": {
          "type": "string",
          "description": "Path parameter: user_id"
        },
        "content_migration_id": {
          "type": "string",
          "description": "Path parameter: content_migration_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        },
        "workflow_state": {
          "type": "string",
          "description": "Set the workflow\\_state of the issue. Allowed values: `active`, `resolved`"
        }
      },
      "required": [
        "user_id",
        "content_migration_id",
        "id",
        "workflow_state"
      ]
    }
  },
  {
    "name": "get_accounts_account_id_content_migrations",
    "description": "**Scope:** `url:GET|/api/v1/accounts/:account_id/content_migrations`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "account_id"
      ]
    }
  },
  {
    "name": "get_courses_course_id_content_migrations",
    "description": "**Scope:** `url:GET|/api/v1/courses/:course_id/content_migrations`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "course_id"
      ]
    }
  },
  {
    "name": "get_groups_group_id_content_migrations",
    "description": "**Scope:** `url:GET|/api/v1/groups/:group_id/content_migrations`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_id": {
          "type": "string",
          "description": "Path parameter: group_id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "group_id"
      ]
    }
  },
  {
    "name": "get_users_user_id_content_migrations",
    "description": "**Scope:** `url:GET|/api/v1/users/:user_id/content_migrations` Returns paginated content migrations ```bash curl https:///api/v1/courses//content_migrations \\ -H 'Authorization: Bearer ' ``` Returns a list of [ContentMigration](#contentmigration) objects. [ContentMigrationsController#show](https://github.com/instructure/canvas-lms/blob/master/app/controllers/content_migrations_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "user_id": {
          "type": "string",
          "description": "Path parameter: user_id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "user_id"
      ]
    }
  },
  {
    "name": "get_accounts_account_id_content_migrations_id",
    "description": "**Scope:** `url:GET|/api/v1/accounts/:account_id/content_migrations/:id`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "account_id",
        "id"
      ]
    }
  },
  {
    "name": "get_courses_course_id_content_migrations_id",
    "description": "**Scope:** `url:GET|/api/v1/courses/:course_id/content_migrations/:id`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "course_id",
        "id"
      ]
    }
  },
  {
    "name": "get_groups_group_id_content_migrations_id",
    "description": "**Scope:** `url:GET|/api/v1/groups/:group_id/content_migrations/:id`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_id": {
          "type": "string",
          "description": "Path parameter: group_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "group_id",
        "id"
      ]
    }
  },
  {
    "name": "get_users_user_id_content_migrations_id",
    "description": "**Scope:** `url:GET|/api/v1/users/:user_id/content_migrations/:id` Returns data on an individual content migration ```bash curl https:///api/v1/courses//content_migrations/ \\ -H 'Authorization: Bearer ' ``` Returns a [ContentMigration](#contentmigration) object. [ContentMigrationsController#create](https://github.com/instructure/canvas-lms/blob/master/app/controllers/content_migrations_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "user_id": {
          "type": "string",
          "description": "Path parameter: user_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "user_id",
        "id"
      ]
    }
  },
  {
    "name": "post_accounts_account_id_content_migrations",
    "description": "**Scope:** `url:POST|/api/v1/accounts/:account_id/content_migrations`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        }
      },
      "required": [
        "account_id"
      ]
    }
  },
  {
    "name": "post_courses_course_id_content_migrations",
    "description": "**Scope:** `url:POST|/api/v1/courses/:course_id/content_migrations`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        }
      },
      "required": [
        "course_id"
      ]
    }
  },
  {
    "name": "post_groups_group_id_content_migrations",
    "description": "**Scope:** `url:POST|/api/v1/groups/:group_id/content_migrations`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_id": {
          "type": "string",
          "description": "Path parameter: group_id"
        }
      },
      "required": [
        "group_id"
      ]
    }
  },
  {
    "name": "post_users_user_id_content_migrations",
    "description": "**Scope:** `url:POST|/api/v1/users/:user_id/content_migrations` Create a content migration. If the migration requires a file to be uploaded the actual processing of the file will start once the file upload process is completed. File uploading works as described in the [File Upload Documentation](../basics/file.file_uploads.md) except that the values are set on a *pre\\_attachment* sub-hash. For migrations that don't require a file to be uploaded, like course copy, the processing will begin as ...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "user_id": {
          "type": "string",
          "description": "Path parameter: user_id"
        },
        "migration_type": {
          "type": "string",
          "description": "<p>The type of the migration. Use the<br><a href=\"#method.content_migrations.available_migrators\">Migrator</a> endpoint to<br>see all available migrators. Default allowed values:<br>canvas\\_cartridge\\_importer, common\\_cartridge\\_importer,<br>course\\_copy\\_importer, zip\\_file\\_importer, qti\\_converter, moodle\\_converter</p>"
        },
        "pre_attachment[name]": {
          "type": "string",
          "description": "<p>Required if uploading a file. This is the first step in uploading a file<br>to the content migration. See the <a href=\"../basics/file.file_uploads.md\">File Upload Documentation</a> for details on the file upload workflow.</p>"
        },
        "pre_attachment[*]": {
          "type": "string",
          "description": "Other file upload properties, See [File Upload Documentation](../basics/file.file_uploads.md)"
        },
        "settings[file_url]": {
          "type": "string",
          "description": "A URL to download the file from. Must not require authentication."
        },
        "settings[content_export_id]": {
          "type": "string",
          "description": "<p>The id of a ContentExport to import. This allows you to import content previously exported from Canvas<br>without needing to download and re-upload it.</p>"
        },
        "settings[source_course_id]": {
          "type": "string",
          "description": "<p>The course to copy from for a course copy migration. (required if doing<br>course copy)</p>"
        },
        "settings[folder_id]": {
          "type": "string",
          "description": "The folder to unzip the .zip file into for a zip\\_file\\_import."
        },
        "settings[overwrite_quizzes]": {
          "type": "boolean",
          "description": "<p>Whether to overwrite quizzes with the same identifiers between content<br>packages.</p>"
        },
        "settings[question_bank_id]": {
          "type": "number",
          "description": "<p>The existing question bank ID to import questions into if not specified in<br>the content package.</p>"
        },
        "settings[question_bank_name]": {
          "type": "string",
          "description": "<p>The question bank to import questions into if not specified in the content<br>package, if both bank id and name are set, id will take precedence.</p>"
        },
        "settings[insert_into_module_id]": {
          "type": "number",
          "description": "<p>The id of a module in the target course. This will add all imported items<br>(that can be added to a module) to the given module.</p>"
        },
        "settings[insert_into_module_type]": {
          "type": "string",
          "description": "<p>If provided (and +insert\\_into\\_module\\_id+ is supplied),<br>only add objects of the specified type to the module. Allowed values: <code>assignment</code>, <code>discussion\\_topic</code>, <code>file</code>, <code>page</code>, <code>quiz</code></p>"
        },
        "settings[insert_into_module_position]": {
          "type": "number",
          "description": "<p>The (1-based) position to insert the imported items into the course<br>(if +insert\\_into\\_module\\_id+ is supplied). If this parameter<br>is omitted, items will be added to the end of the module.</p>"
        },
        "settings[move_to_assignment_group_id]": {
          "type": "number",
          "description": "<p>The id of an assignment group in the target course. If provided, all<br>imported assignments will be moved to the given assignment group.</p>"
        },
        "settings[importer_skips]": {
          "type": "array",
          "description": "Set of importers to skip, even if otherwise selected by migration settings. Allowed values: `all_course_settings`, `visibility_settings`"
        },
        "settings[import_blueprint_settings]": {
          "type": "boolean",
          "description": "<p>Import the \"use as blueprint course\" setting as well as the list of locked items<br>from the source course or package. The destination course must not be associated<br>with an existing blueprint course and cannot have any student or observer enrollments.</p>"
        },
        "date_shift_options[shift_dates]": {
          "type": "boolean",
          "description": "Whether to shift dates in the copied course"
        },
        "date_shift_options[old_start_date]": {
          "type": "string",
          "description": "The original start date of the source content/course"
        },
        "date_shift_options[old_end_date]": {
          "type": "string",
          "description": "The original end date of the source content/course"
        },
        "date_shift_options[new_start_date]": {
          "type": "string",
          "description": "The new start date for the content/course"
        },
        "date_shift_options[new_end_date]": {
          "type": "string",
          "description": "The new end date for the source content/course"
        },
        "date_shift_options[day_substitutions][X]": {
          "type": "number",
          "description": "<p>Move anything scheduled for day 'X' to the specified day. (0-Sunday,<br>1-Monday, 2-Tuesday, 3-Wednesday, 4-Thursday, 5-Friday, 6-Saturday)</p>"
        },
        "date_shift_options[remove_dates]": {
          "type": "boolean",
          "description": "<p>Whether to remove dates in the copied course. Cannot be used<br>in conjunction with <em>shift\\_dates</em>.</p>"
        },
        "selective_import": {
          "type": "boolean",
          "description": "<p>If set, perform a selective import instead of importing all content.<br>The migration will identify the contents of the package and then stop<br>in the +waiting\\_for\\_select+ workflow state. At this point, use the<br><a href=\"#method.content_migrations.content_list\">List items endpoint</a><br>to enumerate the contents of the package, identifying the copy<br>parameters for the desired content. Then call the<br><a href=\"#method.content_migrations.update\">Update endpoint</a> and provide these<br>copy parameters to start the import.</p>"
        },
        "select": {
          "type": "string",
          "description": "<p>For +course\\_copy\\_importer+ migrations, this parameter allows you to select<br>the objects to copy without using the +selective\\_import+ argument and<br>+waiting\\_for\\_select+ state as is required for uploaded imports (though that<br>workflow is also supported for course copy migrations).<br>The keys are object types like 'files', 'folders', 'pages', etc. The value<br>for each key is a list of object ids. An id can be an integer or a string.<br>Multiple object types can be selected in the same call. Allowed values: <code>folders</code>, <code>files</code>, <code>attachments</code>, <code>quizzes</code>, <code>assignments</code>, <code>announcements</code>, <code>calendar\\_events</code>, <code>discussion\\_topics</code>, <code>modules</code>, <code>module\\_items</code>, <code>pages</code>, <code>rubrics</code></p>"
        }
      },
      "required": [
        "user_id",
        "migration_type"
      ]
    }
  },
  {
    "name": "put_accounts_account_id_content_migrations_id",
    "description": "**Scope:** `url:PUT|/api/v1/accounts/:account_id/content_migrations/:id`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        }
      },
      "required": [
        "account_id",
        "id"
      ]
    }
  },
  {
    "name": "put_courses_course_id_content_migrations_id",
    "description": "**Scope:** `url:PUT|/api/v1/courses/:course_id/content_migrations/:id`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        }
      },
      "required": [
        "course_id",
        "id"
      ]
    }
  },
  {
    "name": "put_groups_group_id_content_migrations_id",
    "description": "**Scope:** `url:PUT|/api/v1/groups/:group_id/content_migrations/:id`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_id": {
          "type": "string",
          "description": "Path parameter: group_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        }
      },
      "required": [
        "group_id",
        "id"
      ]
    }
  },
  {
    "name": "put_users_user_id_content_migrations_id",
    "description": "**Scope:** `url:PUT|/api/v1/users/:user_id/content_migrations/:id` Update a content migration. Takes same arguments as [create](#method.content_migrations.create) except that you can't change the migration type. However, changing most settings after the migration process has started will not do anything. Generally updating the content migration will be used when there is a file upload problem, or when importing content selectively. If the first upload has a problem you can supply new *pre\\_at...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "user_id": {
          "type": "string",
          "description": "Path parameter: user_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        }
      },
      "required": [
        "user_id",
        "id"
      ]
    }
  },
  {
    "name": "get_accounts_account_id_content_migrations_migrators",
    "description": "**Scope:** `url:GET|/api/v1/accounts/:account_id/content_migrations/migrators`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "account_id"
      ]
    }
  },
  {
    "name": "get_courses_course_id_content_migrations_migrators",
    "description": "**Scope:** `url:GET|/api/v1/courses/:course_id/content_migrations/migrators`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "course_id"
      ]
    }
  },
  {
    "name": "get_groups_group_id_content_migrations_migrators",
    "description": "**Scope:** `url:GET|/api/v1/groups/:group_id/content_migrations/migrators`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_id": {
          "type": "string",
          "description": "Path parameter: group_id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "group_id"
      ]
    }
  },
  {
    "name": "get_users_user_id_content_migrations_migrators",
    "description": "**Scope:** `url:GET|/api/v1/users/:user_id/content_migrations/migrators` Lists the currently available migration types. These values may change. Returns a list of [Migrator](#migrator) objects. [ContentMigrationsController#content\\_list](https://github.com/instructure/canvas-lms/blob/master/app/controllers/content_migrations_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "user_id": {
          "type": "string",
          "description": "Path parameter: user_id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "user_id"
      ]
    }
  },
  {
    "name": "get_accounts_account_id_content_migrations_id_selective_data",
    "description": "**Scope:** `url:GET|/api/v1/accounts/:account_id/content_migrations/:id/selective_data`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "account_id",
        "id"
      ]
    }
  },
  {
    "name": "get_courses_course_id_content_migrations_id_selective_data",
    "description": "**Scope:** `url:GET|/api/v1/courses/:course_id/content_migrations/:id/selective_data`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "course_id",
        "id"
      ]
    }
  },
  {
    "name": "get_groups_group_id_content_migrations_id_selective_data",
    "description": "**Scope:** `url:GET|/api/v1/groups/:group_id/content_migrations/:id/selective_data`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_id": {
          "type": "string",
          "description": "Path parameter: group_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "group_id",
        "id"
      ]
    }
  },
  {
    "name": "get_users_user_id_content_migrations_id_selective_data",
    "description": "**Scope:** `url:GET|/api/v1/users/:user_id/content_migrations/:id/selective_data` Enumerates the content available for selective import in a tree structure. Each node provides a +property+ copy argument that can be supplied to the [Update endpoint](#method.content_migrations.update) to selectively copy the content associated with that tree node and its children. Each node may also provide a +sub\\_items\\_url+ or an array of +sub\\_items+ which you can use to obtain copy parameters for a subset ...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "user_id": {
          "type": "string",
          "description": "Path parameter: user_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        },
        "type": {
          "type": "string",
          "description": "The type of content to enumerate. Allowed values: `context_modules`, `assignments`, `quizzes`, `assessment_question_banks`, `discussion_topics`, `wiki_pages`, `context_external_tools`, `tool_profiles`, `announcements`, `calendar_events`, `rubrics`, `groups`, `learning_outcomes`, `attachments`"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "user_id",
        "id"
      ]
    }
  },
  {
    "name": "get_courses_course_id_content_migrations_id_asset_id_mapping",
    "description": "**Scope:** `url:GET|/api/v1/courses/:course_id/content_migrations/:id/asset_id_mapping` Given a complete course copy or blueprint import content migration, return a mapping of asset ids from the source course to the destination course that were copied in this migration or an earlier one with the same course pair and migration\\_type (course copy or blueprint). The returned object's keys are asset types as they appear in API URLs (+announcements+, +assignments+, +discussion\\_topics+, +files+, +...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "course_id",
        "id"
      ]
    }
  }
];

const handlers = {
  get_accounts_account_id_content_migrations_content_migration_id_migration_issues: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/accounts/:account_id/content_migrations/:content_migration_id/migration_issues", args);
  },
  get_courses_course_id_content_migrations_content_migration_id_migration_issues: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/courses/:course_id/content_migrations/:content_migration_id/migration_issues", args);
  },
  get_groups_group_id_content_migrations_content_migration_id_migration_issues: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/groups/:group_id/content_migrations/:content_migration_id/migration_issues", args);
  },
  get_users_user_id_content_migrations_content_migration_id_migration_issues: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/users/:user_id/content_migrations/:content_migration_id/migration_issues", args);
  },
  get_accounts_account_id_content_migrations_content_migration_id_migration_issues_id: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/accounts/:account_id/content_migrations/:content_migration_id/migration_issues/:id", args);
  },
  get_courses_course_id_content_migrations_content_migration_id_migration_issues_id: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/courses/:course_id/content_migrations/:content_migration_id/migration_issues/:id", args);
  },
  get_groups_group_id_content_migrations_content_migration_id_migration_issues_id: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/groups/:group_id/content_migrations/:content_migration_id/migration_issues/:id", args);
  },
  get_users_user_id_content_migrations_content_migration_id_migration_issues_id: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/users/:user_id/content_migrations/:content_migration_id/migration_issues/:id", args);
  },
  put_accounts_account_id_content_migrations_content_migration_id_migration_issues_id: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/accounts/:account_id/content_migrations/:content_migration_id/migration_issues/:id", args);
  },
  put_courses_course_id_content_migrations_content_migration_id_migration_issues_id: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/courses/:course_id/content_migrations/:content_migration_id/migration_issues/:id", args);
  },
  put_groups_group_id_content_migrations_content_migration_id_migration_issues_id: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/groups/:group_id/content_migrations/:content_migration_id/migration_issues/:id", args);
  },
  put_users_user_id_content_migrations_content_migration_id_migration_issues_id: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/users/:user_id/content_migrations/:content_migration_id/migration_issues/:id", args);
  },
  get_accounts_account_id_content_migrations: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/accounts/:account_id/content_migrations", args);
  },
  get_courses_course_id_content_migrations: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/courses/:course_id/content_migrations", args);
  },
  get_groups_group_id_content_migrations: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/groups/:group_id/content_migrations", args);
  },
  get_users_user_id_content_migrations: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/users/:user_id/content_migrations", args);
  },
  get_accounts_account_id_content_migrations_id: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/accounts/:account_id/content_migrations/:id", args);
  },
  get_courses_course_id_content_migrations_id: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/courses/:course_id/content_migrations/:id", args);
  },
  get_groups_group_id_content_migrations_id: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/groups/:group_id/content_migrations/:id", args);
  },
  get_users_user_id_content_migrations_id: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/users/:user_id/content_migrations/:id", args);
  },
  post_accounts_account_id_content_migrations: async (client, args) => {
    return genericHandler(client, "POST", "/api/v1/accounts/:account_id/content_migrations", args);
  },
  post_courses_course_id_content_migrations: async (client, args) => {
    return genericHandler(client, "POST", "/api/v1/courses/:course_id/content_migrations", args);
  },
  post_groups_group_id_content_migrations: async (client, args) => {
    return genericHandler(client, "POST", "/api/v1/groups/:group_id/content_migrations", args);
  },
  post_users_user_id_content_migrations: async (client, args) => {
    return genericHandler(client, "POST", "/api/v1/users/:user_id/content_migrations", args);
  },
  put_accounts_account_id_content_migrations_id: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/accounts/:account_id/content_migrations/:id", args);
  },
  put_courses_course_id_content_migrations_id: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/courses/:course_id/content_migrations/:id", args);
  },
  put_groups_group_id_content_migrations_id: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/groups/:group_id/content_migrations/:id", args);
  },
  put_users_user_id_content_migrations_id: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/users/:user_id/content_migrations/:id", args);
  },
  get_accounts_account_id_content_migrations_migrators: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/accounts/:account_id/content_migrations/migrators", args);
  },
  get_courses_course_id_content_migrations_migrators: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/courses/:course_id/content_migrations/migrators", args);
  },
  get_groups_group_id_content_migrations_migrators: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/groups/:group_id/content_migrations/migrators", args);
  },
  get_users_user_id_content_migrations_migrators: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/users/:user_id/content_migrations/migrators", args);
  },
  get_accounts_account_id_content_migrations_id_selective_data: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/accounts/:account_id/content_migrations/:id/selective_data", args);
  },
  get_courses_course_id_content_migrations_id_selective_data: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/courses/:course_id/content_migrations/:id/selective_data", args);
  },
  get_groups_group_id_content_migrations_id_selective_data: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/groups/:group_id/content_migrations/:id/selective_data", args);
  },
  get_users_user_id_content_migrations_id_selective_data: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/users/:user_id/content_migrations/:id/selective_data", args);
  },
  get_courses_course_id_content_migrations_id_asset_id_mapping: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/courses/:course_id/content_migrations/:id/asset_id_mapping", args);
  }
};

module.exports = {
  definitions,
  handlers
};
