// Auto-generated MCP Tools for Canvas LMS API
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const { genericHandler } = require("./helper");

const definitions = [
  {
    "name": "get_courses_course_id_csp_settings",
    "description": "**Scope:** `url:GET|/api/v1/courses/:course_id/csp_settings`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "course_id"
      ]
    }
  },
  {
    "name": "get_accounts_account_id_csp_settings",
    "description": "**Scope:** `url:GET|/api/v1/accounts/:account_id/csp_settings` Update multiple modules in an account. * enabled Whether CSP is enabled. * inherited Whether the current CSP settings are inherited from a parent account. * settings\\_locked Whether current CSP settings can be overridden by sub-accounts and courses. * effective\\_whitelist If enabled, lists the currently allowed domains (includes domains automatically allowed through external tools). * tools\\_whitelist (Account-only) Lists the auto...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "account_id"
      ]
    }
  },
  {
    "name": "put_courses_course_id_csp_settings",
    "description": "**Scope:** `url:PUT|/api/v1/courses/:course_id/csp_settings`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        }
      },
      "required": [
        "course_id"
      ]
    }
  },
  {
    "name": "put_accounts_account_id_csp_settings",
    "description": "**Scope:** `url:PUT|/api/v1/accounts/:account_id/csp_settings` Either explicitly sets CSP to be on or off for courses and sub-accounts, or clear the explicit settings to default to those set by a parent account Note: If \"inherited\" and \"settings\\_locked\" are both true for this account or course, then the CSP setting cannot be modified. [CspSettingsController#set\\_csp\\_lock](https://github.com/instructure/canvas-lms/blob/master/app/controllers/csp_settings_controller.rb) {% hint style=\"warning...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        },
        "status": {
          "type": "string",
          "description": "<p>If set to \"enabled\" for an account, CSP will be enabled for all its courses and sub-accounts (that<br>have not explicitly enabled or disabled it), using the allowed domains set on this account.<br>If set to \"disabled\", CSP will be disabled for this account or course and for all sub-accounts<br>that have not explicitly re-enabled it.<br>If set to \"inherited\", this account or course will reset to the default state where CSP settings<br>are inherited from the first parent account to have them explicitly set. Allowed values: <code>enabled</code>, <code>disabled</code>, <code>inherited</code></p>"
        }
      },
      "required": [
        "account_id",
        "status"
      ]
    }
  },
  {
    "name": "put_accounts_account_id_csp_settings_lock",
    "description": "**Scope:** `url:PUT|/api/v1/accounts/:account_id/csp_settings/lock` Can only be set if CSP is explicitly enabled or disabled on this account (i.e. \"inherited\" is false). [CspSettingsController#add\\_domain](https://github.com/instructure/canvas-lms/blob/master/app/controllers/csp_settings_controller.rb) {% hint style=\"warning\" %} BETA: This API endpoint is not finalized, and there could be breaking changes before its final release. {% endhint %}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        },
        "settings_locked": {
          "type": "boolean",
          "description": "Whether sub-accounts and courses will be prevented from overriding settings inherited from this account."
        }
      },
      "required": [
        "account_id",
        "settings_locked"
      ]
    }
  },
  {
    "name": "post_accounts_account_id_csp_settings_domains",
    "description": "**Scope:** `url:POST|/api/v1/accounts/:account_id/csp_settings/domains` Adds an allowed domain for the current account. Note: this will not take effect unless CSP is explicitly enabled on this account. [CspSettingsController#add\\_multiple\\_domains](https://github.com/instructure/canvas-lms/blob/master/app/controllers/csp_settings_controller.rb) {% hint style=\"warning\" %} BETA: This API endpoint is not finalized, and there could be breaking changes before its final release. {% endhint %}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        },
        "domain": {
          "type": "string",
          "description": "no description"
        }
      },
      "required": [
        "account_id",
        "domain"
      ]
    }
  },
  {
    "name": "post_accounts_account_id_csp_settings_domains_batch_create",
    "description": "**Scope:** `url:POST|/api/v1/accounts/:account_id/csp_settings/domains/batch_create` Adds multiple allowed domains for the current account. Note: this will not take effect unless CSP is explicitly enabled on this account. [CspSettingsController#remove\\_domain](https://github.com/instructure/canvas-lms/blob/master/app/controllers/csp_settings_controller.rb) {% hint style=\"warning\" %} BETA: This API endpoint is not finalized, and there could be breaking changes before its final release. {% endh...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        },
        "domains": {
          "type": "array",
          "description": "no description"
        }
      },
      "required": [
        "account_id",
        "domains"
      ]
    }
  },
  {
    "name": "delete_accounts_account_id_csp_settings_domains",
    "description": "**Scope:** `url:DELETE|/api/v1/accounts/:account_id/csp_settings/domains` Removes an allowed domain from the current account. *** This documentation is generated directly from the Canvas LMS source code, available [on Github](https://github.com/instructure/canvas-lms). --- This documentation is published with GitBook. GitBook is the documentation platform designed so that both humans and AI agents can read, navigate, and reason over technical content effectively. Learn more at gitbook.com. If...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        },
        "domain": {
          "type": "string",
          "description": "no description"
        }
      },
      "required": [
        "account_id",
        "domain"
      ]
    }
  }
];

const handlers = {
  get_courses_course_id_csp_settings: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/courses/:course_id/csp_settings", args);
  },
  get_accounts_account_id_csp_settings: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/accounts/:account_id/csp_settings", args);
  },
  put_courses_course_id_csp_settings: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/courses/:course_id/csp_settings", args);
  },
  put_accounts_account_id_csp_settings: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/accounts/:account_id/csp_settings", args);
  },
  put_accounts_account_id_csp_settings_lock: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/accounts/:account_id/csp_settings/lock", args);
  },
  post_accounts_account_id_csp_settings_domains: async (client, args) => {
    return genericHandler(client, "POST", "/api/v1/accounts/:account_id/csp_settings/domains", args);
  },
  post_accounts_account_id_csp_settings_domains_batch_create: async (client, args) => {
    return genericHandler(client, "POST", "/api/v1/accounts/:account_id/csp_settings/domains/batch_create", args);
  },
  delete_accounts_account_id_csp_settings_domains: async (client, args) => {
    return genericHandler(client, "DELETE", "/api/v1/accounts/:account_id/csp_settings/domains", args);
  }
};

module.exports = {
  definitions,
  handlers
};
