// Auto-generated MCP Tools for Canvas LMS API
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const { genericHandler } = require("./helper");

const definitions = [
  {
    "name": "get_courses_course_id_custom_gradebook_columns",
    "description": "**Scope:** `url:GET|/api/v1/courses/:course_id/custom_gradebook_columns` A paginated list of all custom gradebook columns for a course Returns a list of [CustomColumn](#customcolumn) objects. [CustomGradebookColumnsApiController#create](https://github.com/instructure/canvas-lms/blob/master/app/controllers/custom_gradebook_columns_api_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "include_hidden": {
          "type": "boolean",
          "description": "Include hidden parameters (defaults to false)"
        }
      },
      "required": [
        "course_id"
      ]
    }
  },
  {
    "name": "post_courses_course_id_custom_gradebook_columns",
    "description": "**Scope:** `url:POST|/api/v1/courses/:course_id/custom_gradebook_columns` Create a custom gradebook column Returns a [CustomColumn](#customcolumn) object. [CustomGradebookColumnsApiController#update](https://github.com/instructure/canvas-lms/blob/master/app/controllers/custom_gradebook_columns_api_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "column[title]": {
          "type": "string",
          "description": "no description"
        },
        "column[position]": {
          "type": "number",
          "description": "The position of the column relative to other custom columns"
        },
        "column[hidden]": {
          "type": "boolean",
          "description": "Hidden columns are not displayed in the gradebook"
        },
        "column[teacher_notes]": {
          "type": "boolean",
          "description": "<p>Set this if the column is created by a teacher. The gradebook only<br>supports one teacher\\_notes column.</p>"
        },
        "column[read_only]": {
          "type": "boolean",
          "description": "Set this to prevent the column from being editable in the gradebook ui"
        }
      },
      "required": [
        "course_id",
        "column[title]"
      ]
    }
  },
  {
    "name": "put_courses_course_id_custom_gradebook_columns_id",
    "description": "**Scope:** `url:PUT|/api/v1/courses/:course_id/custom_gradebook_columns/:id` Accepts the same parameters as custom gradebook column creation Returns a [CustomColumn](#customcolumn) object. [CustomGradebookColumnsApiController#destroy](https://github.com/instructure/canvas-lms/blob/master/app/controllers/custom_gradebook_columns_api_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        }
      },
      "required": [
        "course_id",
        "id"
      ]
    }
  },
  {
    "name": "delete_courses_course_id_custom_gradebook_columns_id",
    "description": "**Scope:** `url:DELETE|/api/v1/courses/:course_id/custom_gradebook_columns/:id` Permanently deletes a custom column and its associated data Returns a [CustomColumn](#customcolumn) object. [CustomGradebookColumnsApiController#reorder](https://github.com/instructure/canvas-lms/blob/master/app/controllers/custom_gradebook_columns_api_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        }
      },
      "required": [
        "course_id",
        "id"
      ]
    }
  },
  {
    "name": "post_courses_course_id_custom_gradebook_columns_reorder",
    "description": "**Scope:** `url:POST|/api/v1/courses/:course_id/custom_gradebook_columns/reorder` Puts the given columns in the specified order \\200 OK\\ is returned if successful [CustomGradebookColumnDataApiController#index](https://github.com/instructure/canvas-lms/blob/master/app/controllers/custom_gradebook_column_data_api_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "order[]": {
          "type": "number",
          "description": "no description"
        }
      },
      "required": [
        "course_id",
        "order[]"
      ]
    }
  },
  {
    "name": "get_courses_course_id_custom_gradebook_columns_id_data",
    "description": "**Scope:** `url:GET|/api/v1/courses/:course_id/custom_gradebook_columns/:id/data` This does not list entries for students without associated data. Returns a list of [ColumnDatum](#columndatum) objects. [CustomGradebookColumnDataApiController#update](https://github.com/instructure/canvas-lms/blob/master/app/controllers/custom_gradebook_column_data_api_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        },
        "include_hidden": {
          "type": "boolean",
          "description": "<p>If true, hidden columns will be included in the<br>result. If false or absent, only visible columns<br>will be returned.</p>"
        }
      },
      "required": [
        "course_id",
        "id"
      ]
    }
  },
  {
    "name": "put_courses_course_id_custom_gradebook_columns_id_data_user_id",
    "description": "**Scope:** `url:PUT|/api/v1/courses/:course_id/custom_gradebook_columns/:id/data/:user_id` Set the content of a custom column Returns a [ColumnDatum](#columndatum) object. [CustomGradebookColumnDataApiController#bulk\\_update](https://github.com/instructure/canvas-lms/blob/master/app/controllers/custom_gradebook_column_data_api_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        },
        "user_id": {
          "type": "string",
          "description": "Path parameter: user_id"
        },
        "column_data[content]": {
          "type": "string",
          "description": "Column content. Setting this to blank will delete the datum object."
        }
      },
      "required": [
        "course_id",
        "id",
        "user_id",
        "column_data[content]"
      ]
    }
  },
  {
    "name": "put_courses_course_id_custom_gradebook_column_data",
    "description": "**Scope:** `url:PUT|/api/v1/courses/:course_id/custom_gradebook_column_data` Set the content of custom columns { \"column\\_data\": \\[ { \"column\\_id\": example\\_column\\_id, \"user\\_id\": example\\_student\\_id, \"content\": example\\_content }, { \"column\\_id\": example\\_column\\_id, \"user\\_id\": example\\_student\\_id, \"content: example\\_content } ] } ```bash ``` Returns a [Progress](progress.md#progress) object. *** This documentation is generated directly from the Canvas LMS source code, available [on Gith...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "column_data[]": {
          "type": "array",
          "description": "Column content. Setting this to an empty string will delete the data object."
        }
      },
      "required": [
        "course_id",
        "column_data[]"
      ]
    }
  }
];

const handlers = {
  get_courses_course_id_custom_gradebook_columns: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/courses/:course_id/custom_gradebook_columns", args);
  },
  post_courses_course_id_custom_gradebook_columns: async (client, args) => {
    return genericHandler(client, "POST", "/api/v1/courses/:course_id/custom_gradebook_columns", args);
  },
  put_courses_course_id_custom_gradebook_columns_id: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/courses/:course_id/custom_gradebook_columns/:id", args);
  },
  delete_courses_course_id_custom_gradebook_columns_id: async (client, args) => {
    return genericHandler(client, "DELETE", "/api/v1/courses/:course_id/custom_gradebook_columns/:id", args);
  },
  post_courses_course_id_custom_gradebook_columns_reorder: async (client, args) => {
    return genericHandler(client, "POST", "/api/v1/courses/:course_id/custom_gradebook_columns/reorder", args);
  },
  get_courses_course_id_custom_gradebook_columns_id_data: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/courses/:course_id/custom_gradebook_columns/:id/data", args);
  },
  put_courses_course_id_custom_gradebook_columns_id_data_user_id: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/courses/:course_id/custom_gradebook_columns/:id/data/:user_id", args);
  },
  put_courses_course_id_custom_gradebook_column_data: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/courses/:course_id/custom_gradebook_column_data", args);
  }
};

module.exports = {
  definitions,
  handlers
};
