// Auto-generated MCP Tools for Canvas LMS API
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const { genericHandler } = require("./helper");

const definitions = [
  {
    "name": "get_discovery_pages",
    "description": "**Scope:** `url:GET|/api/v1/discovery_pages` Get the discovery page configuration for the domain root account. ```bash curl 'https:///api/v1/discovery_pages' \\ -H 'Authorization: Bearer ' ``` ```js { \"discovery_page\": { \"primary\": [ { \"authentication_provider_id\": 1, \"label\": \"Students\", \"icon\": \"google\" } ], \"secondary\": [ { \"authentication_provider_id\": 3, \"label\": \"Admins\" } ], \"active\": true } } ``` Returns a [DiscoveryPage](#discoverypage) object. [DiscoveryPagesApiController#upsert](htt...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      }
    }
  },
  {
    "name": "put_discovery_pages",
    "description": "**Scope:** `url:PUT|/api/v1/discovery_pages` Update or create the discovery page configuration for the domain root account. This is a full replacement - provide the complete configuration including primary, secondary, and active fields. Any fields omitted will be removed. ```bash curl -X PUT 'https:///api/v1/discovery_pages' \\ -H 'Authorization: Bearer ' \\ -H 'Content-Type: application/json' \\ -d '{ \"discovery_page\": { \"primary\": [ { \"authentication_provider_id\": 1, \"label\": \"Students\", \"icon...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "discovery_page[primary][][authentication_provider_id]": {
          "type": "number",
          "description": "The ID of an active authentication provider for this account."
        },
        "discovery_page[primary][][label]": {
          "type": "string",
          "description": "The display label for this authentication provider button."
        },
        "discovery_page[primary][][icon]": {
          "type": "string",
          "description": "Icon key for this authentication provider button."
        },
        "discovery_page[secondary][][authentication_provider_id]": {
          "type": "number",
          "description": "The ID of an active authentication provider for this account."
        },
        "discovery_page[secondary][][label]": {
          "type": "string",
          "description": "The display label for this authentication provider button."
        },
        "discovery_page[secondary][][icon]": {
          "type": "string",
          "description": "Icon key for this authentication provider button."
        },
        "discovery_page[active]": {
          "type": "boolean",
          "description": "Whether the discovery page is enabled. Defaults to false if not provided."
        }
      },
      "required": [
        "discovery_page[primary][][authentication_provider_id]",
        "discovery_page[primary][][label]",
        "discovery_page[secondary][][authentication_provider_id]",
        "discovery_page[secondary][][label]"
      ]
    }
  },
  {
    "name": "post_discovery_pages_token",
    "description": "**Scope:** `url:POST|/api/v1/discovery_pages/token` Returns a short-lived RS256-signed JWT containing the discovery page button link configuration, suitable for sending to the identity service preview iframe via postMessage. A discovery\\_page configuration must be provided in the request body. Omitting it returns a 400 Bad Request. ```bash curl -X POST 'https:///api/v1/discovery_pages/token' \\ -H 'Authorization: Bearer ' \\ -H 'Content-Type: application/json' \\ -d '{ \"discovery_page\": { \"prima...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "discovery_page[primary][][authentication_provider_id]": {
          "type": "number",
          "description": "The ID of an active authentication provider for this account."
        },
        "discovery_page[primary][][label]": {
          "type": "string",
          "description": "The display label for this authentication provider button."
        },
        "discovery_page[primary][][icon]": {
          "type": "string",
          "description": "Icon key for this authentication provider button."
        },
        "discovery_page[secondary][][authentication_provider_id]": {
          "type": "number",
          "description": "The ID of an active authentication provider for this account."
        },
        "discovery_page[secondary][][label]": {
          "type": "string",
          "description": "The display label for this authentication provider button."
        },
        "discovery_page[secondary][][icon]": {
          "type": "string",
          "description": "Icon key for this authentication provider button."
        }
      },
      "required": [
        "discovery_page[primary][][authentication_provider_id]"
      ]
    }
  }
];

const handlers = {
  get_discovery_pages: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/discovery_pages", args);
  },
  put_discovery_pages: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/discovery_pages", args);
  },
  post_discovery_pages_token: async (client, args) => {
    return genericHandler(client, "POST", "/api/v1/discovery_pages/token", args);
  }
};

module.exports = {
  definitions,
  handlers
};
