// Auto-generated MCP Tools for Canvas LMS API
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const { genericHandler } = require("./helper");

const definitions = [
  {
    "name": "post_accounts_account_id_grading_standards",
    "description": "**Scope:** `url:POST|/api/v1/accounts/:account_id/grading_standards`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        }
      },
      "required": [
        "account_id"
      ]
    }
  },
  {
    "name": "post_courses_course_id_grading_standards",
    "description": "**Scope:** `url:POST|/api/v1/courses/:course_id/grading_standards` Create a new grading standard ```bash curl https:///api/v1/courses//grading_standards \\ -X POST \\ -H 'Authorization: Bearer ' \\ -d 'title=New standard name' \\ -d 'points_based=false' \\ -d 'scaling_factor=1.0' \\ -d 'grading_scheme_entry[][name]=A' \\ -d 'grading_scheme_entry[][value]=94' \\ -d 'grading_scheme_entry[][name]=A-' \\ -d 'grading_scheme_entry[][value]=90' \\ -d 'grading_scheme_entry[][name]=B+' \\ -d 'grading_scheme_entr...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "title": {
          "type": "string",
          "description": "The title for the Grading Standard."
        },
        "points_based": {
          "type": "boolean",
          "description": "<p>Whether or not a grading scheme is points based.<br>Defaults to false.</p>"
        },
        "scaling_factor": {
          "type": "number",
          "description": "<p>The factor by which to scale a percentage into a points based scheme grade.<br>This is the maximum number of points possible in the grading scheme.<br>Defaults to 1. Not required for percentage based grading schemes.</p>"
        },
        "grading_scheme_entry[][name]": {
          "type": "string",
          "description": "<p>The name for an entry value within a GradingStandard that describes the range of the value<br>e.g. A-</p>"
        },
        "grading_scheme_entry[][value]": {
          "type": "number",
          "description": "<p>The value for the name of the entry within a GradingStandard.<br>The entry represents the lower bound of the range for the entry.<br>This range includes the value up to the next entry in the GradingStandard,<br>or 100 if there is no upper bound. The lowest value will have a lower bound range of 0.<br>e.g. 93</p>"
        }
      },
      "required": [
        "course_id",
        "title",
        "grading_scheme_entry[][name]",
        "grading_scheme_entry[][value]"
      ]
    }
  },
  {
    "name": "get_courses_course_id_grading_standards",
    "description": "**Scope:** `url:GET|/api/v1/courses/:course_id/grading_standards`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        }
      },
      "required": [
        "course_id"
      ]
    }
  },
  {
    "name": "get_accounts_account_id_grading_standards",
    "description": "**Scope:** `url:GET|/api/v1/accounts/:account_id/grading_standards` Returns the paginated list of grading standards for the given context that are visible to the user. ```bash curl https:///api/v1/courses/1/grading_standards \\ -H 'Authorization: Bearer ' ``` Returns a list of [GradingStandard](#gradingstandard) objects. [GradingStandardsApiController#context\\_show](https://github.com/instructure/canvas-lms/blob/master/app/controllers/grading_standards_api_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        }
      },
      "required": [
        "account_id"
      ]
    }
  },
  {
    "name": "get_courses_course_id_grading_standards_grading_standard_id",
    "description": "**Scope:** `url:GET|/api/v1/courses/:course_id/grading_standards/:grading_standard_id`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "grading_standard_id": {
          "type": "string",
          "description": "Path parameter: grading_standard_id"
        }
      },
      "required": [
        "course_id",
        "grading_standard_id"
      ]
    }
  },
  {
    "name": "get_accounts_account_id_grading_standards_grading_standard_id",
    "description": "**Scope:** `url:GET|/api/v1/accounts/:account_id/grading_standards/:grading_standard_id` Returns a grading standard for the given context that is visible to the user. ```bash curl https:///api/v1/courses/1/grading_standards/5 \\ -H 'Authorization: Bearer ' ``` Returns a [GradingStandard](#gradingstandard) object. [GradingStandardsApiController#update](https://github.com/instructure/canvas-lms/blob/master/app/controllers/grading_standards_api_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        },
        "grading_standard_id": {
          "type": "string",
          "description": "Path parameter: grading_standard_id"
        }
      },
      "required": [
        "account_id",
        "grading_standard_id"
      ]
    }
  },
  {
    "name": "put_courses_course_id_grading_standards_grading_standard_id",
    "description": "**Scope:** `url:PUT|/api/v1/courses/:course_id/grading_standards/:grading_standard_id`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "grading_standard_id": {
          "type": "string",
          "description": "Path parameter: grading_standard_id"
        }
      },
      "required": [
        "course_id",
        "grading_standard_id"
      ]
    }
  },
  {
    "name": "put_accounts_account_id_grading_standards_grading_standard_id",
    "description": "**Scope:** `url:PUT|/api/v1/accounts/:account_id/grading_standards/:grading_standard_id` Updates the grading standard with the given id If the grading standard has been used for grading, only the title can be updated. The data, points\\_based, and scaling\\_factor cannot be modified once the grading standard has been used to grade assignments. ```bash curl https:///api/v1/courses/1/grading_standards/5 \\ -X PUT \\ -H 'Authorization: Bearer ' \\ -d 'title=Updated+Grading+Standard' -d 'points_based=...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        },
        "grading_standard_id": {
          "type": "string",
          "description": "Path parameter: grading_standard_id"
        },
        "title": {
          "type": "string",
          "description": "The title for the Grading Standard"
        },
        "points_based": {
          "type": "boolean",
          "description": "<p>Whether or not a grading scheme is points based.<br>Defaults to false.</p>"
        },
        "scaling_factor": {
          "type": "number",
          "description": "<p>The factor by which to scale a percentage into a points based scheme grade.<br>This is the maximum number of points possible in the grading scheme.<br>Defaults to 1. Not required for percentage based grading schemes.</p>"
        },
        "grading_scheme_entry[][name]": {
          "type": "string",
          "description": "<p>The name for an entry value within a GradingStandard that describes the range of the value<br>e.g. A-</p>"
        },
        "grading_scheme_entry[][value]": {
          "type": "number",
          "description": "<p>The value for the name of the entry within a GradingStandard.<br>The entry represents the lower bound of the range for the entry.<br>This range includes the value up to the next entry in the GradingStandard,<br>or 100 if there is no upper bound. The lowest value will have a lower bound range of 0.<br>e.g. 93</p>"
        }
      },
      "required": [
        "account_id",
        "grading_standard_id",
        "grading_scheme_entry[][value]"
      ]
    }
  },
  {
    "name": "delete_courses_course_id_grading_standards_grading_standard_id",
    "description": "**Scope:** `url:DELETE|/api/v1/courses/:course_id/grading_standards/:grading_standard_id`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "grading_standard_id": {
          "type": "string",
          "description": "Path parameter: grading_standard_id"
        }
      },
      "required": [
        "course_id",
        "grading_standard_id"
      ]
    }
  },
  {
    "name": "delete_accounts_account_id_grading_standards_grading_standard_id",
    "description": "**Scope:** `url:DELETE|/api/v1/accounts/:account_id/grading_standards/:grading_standard_id` Deletes the grading standard with the given id ```bash curl https:///api/v1/courses/1/grading_standards/5 \\ -X DELETE \\ -H 'Authorization: Bearer ' ``` Returns a [GradingStandard](#gradingstandard) object. *** This documentation is generated directly from the Canvas LMS source code, available [on Github](https://github.com/instructure/canvas-lms). --- This documentation is published with GitBook. GitBo...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        },
        "grading_standard_id": {
          "type": "string",
          "description": "Path parameter: grading_standard_id"
        }
      },
      "required": [
        "account_id",
        "grading_standard_id"
      ]
    }
  }
];

const handlers = {
  post_accounts_account_id_grading_standards: async (client, args) => {
    return genericHandler(client, "POST", "/api/v1/accounts/:account_id/grading_standards", args);
  },
  post_courses_course_id_grading_standards: async (client, args) => {
    return genericHandler(client, "POST", "/api/v1/courses/:course_id/grading_standards", args);
  },
  get_courses_course_id_grading_standards: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/courses/:course_id/grading_standards", args);
  },
  get_accounts_account_id_grading_standards: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/accounts/:account_id/grading_standards", args);
  },
  get_courses_course_id_grading_standards_grading_standard_id: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/courses/:course_id/grading_standards/:grading_standard_id", args);
  },
  get_accounts_account_id_grading_standards_grading_standard_id: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/accounts/:account_id/grading_standards/:grading_standard_id", args);
  },
  put_courses_course_id_grading_standards_grading_standard_id: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/courses/:course_id/grading_standards/:grading_standard_id", args);
  },
  put_accounts_account_id_grading_standards_grading_standard_id: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/accounts/:account_id/grading_standards/:grading_standard_id", args);
  },
  delete_courses_course_id_grading_standards_grading_standard_id: async (client, args) => {
    return genericHandler(client, "DELETE", "/api/v1/courses/:course_id/grading_standards/:grading_standard_id", args);
  },
  delete_accounts_account_id_grading_standards_grading_standard_id: async (client, args) => {
    return genericHandler(client, "DELETE", "/api/v1/accounts/:account_id/grading_standards/:grading_standard_id", args);
  }
};

module.exports = {
  definitions,
  handlers
};
