// Auto-generated MCP Tools for Canvas LMS API
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const { genericHandler } = require("./helper");

const definitions = [
  {
    "name": "get_accounts_account_id_group_categories",
    "description": "**Scope:** `url:GET|/api/v1/accounts/:account_id/group_categories`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        }
      },
      "required": [
        "account_id"
      ]
    }
  },
  {
    "name": "get_courses_course_id_group_categories",
    "description": "**Scope:** `url:GET|/api/v1/courses/:course_id/group_categories` Returns a paginated list of group categories in a context. The list returned depends on the permissions of the current user and the specified collaboration state. ```bash curl https:///api/v1/accounts//group_categories \\ -H 'Authorization: Bearer ' \\ -d 'collaboration_state=all' ``` Returns a list of [GroupCategory](#groupcategory) objects. [GroupCategoriesController#show](https://github.com/instructure/canvas-lms/blob/master/ap...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "collaboration_state": {
          "type": "string",
          "description": "<p>Filter group categories by their collaboration state:<br>- \"all\": Return both collaborative and non-collaborative group categories<br>- \"collaborative\": Return only collaborative group categories (default)<br>- \"non\\_collaborative\": Return only non-collaborative group categories</p>"
        }
      },
      "required": [
        "course_id"
      ]
    }
  },
  {
    "name": "get_group_categories_group_category_id",
    "description": "**Scope:** `url:GET|/api/v1/group_categories/:group_category_id` Returns the data for a single group category, or a 401 if the caller doesn't have the rights to see it. ```bash curl https:///api/v1/group_categories/ \\ -H 'Authorization: Bearer ' ``` Returns a [GroupCategory](#groupcategory) object. [GroupCategoriesController#create](https://github.com/instructure/canvas-lms/blob/master/app/controllers/group_categories_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_category_id": {
          "type": "string",
          "description": "Path parameter: group_category_id"
        }
      },
      "required": [
        "group_category_id"
      ]
    }
  },
  {
    "name": "post_accounts_account_id_group_categories",
    "description": "**Scope:** `url:POST|/api/v1/accounts/:account_id/group_categories`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        }
      },
      "required": [
        "account_id"
      ]
    }
  },
  {
    "name": "post_courses_course_id_group_categories",
    "description": "**Scope:** `url:POST|/api/v1/courses/:course_id/group_categories` Create a new group category ```bash curl htps:///api/v1/courses//group_categories \\ -F 'name=Project Groups' \\ -H 'Authorization: Bearer ' ``` Returns a [GroupCategory](#groupcategory) object. [GroupCategoriesController#bulk\\_manage\\_differentiation\\_tag](https://github.com/instructure/canvas-lms/blob/master/app/controllers/group_categories_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "name": {
          "type": "string",
          "description": "Name of the group category"
        },
        "non_collaborative": {
          "type": "boolean",
          "description": "<p>Can only be set by users with the Differentiation Tag - Add permission<br>If set to true, groups in this category will be only be visible to users with the<br>Differentiation Tag - Manage permission.</p>"
        },
        "self_signup": {
          "type": "string",
          "description": "<p>Allow students to sign up for a group themselves (Course Only).<br>valid values are:<br>\"enabled\":: allows students to self sign up for any group in course<br>\"restricted\":: allows students to self sign up only for groups in the<br>same section null disallows self sign up Allowed values: <code>enabled</code>, <code>restricted</code></p>"
        },
        "auto_leader": {
          "type": "string",
          "description": "<p>Assigns group leaders automatically when generating and allocating students to groups<br>Valid values are:<br>\"first\":: the first student to be allocated to a group is the leader<br>\"random\":: a random student from all members is chosen as the leader Allowed values: <code>first</code>, <code>random</code></p>"
        },
        "group_limit": {
          "type": "number",
          "description": "<p>Limit the maximum number of users in each group (Course Only). Requires<br>self signup.</p>"
        },
        "sis_group_category_id": {
          "type": "string",
          "description": "The unique SIS identifier."
        },
        "create_group_count": {
          "type": "number",
          "description": "Create this number of groups (Course Only)."
        },
        "split_group_count": {
          "type": "string",
          "description": "<p>(Deprecated)<br>Create this number of groups, and evenly distribute students<br>among them. not allowed with \"enable\\_self\\_signup\". because<br>the group assignment happens synchronously, it's recommended<br>that you instead use the assign\\_unassigned\\_members endpoint.<br>(Course Only)</p>"
        }
      },
      "required": [
        "course_id",
        "name"
      ]
    }
  },
  {
    "name": "post_courses_course_id_group_categories_bulk_manage_differentiation_tag",
    "description": "**Scope:** `url:POST|/api/v1/courses/:course_id/group_categories/bulk_manage_differentiation_tag` This API is only meant for Groups and GroupCategories where non\\_collaborative is true. Perform bulk operations on groups within a group category, or create a new group category along with the groups in one transaction. If creation of the GroupCategory or any Group fails, the entire operation will be rolled back. ```bash curl https:///api/v1/courses/:course_id/group_categories/bulk_manage_differe...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "operations": {
          "type": "string",
          "description": "<p>A hash containing arrays of create/update/delete operations:<br>{<br>\"create\": \\[<br>{ \"name\": \"New Group A\" },<br>{ \"name\": \"New Group B\" }<br>],<br>\"update\": \\[<br>{ \"id\": 123, \"name\": \"Updated Group Name A\" },<br>{ \"id\": 456, \"name\": \"Updated Group Name B\" }<br>],<br>\"delete\": \\[<br>{ \"id\": 789 },<br>{ \"id\": 101 }<br>]<br>}</p>"
        },
        "group_category": {
          "type": "string",
          "description": "<p>Attributes for the GroupCategory. May include:<br>- id \\[Optional, Integer]: The ID of an existing GroupCategory.<br>- name \\[Optional, String]: A new name for the GroupCategory. If provided with an ID, the category name will be updated.</p>"
        }
      },
      "required": [
        "course_id",
        "operations",
        "group_category"
      ]
    }
  },
  {
    "name": "post_courses_course_id_group_categories_import_tags",
    "description": "**Scope:** `url:POST|/api/v1/courses/:course_id/group_categories/import_tags` Create Differentiation Tags through a CSV import For more information on the format that's expected here, please see the \"Differentiation Tag CSV\" section in the API docs. ```js { \"completion\": 0, \"context_id\": 20, \"context_type\": \"Course\", \"created_at\": \"2013-07-05T10:57:48-06:00\", \"id\": 2, \"message\": null, \"tag\": \"course_tag_import\", \"updated_at\": \"2013-07-05T10:57:48-06:00\", \"user_id\": null, \"workflow_state\": \"ru...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "attachment": {
          "type": "string",
          "description": "<p>There are two ways to post differentiation tag import data - either via a<br>multipart/form-data form-field-style attachment, or via a non-multipart<br>raw post request.<br>'attachment' is required for multipart/form-data style posts. Assumed to<br>be tag data from a file upload form field named 'attachment'.<br>Examples:<br>curl -F attachment=@\\<filename> -H \"Authorization: Bearer \\<token>\" \\<br> 'https\\://\\<canvas>/api/v1/group\\_categories/import\\_tags'<br>If you decide to do a raw post, you can skip the 'attachment' argument,<br>but you will then be required to provide a suitable Content-Type header.<br>You are encouraged to also provide the 'extension' argument.<br>Examples:<br>curl -H 'Content-Type: text/csv' --data-binary @\\<filename>.csv \\<br> -H \"Authorization: Bearer \\<token>\" \\<br> 'https\\://\\<canvas>/api/v1/group\\_categories\\_tags'</p>"
        }
      },
      "required": [
        "course_id"
      ]
    }
  },
  {
    "name": "post_group_categories_group_category_id_import",
    "description": "**Scope:** `url:POST|/api/v1/group_categories/:group_category_id/import` Create Groups in a Group Category through a CSV import For more information on the format that's expected here, please see the \"Group Category CSV\" section in the API docs. ```js { \"completion\": 0, \"context_id\": 20, \"context_type\": \"GroupCategory\", \"created_at\": \"2013-07-05T10:57:48-06:00\", \"id\": 2, \"message\": null, \"tag\": \"course_group_import\", \"updated_at\": \"2013-07-05T10:57:48-06:00\", \"user_id\": null, \"workflow_state\"...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_category_id": {
          "type": "string",
          "description": "Path parameter: group_category_id"
        },
        "attachment": {
          "type": "string",
          "description": "<p>There are two ways to post group category import data - either via a<br>multipart/form-data form-field-style attachment, or via a non-multipart<br>raw post request.<br>'attachment' is required for multipart/form-data style posts. Assumed to<br>be outcome data from a file upload form field named 'attachment'.<br>Examples:<br>curl -F attachment=@\\<filename> -H \"Authorization: Bearer \\<token>\" \\<br> 'https\\://\\<canvas>/api/v1/group\\_categories/\\<category\\_id>/import'<br>If you decide to do a raw post, you can skip the 'attachment' argument,<br>but you will then be required to provide a suitable Content-Type header.<br>You are encouraged to also provide the 'extension' argument.<br>Examples:<br>curl -H 'Content-Type: text/csv' --data-binary @\\<filename>.csv \\<br> -H \"Authorization: Bearer \\<token>\" \\<br> 'https\\://\\<canvas>/api/v1/group\\_categories/\\<category\\_id>/import'</p>"
        }
      },
      "required": [
        "group_category_id"
      ]
    }
  },
  {
    "name": "put_group_categories_group_category_id",
    "description": "**Scope:** `url:PUT|/api/v1/group_categories/:group_category_id` Modifies an existing group category. ```bash curl https:///api/v1/group_categories/ \\ -X PUT \\ -F 'name=Project Groups' \\ -H 'Authorization: Bearer ' ``` Returns a [GroupCategory](#groupcategory) object. [GroupCategoriesController#destroy](https://github.com/instructure/canvas-lms/blob/master/app/controllers/group_categories_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_category_id": {
          "type": "string",
          "description": "Path parameter: group_category_id"
        },
        "name": {
          "type": "string",
          "description": "Name of the group category"
        },
        "self_signup": {
          "type": "string",
          "description": "<p>Allow students to sign up for a group themselves (Course Only).<br>Valid values are:<br>\"enabled\":: allows students to self sign up for any group in course<br>\"restricted\":: allows students to self sign up only for groups in the<br>same section null disallows self sign up Allowed values: <code>enabled</code>, <code>restricted</code></p>"
        },
        "auto_leader": {
          "type": "string",
          "description": "<p>Assigns group leaders automatically when generating and allocating students to groups<br>Valid values are:<br>\"first\":: the first student to be allocated to a group is the leader<br>\"random\":: a random student from all members is chosen as the leader Allowed values: <code>first</code>, <code>random</code></p>"
        },
        "group_limit": {
          "type": "number",
          "description": "<p>Limit the maximum number of users in each group (Course Only). Requires<br>self signup.</p>"
        },
        "sis_group_category_id": {
          "type": "string",
          "description": "The unique SIS identifier."
        },
        "create_group_count": {
          "type": "number",
          "description": "Create this number of groups (Course Only)."
        },
        "split_group_count": {
          "type": "string",
          "description": "<p>(Deprecated)<br>Create this number of groups, and evenly distribute students<br>among them. not allowed with \"enable\\_self\\_signup\". because<br>the group assignment happens synchronously, it's recommended<br>that you instead use the assign\\_unassigned\\_members endpoint.<br>(Course Only)</p>"
        }
      },
      "required": [
        "group_category_id"
      ]
    }
  },
  {
    "name": "delete_group_categories_group_category_id",
    "description": "**Scope:** `url:DELETE|/api/v1/group_categories/:group_category_id` Deletes a group category and all groups under it. Protected group categories can not be deleted, i.e. \"communities\" and \"student\\_organized\". ```bash curl https:///api/v1/group_categories/ \\ -X DELETE \\ -H 'Authorization: Bearer ' ``` [GroupCategoriesController#groups](https://github.com/instructure/canvas-lms/blob/master/app/controllers/group_categories_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_category_id": {
          "type": "string",
          "description": "Path parameter: group_category_id"
        }
      },
      "required": [
        "group_category_id"
      ]
    }
  },
  {
    "name": "get_group_categories_group_category_id_groups",
    "description": "**Scope:** `url:GET|/api/v1/group_categories/:group_category_id/groups` Returns a paginated list of groups in a group category ```bash curl https:///api/v1/group_categories//groups \\ -H 'Authorization: Bearer ' ``` Returns a list of [Group](groups.md#group) objects. [GroupCategoriesController#export](https://github.com/instructure/canvas-lms/blob/master/app/controllers/group_categories_controller.rb) {% hint style=\"warning\" %} BETA: This API endpoint is not finalized, and there could be break...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_category_id": {
          "type": "string",
          "description": "Path parameter: group_category_id"
        }
      },
      "required": [
        "group_category_id"
      ]
    }
  },
  {
    "name": "get_group_categories_group_category_id_export",
    "description": "**Scope:** `url:GET|/api/v1/group_categories/:group_category_id/export` Returns a csv file of users in format ready to import. ```bash curl https:///api/v1/group_categories//export \\ -H 'Authorization: Bearer ' ``` [GroupCategoriesController#export\\_tags](https://github.com/instructure/canvas-lms/blob/master/app/controllers/group_categories_controller.rb) {% hint style=\"warning\" %} BETA: This API endpoint is not finalized, and there could be breaking changes before its final release. {% endhi...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_category_id": {
          "type": "string",
          "description": "Path parameter: group_category_id"
        }
      },
      "required": [
        "group_category_id"
      ]
    }
  },
  {
    "name": "get_courses_course_id_group_categories_export_tags",
    "description": "**Scope:** `url:GET|/api/v1/courses/:course_id/group_categories/export_tags` Returns a csv file of users in format ready to import. ```bash curl https:///api/v1/group_categories/export_tags \\ -H 'Authorization: Bearer ' ``` [GroupCategoriesController#users](https://github.com/instructure/canvas-lms/blob/master/app/controllers/group_categories_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        }
      },
      "required": [
        "course_id"
      ]
    }
  },
  {
    "name": "get_group_categories_group_category_id_users",
    "description": "**Scope:** `url:GET|/api/v1/group_categories/:group_category_id/users` Returns a paginated list of users in the group category. ```bash curl https:///api/v1/group_categories/1/users \\ -H 'Authorization: Bearer ' ``` Returns a list of [User](users.md#user) objects. [GroupCategoriesController#assign\\_unassigned\\_members](https://github.com/instructure/canvas-lms/blob/master/app/controllers/group_categories_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_category_id": {
          "type": "string",
          "description": "Path parameter: group_category_id"
        },
        "search_term": {
          "type": "string",
          "description": "<p>The partial name or full ID of the users to match and return in the results<br>list. Must be at least 3 characters.</p>"
        },
        "unassigned": {
          "type": "boolean",
          "description": "<p>Set this value to true if you wish only to search unassigned users in the<br>group category.</p>"
        }
      },
      "required": [
        "group_category_id"
      ]
    }
  },
  {
    "name": "post_group_categories_group_category_id_assign_unassigned_members",
    "description": "**Scope:** `url:POST|/api/v1/group_categories/:group_category_id/assign_unassigned_members` Assign all unassigned members as evenly as possible among the existing student groups. ```bash curl https:///api/v1/group_categories/1/assign_unassigned_members \\ -H 'Authorization: Bearer ' ``` ```js { \"completion\": 0, \"context_id\": 20, \"context_type\": \"GroupCategory\", \"created_at\": \"2013-07-05T10:57:48-06:00\", \"id\": 2, \"message\": null, \"tag\": \"assign_unassigned_members\", \"updated_at\": \"2013-07-05T10:...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_category_id": {
          "type": "string",
          "description": "Path parameter: group_category_id"
        },
        "sync": {
          "type": "boolean",
          "description": "<p>The assigning is done asynchronously by default. If you would like to<br>override this and have the assigning done synchronously, set this value<br>to true.</p>"
        }
      },
      "required": [
        "group_category_id"
      ]
    }
  }
];

const handlers = {
  get_accounts_account_id_group_categories: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/accounts/:account_id/group_categories", args);
  },
  get_courses_course_id_group_categories: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/courses/:course_id/group_categories", args);
  },
  get_group_categories_group_category_id: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/group_categories/:group_category_id", args);
  },
  post_accounts_account_id_group_categories: async (client, args) => {
    return genericHandler(client, "POST", "/api/v1/accounts/:account_id/group_categories", args);
  },
  post_courses_course_id_group_categories: async (client, args) => {
    return genericHandler(client, "POST", "/api/v1/courses/:course_id/group_categories", args);
  },
  post_courses_course_id_group_categories_bulk_manage_differentiation_tag: async (client, args) => {
    return genericHandler(client, "POST", "/api/v1/courses/:course_id/group_categories/bulk_manage_differentiation_tag", args);
  },
  post_courses_course_id_group_categories_import_tags: async (client, args) => {
    return genericHandler(client, "POST", "/api/v1/courses/:course_id/group_categories/import_tags", args);
  },
  post_group_categories_group_category_id_import: async (client, args) => {
    return genericHandler(client, "POST", "/api/v1/group_categories/:group_category_id/import", args);
  },
  put_group_categories_group_category_id: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/group_categories/:group_category_id", args);
  },
  delete_group_categories_group_category_id: async (client, args) => {
    return genericHandler(client, "DELETE", "/api/v1/group_categories/:group_category_id", args);
  },
  get_group_categories_group_category_id_groups: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/group_categories/:group_category_id/groups", args);
  },
  get_group_categories_group_category_id_export: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/group_categories/:group_category_id/export", args);
  },
  get_courses_course_id_group_categories_export_tags: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/courses/:course_id/group_categories/export_tags", args);
  },
  get_group_categories_group_category_id_users: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/group_categories/:group_category_id/users", args);
  },
  post_group_categories_group_category_id_assign_unassigned_members: async (client, args) => {
    return genericHandler(client, "POST", "/api/v1/group_categories/:group_category_id/assign_unassigned_members", args);
  }
};

module.exports = {
  definitions,
  handlers
};
