// Auto-generated MCP Tools for Canvas LMS API
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const { genericHandler } = require("./helper");

const definitions = [
  {
    "name": "post_inst_access_tokens",
    "description": "**Scope:** `url:POST|/api/v1/inst_access_tokens` Create a unique, encrypted InstAccess token. Generates a different InstAccess token each time it's called, each one expires after a short window (1 hour). ```bash curl 'https:///api/v1/inst_access_tokens' \\ -X POST \\ -H \"Accept: application/json\" \\ -H 'Authorization: Bearer ' ``` Returns an [InstAccessToken](#instaccesstoken) object. *** This documentation is generated directly from the Canvas LMS source code, available [on Github](https://gith...",
    "inputSchema": {
      "type": "object",
      "properties": {}
    }
  }
];

const handlers = {
  post_inst_access_tokens: async (client, args) => {
    return genericHandler(client, "POST", "/api/v1/inst_access_tokens", args);
  }
};

module.exports = {
  definitions,
  handlers
};
