// Auto-generated MCP Tools for Canvas LMS API
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const { genericHandler } = require("./helper");

const definitions = [
  {
    "name": "get_courses_course_id_modules_context_module_id_date_details",
    "description": "**Scope:** `url:GET|/api/v1/courses/:course_id/modules/:context_module_id/date_details`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "context_module_id": {
          "type": "string",
          "description": "Path parameter: context_module_id"
        }
      },
      "required": [
        "course_id",
        "context_module_id"
      ]
    }
  },
  {
    "name": "get_courses_course_id_assignments_assignment_id_date_details",
    "description": "**Scope:** `url:GET|/api/v1/courses/:course_id/assignments/:assignment_id/date_details`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "assignment_id": {
          "type": "string",
          "description": "Path parameter: assignment_id"
        }
      },
      "required": [
        "course_id",
        "assignment_id"
      ]
    }
  },
  {
    "name": "get_courses_course_id_quizzes_quiz_id_date_details",
    "description": "**Scope:** `url:GET|/api/v1/courses/:course_id/quizzes/:quiz_id/date_details`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "quiz_id": {
          "type": "string",
          "description": "Path parameter: quiz_id"
        }
      },
      "required": [
        "course_id",
        "quiz_id"
      ]
    }
  },
  {
    "name": "get_courses_course_id_discussion_topics_discussion_topic_id_date_details",
    "description": "**Scope:** `url:GET|/api/v1/courses/:course_id/discussion_topics/:discussion_topic_id/date_details`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "discussion_topic_id": {
          "type": "string",
          "description": "Path parameter: discussion_topic_id"
        }
      },
      "required": [
        "course_id",
        "discussion_topic_id"
      ]
    }
  },
  {
    "name": "get_courses_course_id_pages_url_or_id_date_details",
    "description": "**Scope:** `url:GET|/api/v1/courses/:course_id/pages/:url_or_id/date_details`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "url_or_id": {
          "type": "string",
          "description": "Path parameter: url_or_id"
        }
      },
      "required": [
        "course_id",
        "url_or_id"
      ]
    }
  },
  {
    "name": "get_courses_course_id_files_attachment_id_date_details",
    "description": "**Scope:** `url:GET|/api/v1/courses/:course_id/files/:attachment_id/date_details` Get a learning object's date-related information, including due date, availability dates, override status, and a paginated list of all assignment overrides for the item. Returns a [LearningObjectDates](#learningobjectdates) object. [LearningObjectDatesController#update](https://github.com/instructure/canvas-lms/blob/master/app/controllers/learning_object_dates_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "attachment_id": {
          "type": "string",
          "description": "Path parameter: attachment_id"
        },
        "include[]": {
          "type": "array",
          "description": "<p>Array of strings indicating what additional data to include in the response.<br>Valid values:<br>- \"peer\\_review\": includes peer review sub assignment information and overrides in the response.<br>If a peer review sub assignment exists, it is returned regardless of the Peer Review<br>Allocation and Grading feature state. If no peer review sub assignment exists,<br>the feature must be enabled to receive a null value; otherwise the key is omitted.<br>- \"child\\_peer\\_review\\_override\\_dates\": each assignment override will include a peer\\_review\\_dates<br>field containing the matched peer review override data (id, due\\_at, unlock\\_at, lock\\_at)<br>for that override. The field will be present as null if no matching peer review override exists.</p>"
        },
        "exclude[]": {
          "type": "array",
          "description": "<p>Array of strings indicating what data to exclude from the response.<br>Valid values:<br>- \"peer\\_review\\_overrides\": when include\\[]=peer\\_review is also specified, the<br>peer\\_review\\_sub\\_assignment object will not include the overrides array, reducing the<br>response payload size. This is useful when using include\\[]=child\\_peer\\_review\\_override\\_dates<br>since the peer review override data is already embedded in the parent assignment overrides.<br>- \"child\\_override\\_due\\_dates\": prevents the sub\\_assignment\\_due\\_dates field from being included<br>in assignment override responses, even when discussion checkpoints are enabled. This reduces<br>response payload size when checkpoint due date information is not needed.</p>"
        }
      },
      "required": [
        "course_id",
        "attachment_id"
      ]
    }
  },
  {
    "name": "put_courses_course_id_assignments_assignment_id_date_details",
    "description": "**Scope:** `url:PUT|/api/v1/courses/:course_id/assignments/:assignment_id/date_details`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "assignment_id": {
          "type": "string",
          "description": "Path parameter: assignment_id"
        }
      },
      "required": [
        "course_id",
        "assignment_id"
      ]
    }
  },
  {
    "name": "put_courses_course_id_quizzes_quiz_id_date_details",
    "description": "**Scope:** `url:PUT|/api/v1/courses/:course_id/quizzes/:quiz_id/date_details`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "quiz_id": {
          "type": "string",
          "description": "Path parameter: quiz_id"
        }
      },
      "required": [
        "course_id",
        "quiz_id"
      ]
    }
  },
  {
    "name": "put_courses_course_id_discussion_topics_discussion_topic_id_date_details",
    "description": "**Scope:** `url:PUT|/api/v1/courses/:course_id/discussion_topics/:discussion_topic_id/date_details`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "discussion_topic_id": {
          "type": "string",
          "description": "Path parameter: discussion_topic_id"
        }
      },
      "required": [
        "course_id",
        "discussion_topic_id"
      ]
    }
  },
  {
    "name": "put_courses_course_id_pages_url_or_id_date_details",
    "description": "**Scope:** `url:PUT|/api/v1/courses/:course_id/pages/:url_or_id/date_details`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "url_or_id": {
          "type": "string",
          "description": "Path parameter: url_or_id"
        }
      },
      "required": [
        "course_id",
        "url_or_id"
      ]
    }
  },
  {
    "name": "put_courses_course_id_files_attachment_id_date_details",
    "description": "**Scope:** `url:PUT|/api/v1/courses/:course_id/files/:attachment_id/date_details` Updates date-related information for learning objects, including due date, availability dates, override status, and assignment overrides. Returns 204 No Content response code if successful. ```bash curl https:///api/v1/courses/:course_id/assignments/:assignment_id/date_details \\ -X PUT \\ -H 'Authorization: Bearer ' \\ -H 'Content-Type: application/json' \\ -d '{ \"due_at\": \"2012-07-01T23:59:00-06:00\", \"unlock_at\": ...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "attachment_id": {
          "type": "string",
          "description": "Path parameter: attachment_id"
        },
        "due_at": {
          "type": "string",
          "description": "The learning object's due date. Not applicable for ungraded discussions, pages, and files."
        },
        "unlock_at": {
          "type": "string",
          "description": "The learning object's unlock date. Must be before the due date if there is one."
        },
        "lock_at": {
          "type": "string",
          "description": "The learning object's lock date. Must be after the due date if there is one."
        },
        "only_visible_to_overrides": {
          "type": "boolean",
          "description": "Whether the learning object is only assigned to students who are targeted by an override."
        },
        "assignment_overrides[]": {
          "type": "array",
          "description": "<p>List of overrides to apply to the learning object. Overrides that already exist should include<br>an ID and will be updated if needed. New overrides will be created for overrides in the list<br>without an ID. Overrides not included in the list will be deleted. Providing an empty list<br>will delete all of the object's overrides. Keys for each override object can include: 'id',<br>'title', 'due\\_at', 'unlock\\_at', 'lock\\_at', 'student\\_ids', and 'course\\_section\\_id', 'course\\_id',<br>'noop\\_id', and 'unassign\\_item'.</p>"
        },
        "peer_review": {
          "type": "string",
          "description": "<p>Optional peer review configuration for assignments with peer reviews enabled.<br>Requires the peer\\_review\\_allocation\\_and\\_grading feature flag.<br>Keys can include: 'due\\_at', 'unlock\\_at', 'lock\\_at', 'peer\\_review\\_overrides'</p>"
        },
        "peer_review[due_at]": {
          "type": "string",
          "description": "The peer review due date"
        },
        "peer_review[unlock_at]": {
          "type": "string",
          "description": "The peer review unlock date (when peer reviews become available)"
        },
        "peer_review[lock_at]": {
          "type": "string",
          "description": "The peer review lock date (when peer reviews are no longer available)"
        },
        "peer_review[peer_review_overrides][]": {
          "type": "array",
          "description": "<p>List of peer review overrides. Each override can include: 'id', 'due\\_at',<br>'unlock\\_at', 'lock\\_at', 'student\\_ids', 'course\\_section\\_id', 'course\\_id',<br>'group\\_id', 'unassign\\_item'</p>"
        }
      },
      "required": [
        "course_id",
        "attachment_id"
      ]
    }
  }
];

const handlers = {
  get_courses_course_id_modules_context_module_id_date_details: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/courses/:course_id/modules/:context_module_id/date_details", args);
  },
  get_courses_course_id_assignments_assignment_id_date_details: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/courses/:course_id/assignments/:assignment_id/date_details", args);
  },
  get_courses_course_id_quizzes_quiz_id_date_details: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/courses/:course_id/quizzes/:quiz_id/date_details", args);
  },
  get_courses_course_id_discussion_topics_discussion_topic_id_date_details: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/courses/:course_id/discussion_topics/:discussion_topic_id/date_details", args);
  },
  get_courses_course_id_pages_url_or_id_date_details: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/courses/:course_id/pages/:url_or_id/date_details", args);
  },
  get_courses_course_id_files_attachment_id_date_details: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/courses/:course_id/files/:attachment_id/date_details", args);
  },
  put_courses_course_id_assignments_assignment_id_date_details: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/courses/:course_id/assignments/:assignment_id/date_details", args);
  },
  put_courses_course_id_quizzes_quiz_id_date_details: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/courses/:course_id/quizzes/:quiz_id/date_details", args);
  },
  put_courses_course_id_discussion_topics_discussion_topic_id_date_details: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/courses/:course_id/discussion_topics/:discussion_topic_id/date_details", args);
  },
  put_courses_course_id_pages_url_or_id_date_details: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/courses/:course_id/pages/:url_or_id/date_details", args);
  },
  put_courses_course_id_files_attachment_id_date_details: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/courses/:course_id/files/:attachment_id/date_details", args);
  }
};

module.exports = {
  definitions,
  handlers
};
