// Auto-generated MCP Tools for Canvas LMS API
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const { genericHandler } = require("./helper");

const definitions = [
  {
    "name": "get_media_objects_media_object_id_media_tracks",
    "description": "**Scope:** `url:GET|/api/v1/media_objects/:media_object_id/media_tracks`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "media_object_id": {
          "type": "string",
          "description": "Path parameter: media_object_id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "media_object_id"
      ]
    }
  },
  {
    "name": "get_media_attachments_attachment_id_media_tracks",
    "description": "**Scope:** `url:GET|/api/v1/media_attachments/:attachment_id/media_tracks` List the media tracks associated with a media object or attachment ```bash curl https:///api/v1/media_objects//media_tracks?include[]=content -H 'Authorization: Bearer ' ``` ```bash curl https:///api/v1/media_attachments//media_tracks?include[]=content -H 'Authorization: Bearer ' ``` Returns a list of [MediaTrack](#mediatrack) objects. [MediaTracksController#update](https://github.com/instructure/canvas-lms/blob/master...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "attachment_id": {
          "type": "string",
          "description": "Path parameter: attachment_id"
        },
        "include[]": {
          "type": "string",
          "description": "<p>By default, index returns id, locale, kind, media\\_object\\_id, and user\\_id for each of the<br>result MediaTracks. Use include\\[] to<br>add additional fields. For example include\\[]=content Allowed values: <code>content</code>, <code>webvtt\\_content</code>, <code>updated\\_at</code>, <code>created\\_at</code></p>"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "attachment_id"
      ]
    }
  },
  {
    "name": "put_media_objects_media_object_id_media_tracks",
    "description": "**Scope:** `url:PUT|/api/v1/media_objects/:media_object_id/media_tracks`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "media_object_id": {
          "type": "string",
          "description": "Path parameter: media_object_id"
        }
      },
      "required": [
        "media_object_id"
      ]
    }
  },
  {
    "name": "put_media_attachments_attachment_id_media_tracks",
    "description": "**Scope:** `url:PUT|/api/v1/media_attachments/:attachment_id/media_tracks` Replace the media tracks associated with a media object or attachment with the array of tracks provided in the body. Update will delete any existing tracks not listed, leave untouched any tracks with no content field, and update or create tracks with a content field. ```bash curl -X PUT https:///api/v1/media_objects//media_tracks?include[]=content \\ -H 'Authorization: Bearer ' -d '[{\"locale\": \"en\"}, {\"locale\": \"af\",\"co...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "attachment_id": {
          "type": "string",
          "description": "Path parameter: attachment_id"
        },
        "include[]": {
          "type": "string",
          "description": "<p>By default, an update returns id, locale, kind, media\\_object\\_id, and user\\_id for each of the<br>result MediaTracks. Use include\\[] to<br>add additional fields. For example include\\[]=content Allowed values: <code>content</code>, <code>webvtt\\_content</code>, <code>updated\\_at</code>, <code>created\\_at</code></p>"
        }
      },
      "required": [
        "attachment_id"
      ]
    }
  },
  {
    "name": "get_media_objects",
    "description": "**Scope:** `url:GET|/api/v1/media_objects`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      }
    }
  },
  {
    "name": "get_courses_course_id_media_objects",
    "description": "**Scope:** `url:GET|/api/v1/courses/:course_id/media_objects`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "course_id"
      ]
    }
  },
  {
    "name": "get_groups_group_id_media_objects",
    "description": "**Scope:** `url:GET|/api/v1/groups/:group_id/media_objects`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_id": {
          "type": "string",
          "description": "Path parameter: group_id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "group_id"
      ]
    }
  },
  {
    "name": "get_media_attachments",
    "description": "**Scope:** `url:GET|/api/v1/media_attachments`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      }
    }
  },
  {
    "name": "get_courses_course_id_media_attachments",
    "description": "**Scope:** `url:GET|/api/v1/courses/:course_id/media_attachments`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "course_id"
      ]
    }
  },
  {
    "name": "get_groups_group_id_media_attachments",
    "description": "**Scope:** `url:GET|/api/v1/groups/:group_id/media_attachments` Returns media objects created by the user making the request. When using the second version, returns media objects associated with the given course. ```bash curl https:///api/v1/media_objects?exclude[]=sources&exclude[]=tracks \\ -H 'Authorization: Bearer ' curl https:///api/v1/courses/17/media_objects?exclude[]=sources&exclude[]=tracks \\ -H 'Authorization: Bearer ' ``` Returns a list of [MediaObject](#mediaobject) objects. [Media...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_id": {
          "type": "string",
          "description": "Path parameter: group_id"
        },
        "sort": {
          "type": "string",
          "description": "<p>Field to sort on. Default is \"title\"<br>title:: sorts on user\\_entered\\_title if available, title if not.<br>created\\_at:: sorts on the object's creation time. Allowed values: <code>title</code>, <code>created\\_at</code></p>"
        },
        "order": {
          "type": "string",
          "description": "Sort direction. Default is \"asc\" Allowed values: `asc`, `desc`"
        },
        "exclude[]": {
          "type": "string",
          "description": "<p>Array of data to exclude. By excluding \"sources\" and \"tracks\",<br>the api will not need to query kaltura, which greatly<br>speeds up its response.<br>sources:: Do not query kaltura for media\\_sources<br>tracks:: Do not query kaltura for media\\_tracks Allowed values: <code>sources</code>, <code>tracks</code></p>"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "group_id"
      ]
    }
  },
  {
    "name": "put_media_objects_media_object_id",
    "description": "**Scope:** `url:PUT|/api/v1/media_objects/:media_object_id`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "media_object_id": {
          "type": "string",
          "description": "Path parameter: media_object_id"
        }
      },
      "required": [
        "media_object_id"
      ]
    }
  },
  {
    "name": "put_media_attachments_attachment_id",
    "description": "**Scope:** `url:PUT|/api/v1/media_attachments/:attachment_id` Updates the title of a media object. *** This documentation is generated directly from the Canvas LMS source code, available [on Github](https://github.com/instructure/canvas-lms). --- This documentation is published with GitBook. GitBook is the documentation platform designed so that both humans and AI agents can read, navigate, and reason over technical content effectively. Learn more at gitbook.com. If you need additional inform...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "attachment_id": {
          "type": "string",
          "description": "Path parameter: attachment_id"
        },
        "user_entered_title": {
          "type": "string",
          "description": "The new title."
        },
        "viewer_restrictions": {
          "type": "string",
          "description": "<p>A JSON object describing viewer access restrictions for this media.<br>- show\\_rolling\\_transcript \\[Optional, Boolean]: Whether to show the rolling transcripts of the media during playback, or not.</p>"
        }
      },
      "required": [
        "attachment_id"
      ]
    }
  }
];

const handlers = {
  get_media_objects_media_object_id_media_tracks: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/media_objects/:media_object_id/media_tracks", args);
  },
  get_media_attachments_attachment_id_media_tracks: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/media_attachments/:attachment_id/media_tracks", args);
  },
  put_media_objects_media_object_id_media_tracks: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/media_objects/:media_object_id/media_tracks", args);
  },
  put_media_attachments_attachment_id_media_tracks: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/media_attachments/:attachment_id/media_tracks", args);
  },
  get_media_objects: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/media_objects", args);
  },
  get_courses_course_id_media_objects: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/courses/:course_id/media_objects", args);
  },
  get_groups_group_id_media_objects: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/groups/:group_id/media_objects", args);
  },
  get_media_attachments: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/media_attachments", args);
  },
  get_courses_course_id_media_attachments: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/courses/:course_id/media_attachments", args);
  },
  get_groups_group_id_media_attachments: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/groups/:group_id/media_attachments", args);
  },
  put_media_objects_media_object_id: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/media_objects/:media_object_id", args);
  },
  put_media_attachments_attachment_id: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/media_attachments/:attachment_id", args);
  }
};

module.exports = {
  definitions,
  handlers
};
