// Auto-generated MCP Tools for Canvas LMS API
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const { genericHandler } = require("./helper");

const definitions = [
  {
    "name": "get_courses_course_id_names_and_roles",
    "description": "**Scope:** `url:GET|/api/lti/courses/:course_id/names_and_roles` Return active NamesAndRoleMemberships in the given course. Returns a [NamesAndRoleMemberships](#namesandrolememberships) object. [Lti::Ims::NamesAndRolesController#group\\_index](https://github.com/instructure/canvas-lms/blob/master/app/controllers/lti/ims/names_and_roles_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "rlid": {
          "type": "string",
          "description": "<p>If specified only NamesAndRoleMemberships with access to the LTI link references by this <code>rlid</code> will be included.<br>Also causes the member array to be included for each returned NamesAndRoleMembership.<br>If the <code>role</code> parameter is also present, it will be 'and-ed' together with this parameter</p>"
        },
        "role": {
          "type": "string",
          "description": "<p>If specified only NamesAndRoleMemberships having this role in the given Course will be included.<br>Value must be a fully-qualified LTI/LIS role URN.<br>If the <code>rlid</code> parameter is also present, it will be 'and-ed' together with this parameter</p>"
        },
        "limit": {
          "type": "string",
          "description": "May be used to limit the number of NamesAndRoleMemberships returned in a page. Defaults to 50."
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "course_id"
      ]
    }
  },
  {
    "name": "get_groups_group_id_names_and_roles",
    "description": "**Scope:** `url:GET|/api/lti/groups/:group_id/names_and_roles` Return active NamesAndRoleMemberships in the given group. Returns a [NamesAndRoleMemberships](#namesandrolememberships) object. *** This documentation is generated directly from the Canvas LMS source code, available [on Github](https://github.com/instructure/canvas-lms). --- This documentation is published with GitBook. GitBook is the documentation platform designed so that both humans and AI agents can read, navigate, and reason ...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_id": {
          "type": "string",
          "description": "Path parameter: group_id"
        },
        "rlid": {
          "type": "string",
          "description": "<p>If specified only NamesAndRoleMemberships with access to the LTI link references by this <code>rlid</code> will be included.<br>Also causes the member array to be included for each returned NamesAndRoleMembership.<br>If the role parameter is also present, it will be 'and-ed' together with this parameter</p>"
        },
        "role": {
          "type": "string",
          "description": "<p>If specified only NamesAndRoleMemberships having this role in the given Group will be included.<br>Value must be a fully-qualified LTI/LIS role URN. Further, only<br><http://purl.imsglobal.org/vocab/lis/v2/membership#Member> and<br><http://purl.imsglobal.org/vocab/lis/v2/membership#Manager> are supported.<br>If the <code>rlid</code> parameter is also present, it will be 'and-ed' together with this parameter</p>"
        },
        "limit": {
          "type": "string",
          "description": "May be used to limit the number of NamesAndRoleMemberships returned in a page. Defaults to 50."
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "group_id"
      ]
    }
  }
];

const handlers = {
  get_courses_course_id_names_and_roles: async (client, args) => {
    return genericHandler(client, "GET", "/api/lti/courses/:course_id/names_and_roles", args);
  },
  get_groups_group_id_names_and_roles: async (client, args) => {
    return genericHandler(client, "GET", "/api/lti/groups/:group_id/names_and_roles", args);
  }
};

module.exports = {
  definitions,
  handlers
};
