// Auto-generated MCP Tools for Canvas LMS API
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const { genericHandler } = require("./helper");

const definitions = [
  {
    "name": "get_quiz_v1_courses_course_id_quizzes_assignment_id",
    "description": "**Scope:** `url:GET|/api/quiz/v1/courses/:course_id/quizzes/:assignment_id` Get details about a single new quiz. ```bash curl 'https:///api/quiz/v1/courses/1/quizzes/12' \\ -H 'Authorization: Bearer ' ``` Returns a [NewQuiz](#newquiz) object.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "number",
          "description": "no description"
        },
        "assignment_id": {
          "type": "number",
          "description": "The id of the assignment associated with the quiz."
        }
      },
      "required": [
        "course_id",
        "assignment_id"
      ]
    }
  },
  {
    "name": "get_quiz_v1_courses_course_id_quizzes",
    "description": "**Scope:** `url:GET|/api/quiz/v1/courses/:course_id/quizzes` Get a list of new quizzes. ```bash curl 'https:///api/quiz/v1/courses/1/quizzes' \\ -H 'Authorization Bearer ' ``` Returns a list of [NewQuiz](#newquiz) objects.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "number",
          "description": "no description"
        }
      },
      "required": [
        "course_id"
      ]
    }
  },
  {
    "name": "post_quiz_v1_courses_course_id_quizzes",
    "description": "**Scope:** `url:POST|/api/quiz/v1/courses/:course_id/quizzes` Create a new quiz for the course. ```bash curl 'https:///api/quiz/v1/courses/1/quizzes' \\ -X POST \\ -H 'Authorization Bearer ' \\ -d 'quiz[title]=New quiz' \\ -d 'quiz[assignment_group_id]=1' \\ -d 'quiz[points_possible]=100.0' \\ -d 'quiz[due_at]=2023-01-02T00:00:00Z' \\ -d 'quiz[lock_at]=2023-01-03T00:00:00Z' \\ -d 'quiz[unlock_at]=2023-01-01T00:00:00Z' \\ -d 'quiz[grading_type]=points' \\ -d 'quiz[instructions]=Instructions for quiz' \\ ...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "number",
          "description": "no description"
        },
        "quiz[title]": {
          "type": "string",
          "description": "The title of the quiz."
        },
        "quiz[assignment_group_id]": {
          "type": "number",
          "description": "The ID of the quiz's assignment group."
        },
        "quiz[points_possible]": {
          "type": "number",
          "description": "The total point value given to the quiz. Must be positive."
        },
        "quiz[due_at]": {
          "type": "string",
          "description": "When the quiz is due."
        },
        "quiz[lock_at]": {
          "type": "string",
          "description": "When to lock the quiz."
        },
        "quiz[unlock_at]": {
          "type": "string",
          "description": "When to unlock the quiz."
        },
        "quiz[grading_type]": {
          "type": "string",
          "description": "The type of grading the assignment receives. Allowed values: `pass_fail`, `percent`, `letter_grade`, `gpa_scale`, `points`"
        },
        "quiz[instructions]": {
          "type": "string",
          "description": "Instructions for the quiz."
        },
        "quiz[quiz_settings][calculator_type]": {
          "type": "string",
          "description": "<p>Specifies which type of Calculator a student can use during Quiz taking.<br>Should be null if no calculator is allowed. Allowed values: <code>none</code>, <code>basic</code>, <code>scientific</code></p>"
        },
        "quiz[quiz_settings][filter_ip_address]": {
          "type": "boolean",
          "description": "Whether IP filtering is needed. Must be true for filters to take effect."
        },
        "quiz[quiz_settings][filters][ips][]": {
          "type": "string",
          "description": "<p>Specifies ranges of IP addresses where the quiz can be taken from. Each range is an array like<br>\\[start address, end address], or null if there's no restriction.</p>"
        },
        "quiz[quiz_settings][multiple_attempts][multiple_attempts_enabled]": {
          "type": "boolean",
          "description": "Whether multiple attempts for this quiz is true."
        },
        "quiz[quiz_settings][multiple_attempts][attempt_limit]": {
          "type": "boolean",
          "description": "Whether there is an attempt limit. Only set if multiple\\_attempts\\_enabled is true."
        },
        "quiz[quiz_settings][multiple_attempts][max_attempts]": {
          "type": "number",
          "description": "<p>The allowed attempts a student can take. If null, the allowed attempts are unlimited. Only used if<br>attempt\\_limit is true.</p>"
        },
        "quiz[quiz_settings][multiple_attempts][score_to_keep]": {
          "type": "string",
          "description": "Whichever score to keep for the attempts. Only used if multiple\\_attempts\\_enabled is true. Allowed values: `average`, `first`, `highest`, `latest`"
        },
        "quiz[quiz_settings][multiple_attempts][cooling_period]": {
          "type": "boolean",
          "description": "Whether there is a cooling (waiting) period. Only used if multiple\\_attempts\\_enabled is true."
        },
        "quiz[quiz_settings][multiple_attempts][cooling_period_seconds]": {
          "type": "number",
          "description": "<p>Required waiting period in seconds between attempts. If null, there is no required time. Only used if<br>cooling\\_period is true</p>"
        },
        "quiz[quiz_settings][one_at_a_time_type]": {
          "type": "string",
          "description": "Specifies the settings for questions to display when quiz taking. Allowed values: `none`, `question`"
        },
        "quiz[quiz_settings][allow_backtracking]": {
          "type": "boolean",
          "description": "Whether to allow user to return to previous questions when 'one\\_at\\_a\\_time\\_type' is set to 'question'."
        },
        "quiz[quiz_settings][result_view_settings][result_view_restricted]": {
          "type": "boolean",
          "description": "Whether the results view is restricted for students. Must be true for any student restrictions to be set."
        },
        "quiz[quiz_settings][result_view_settings][display_points_awarded]": {
          "type": "boolean",
          "description": "Whether points are shown. Must set result\\_view\\_restricted to true to use this parameter."
        },
        "quiz[quiz_settings][result_view_settings][display_points_possible]": {
          "type": "boolean",
          "description": "Whether points possible is shown. Must set result\\_view\\_restricted to true to use this parameter."
        },
        "quiz[quiz_settings][result_view_settings][display_items]": {
          "type": "boolean",
          "description": "Whether to show items in the results view. Must be true for any items restrictions to be set."
        },
        "quiz[quiz_settings][result_view_settings][display_item_response]": {
          "type": "boolean",
          "description": "<p>Whether item response is shown. Only set if display\\_items is true. Must be true for<br>display\\_item\\_response\\_qualifier, show\\_item\\_responses\\_at, hide\\_item\\_responses\\_at, and<br>display\\_item\\_response\\_correctness to be set.</p>"
        },
        "quiz[quiz_settings][result_view_settings][display_item_response_qualifier]": {
          "type": "string",
          "description": "Specifies after which attempts student responses should be shown to them. Only used if display\\_item\\_response is true. Allowed values: `always`, `once_per_attempt`, `after_last_attempt`, `once_after_last_attempt`"
        },
        "quiz[quiz_settings][result_view_settings][show_item_responses_at]": {
          "type": "string",
          "description": "When student responses should be shown to them. Only used if display\\_item\\_response is true."
        },
        "quiz[quiz_settings][result_view_settings][hide_item_responses_at]": {
          "type": "string",
          "description": "When student responses should be hidden from them. Only used if display\\_item\\_response is true."
        },
        "quiz[quiz_settings][result_view_settings][display_item_response_correctness]": {
          "type": "boolean",
          "description": "<p>Whether item correctness is shown. Only set if display\\_item\\_response is true. Must be true for<br>display\\_item\\_response\\_correctness\\_qualifier, show\\_item\\_response\\_correctness\\_at, hide\\_item\\_response\\_correctness\\_at<br>and display\\_item\\_correct\\_answer to be set.</p>"
        },
        "quiz[quiz_settings][result_view_settings][display_item_response_correctness_qualifier]": {
          "type": "string",
          "description": "Specifies after which attempts student response correctness should be shown to them. Only used if display\\_item\\_response\\_correctness is true. Allowed values: `always`, `after_last_attempt`"
        },
        "quiz[quiz_settings][result_view_settings][show_item_response_correctness_at]": {
          "type": "string",
          "description": "When student response correctness should be shown to them. Only used if display\\_item\\_response\\_correctness is true."
        },
        "quiz[quiz_settings][result_view_settings][hide_item_response_correctness_at]": {
          "type": "string",
          "description": "When student response correctness should be hidden from them. Only used if display\\_item\\_response\\_correctness is true."
        },
        "quiz[quiz_settings][result_view_settings][display_item_correct_answer]": {
          "type": "boolean",
          "description": "Whether correct answer is shown. Only set if display\\_item\\_response\\_correctness is true."
        },
        "quiz[quiz_settings][result_view_settings][display_item_feedback]": {
          "type": "boolean",
          "description": "Whether Item feedback is shown. Only set if display\\_items is true."
        },
        "quiz[quiz_settings][shuffle_answers]": {
          "type": "boolean",
          "description": "Whether answers should be shuffled for students."
        },
        "quiz[quiz_settings][shuffle_questions]": {
          "type": "boolean",
          "description": "Whether questions should be shuffled for students."
        },
        "quiz[quiz_settings][require_student_access_code]": {
          "type": "boolean",
          "description": "Whether an access code is needed to take the quiz."
        },
        "quiz[quiz_settings][student_access_code]": {
          "type": "string",
          "description": "Access code to restrict quiz access. Should be null if no restriction."
        },
        "quiz[quiz_settings][has_time_limit]": {
          "type": "boolean",
          "description": "Whether there is a time limit for the quiz."
        },
        "quiz[quiz_settings][session_time_limit_in_seconds]": {
          "type": "number",
          "description": "Limit the time a student can work on the quiz. Should be null if no restriction."
        }
      },
      "required": [
        "course_id"
      ]
    }
  },
  {
    "name": "delete_quiz_v1_courses_course_id_quizzes_assignment_id",
    "description": "**Scope:** `url:DELETE|/api/quiz/v1/courses/:course_id/quizzes/:assignment_id` Delete a single new quiz. ```bash curl 'https:///api/quiz/v1/courses/1/quizzes/12' \\ -X DELETE \\ -H 'Authorization: Bearer ' ``` Returns a [NewQuiz](#newquiz) object. *** This documentation is generated directly from the Canvas LMS source code, available [on Github](https://github.com/instructure/canvas-lms). --- This documentation is published with GitBook. GitBook is the documentation platform designed so that bo...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "number",
          "description": "no description"
        },
        "assignment_id": {
          "type": "number",
          "description": "The id of the assignment associated with the quiz."
        }
      },
      "required": [
        "course_id",
        "assignment_id"
      ]
    }
  }
];

const handlers = {
  get_quiz_v1_courses_course_id_quizzes_assignment_id: async (client, args) => {
    return genericHandler(client, "GET", "/api/quiz/v1/courses/:course_id/quizzes/:assignment_id", args);
  },
  get_quiz_v1_courses_course_id_quizzes: async (client, args) => {
    return genericHandler(client, "GET", "/api/quiz/v1/courses/:course_id/quizzes", args);
  },
  post_quiz_v1_courses_course_id_quizzes: async (client, args) => {
    return genericHandler(client, "POST", "/api/quiz/v1/courses/:course_id/quizzes", args);
  },
  delete_quiz_v1_courses_course_id_quizzes_assignment_id: async (client, args) => {
    return genericHandler(client, "DELETE", "/api/quiz/v1/courses/:course_id/quizzes/:assignment_id", args);
  }
};

module.exports = {
  definitions,
  handlers
};
