// Auto-generated MCP Tools for Canvas LMS API
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const { genericHandler } = require("./helper");

const definitions = [
  {
    "name": "get_notice_handlers_context_external_tool_id",
    "description": "**Scope:** `url:GET|/api/lti/notice-handlers/:context_external_tool_id` List all notice handlers for the tool ```js { \"client_id\": 10000000000267, \"deployment_id\": \"123:8865aa05b4b79b64a91a86042e43af5ea8ae79eb\", \"notice_handlers\": [ { \"handler\": \"\", \"notice_type\": \"LtiHelloWorldNotice\" } ] } ``` Returns a [NoticeCatalog](#noticecatalog) object. [Lti::Ims::NoticeHandlersController#update](https://github.com/instructure/canvas-lms/blob/master/app/controllers/lti/ims/notice_handlers_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "context_external_tool_id": {
          "type": "string",
          "description": "Path parameter: context_external_tool_id"
        }
      },
      "required": [
        "context_external_tool_id"
      ]
    }
  },
  {
    "name": "put_notice_handlers_context_external_tool_id",
    "description": "**Scope:** `url:PUT|/api/lti/notice-handlers/:context_external_tool_id` Subscribe (set) or unsubscribe (remove) a notice handler for the tool ```js { \"handler\": \"\", \"notice_type\": \"LtiHelloWorldNotice\" } ``` Returns a [NoticeHandler](#noticehandler) object. *** This documentation is generated directly from the Canvas LMS source code, available [on Github](https://github.com/instructure/canvas-lms). --- This documentation is published with GitBook. GitBook is the documentation platform designe...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "context_external_tool_id": {
          "type": "string",
          "description": "Path parameter: context_external_tool_id"
        },
        "notice_type": {
          "type": "string",
          "description": "The type of notice"
        },
        "handler": {
          "type": "string",
          "description": "URL to receive the notice, or an empty string to unsubscribe"
        },
        "max_batch_size": {
          "type": "number",
          "description": "The maximum number of notices to include in a single batch"
        }
      },
      "required": [
        "context_external_tool_id",
        "notice_type",
        "handler"
      ]
    }
  }
];

const handlers = {
  get_notice_handlers_context_external_tool_id: async (client, args) => {
    return genericHandler(client, "GET", "/api/lti/notice-handlers/:context_external_tool_id", args);
  },
  put_notice_handlers_context_external_tool_id: async (client, args) => {
    return genericHandler(client, "PUT", "/api/lti/notice-handlers/:context_external_tool_id", args);
  }
};

module.exports = {
  definitions,
  handlers
};
