// Auto-generated MCP Tools for Canvas LMS API
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const { genericHandler } = require("./helper");

const definitions = [
  {
    "name": "get_users_user_id_communication_channels_communication_channel_id_notification_preferences",
    "description": "**Scope:** `url:GET|/api/v1/users/:user_id/communication_channels/:communication_channel_id/notification_preferences`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "user_id": {
          "type": "string",
          "description": "Path parameter: user_id"
        },
        "communication_channel_id": {
          "type": "string",
          "description": "Path parameter: communication_channel_id"
        }
      },
      "required": [
        "user_id",
        "communication_channel_id"
      ]
    }
  },
  {
    "name": "get_users_user_id_communication_channels_type_address_notification_preferences",
    "description": "**Scope:** `url:GET|/api/v1/users/:user_id/communication_channels/:type/:address/notification_preferences` Fetch all preferences for the given communication channel Returns a list of [NotificationPreference](#notificationpreference) objects. [NotificationPreferencesController#category\\_index](https://github.com/instructure/canvas-lms/blob/master/app/controllers/notification_preferences_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "user_id": {
          "type": "string",
          "description": "Path parameter: user_id"
        },
        "type": {
          "type": "string",
          "description": "Path parameter: type"
        },
        "address": {
          "type": "string",
          "description": "Path parameter: address"
        }
      },
      "required": [
        "user_id",
        "type",
        "address"
      ]
    }
  },
  {
    "name": "get_users_user_id_communication_channels_communication_channel_id_notification_preference_categories",
    "description": "**Scope:** `url:GET|/api/v1/users/:user_id/communication_channels/:communication_channel_id/notification_preference_categories` Fetch all notification preference categories for the given communication channel [NotificationPreferencesController#show](https://github.com/instructure/canvas-lms/blob/master/app/controllers/notification_preferences_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "user_id": {
          "type": "string",
          "description": "Path parameter: user_id"
        },
        "communication_channel_id": {
          "type": "string",
          "description": "Path parameter: communication_channel_id"
        }
      },
      "required": [
        "user_id",
        "communication_channel_id"
      ]
    }
  },
  {
    "name": "get_users_user_id_communication_channels_communication_channel_id_notification_preferences_notification",
    "description": "**Scope:** `url:GET|/api/v1/users/:user_id/communication_channels/:communication_channel_id/notification_preferences/:notification`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "user_id": {
          "type": "string",
          "description": "Path parameter: user_id"
        },
        "communication_channel_id": {
          "type": "string",
          "description": "Path parameter: communication_channel_id"
        },
        "notification": {
          "type": "string",
          "description": "Path parameter: notification"
        }
      },
      "required": [
        "user_id",
        "communication_channel_id",
        "notification"
      ]
    }
  },
  {
    "name": "get_users_user_id_communication_channels_type_address_notification_preferences_notification",
    "description": "**Scope:** `url:GET|/api/v1/users/:user_id/communication_channels/:type/:address/notification_preferences/:notification` Fetch the preference for the given notification for the given communication channel Returns a [NotificationPreference](#notificationpreference) object. [NotificationPreferencesController#update](https://github.com/instructure/canvas-lms/blob/master/app/controllers/notification_preferences_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "user_id": {
          "type": "string",
          "description": "Path parameter: user_id"
        },
        "type": {
          "type": "string",
          "description": "Path parameter: type"
        },
        "address": {
          "type": "string",
          "description": "Path parameter: address"
        },
        "notification": {
          "type": "string",
          "description": "Path parameter: notification"
        }
      },
      "required": [
        "user_id",
        "type",
        "address",
        "notification"
      ]
    }
  },
  {
    "name": "put_users_self_communication_channels_communication_channel_id_notification_preferences_notification",
    "description": "**Scope:** `url:PUT|/api/v1/users/self/communication_channels/:communication_channel_id/notification_preferences/:notification`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "communication_channel_id": {
          "type": "string",
          "description": "Path parameter: communication_channel_id"
        },
        "notification": {
          "type": "string",
          "description": "Path parameter: notification"
        }
      },
      "required": [
        "communication_channel_id",
        "notification"
      ]
    }
  },
  {
    "name": "put_users_self_communication_channels_type_address_notification_preferences_notification",
    "description": "**Scope:** `url:PUT|/api/v1/users/self/communication_channels/:type/:address/notification_preferences/:notification` Change the preference for a single notification for a single communication channel [NotificationPreferencesController#update\\_preferences\\_by\\_category](https://github.com/instructure/canvas-lms/blob/master/app/controllers/notification_preferences_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "description": "Path parameter: type"
        },
        "address": {
          "type": "string",
          "description": "Path parameter: address"
        },
        "notification": {
          "type": "string",
          "description": "Path parameter: notification"
        },
        "notification_preferences[frequency]": {
          "type": "string",
          "description": "The desired frequency for this notification"
        }
      },
      "required": [
        "type",
        "address",
        "notification",
        "notification_preferences[frequency]"
      ]
    }
  },
  {
    "name": "put_users_self_communication_channels_communication_channel_id_notification_preference_categories_category",
    "description": "**Scope:** `url:PUT|/api/v1/users/self/communication_channels/:communication_channel_id/notification_preference_categories/:category` Change the preferences for multiple notifications based on the category for a single communication channel [NotificationPreferencesController#update\\_all](https://github.com/instructure/canvas-lms/blob/master/app/controllers/notification_preferences_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "communication_channel_id": {
          "type": "string",
          "description": "Path parameter: communication_channel_id"
        },
        "category": {
          "type": "string",
          "description": "The name of the category. Must be parameterized (e.g. The category \"Course Content\" should be \"course\\_content\")"
        },
        "notification_preferences[frequency]": {
          "type": "string",
          "description": "The desired frequency for each notification in the category"
        }
      },
      "required": [
        "communication_channel_id",
        "category",
        "notification_preferences[frequency]"
      ]
    }
  },
  {
    "name": "put_users_self_communication_channels_communication_channel_id_notification_preferences",
    "description": "**Scope:** `url:PUT|/api/v1/users/self/communication_channels/:communication_channel_id/notification_preferences`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "communication_channel_id": {
          "type": "string",
          "description": "Path parameter: communication_channel_id"
        }
      },
      "required": [
        "communication_channel_id"
      ]
    }
  },
  {
    "name": "put_users_self_communication_channels_type_address_notification_preferences",
    "description": "**Scope:** `url:PUT|/api/v1/users/self/communication_channels/:type/:address/notification_preferences` Change the preferences for multiple notifications for a single communication channel at once *** This documentation is generated directly from the Canvas LMS source code, available [on Github](https://github.com/instructure/canvas-lms). --- This documentation is published with GitBook. GitBook is the documentation platform designed so that both humans and AI agents can read, navigate, and re...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "description": "Path parameter: type"
        },
        "address": {
          "type": "string",
          "description": "Path parameter: address"
        },
        "notification_preferences[<X>][frequency]": {
          "type": "string",
          "description": "The desired frequency for \\<X> notification"
        }
      },
      "required": [
        "type",
        "address",
        "notification_preferences[<X>][frequency]"
      ]
    }
  }
];

const handlers = {
  get_users_user_id_communication_channels_communication_channel_id_notification_preferences: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/users/:user_id/communication_channels/:communication_channel_id/notification_preferences", args);
  },
  get_users_user_id_communication_channels_type_address_notification_preferences: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/users/:user_id/communication_channels/:type/:address/notification_preferences", args);
  },
  get_users_user_id_communication_channels_communication_channel_id_notification_preference_categories: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/users/:user_id/communication_channels/:communication_channel_id/notification_preference_categories", args);
  },
  get_users_user_id_communication_channels_communication_channel_id_notification_preferences_notification: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/users/:user_id/communication_channels/:communication_channel_id/notification_preferences/:notification", args);
  },
  get_users_user_id_communication_channels_type_address_notification_preferences_notification: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/users/:user_id/communication_channels/:type/:address/notification_preferences/:notification", args);
  },
  put_users_self_communication_channels_communication_channel_id_notification_preferences_notification: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/users/self/communication_channels/:communication_channel_id/notification_preferences/:notification", args);
  },
  put_users_self_communication_channels_type_address_notification_preferences_notification: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/users/self/communication_channels/:type/:address/notification_preferences/:notification", args);
  },
  put_users_self_communication_channels_communication_channel_id_notification_preference_categories_category: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/users/self/communication_channels/:communication_channel_id/notification_preference_categories/:category", args);
  },
  put_users_self_communication_channels_communication_channel_id_notification_preferences: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/users/self/communication_channels/:communication_channel_id/notification_preferences", args);
  },
  put_users_self_communication_channels_type_address_notification_preferences: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/users/self/communication_channels/:type/:address/notification_preferences", args);
  }
};

module.exports = {
  definitions,
  handlers
};
