// Auto-generated MCP Tools for Canvas LMS API
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const { genericHandler } = require("./helper");

const definitions = [
  {
    "name": "post_assignments_assignment_id_submissions_submission_id_originality_report",
    "description": "**Scope:** `url:POST|/api/lti/assignments/:assignment_id/submissions/:submission_id/originality_report` Create a new OriginalityReport for the specified file Returns an [OriginalityReport](#originalityreport) object. [Lti::OriginalityReportsApiController#update](https://github.com/instructure/canvas-lms/blob/master/app/controllers/lti/originality_reports_api_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "assignment_id": {
          "type": "string",
          "description": "Path parameter: assignment_id"
        },
        "submission_id": {
          "type": "string",
          "description": "Path parameter: submission_id"
        },
        "originality_report[file_id]": {
          "type": "number",
          "description": "<p>The id of the file being given an originality score. Required<br>if creating a report associated with a file.</p>"
        },
        "originality_report[originality_score]": {
          "type": "number",
          "description": "<p>A number between 0 and 100 representing the measure of the<br>specified file's originality.</p>"
        },
        "originality_report[originality_report_url]": {
          "type": "string",
          "description": "<p>The URL where the originality report for the specified<br>file may be found.</p>"
        },
        "originality_report[originality_report_file_id]": {
          "type": "number",
          "description": "<p>The ID of the file within Canvas that contains the originality<br>report for the submitted file provided in the request URL.</p>"
        },
        "originality_report[tool_setting][resource_type_code]": {
          "type": "string",
          "description": "<p>The resource type code of the resource handler Canvas should use for the<br>LTI launch for viewing originality reports. If set Canvas will launch<br>to the message with type 'basic-lti-launch-request' in the specified<br>resource handler rather than using the originality\\_report\\_url.</p>"
        },
        "originality_report[tool_setting][resource_url]": {
          "type": "string",
          "description": "<p>The URL Canvas should launch to when showing an LTI originality report.<br>Note that this value is inferred from the specified resource handler's<br>message \"path\" value (See <code>resource\\_type\\_code</code>) unless<br>it is specified. If this parameter is used a <code>resource\\_type\\_code</code><br>must also be specified.</p>"
        },
        "originality_report[workflow_state]": {
          "type": "string",
          "description": "<p>May be set to \"pending\", \"error\", or \"scored\". If an originality score<br>is provided a workflow state of \"scored\" will be inferred.</p>"
        },
        "originality_report[error_message]": {
          "type": "string",
          "description": "<p>A message describing the error. If set, the \"workflow\\_state\"<br>will be set to \"error.\"</p>"
        },
        "originality_report[attempt]": {
          "type": "number",
          "description": "<p>If no <code>file\\_id</code> is given, and no file is required for the assignment<br>(that is, the assignment allows an online text entry), this parameter<br>may be given to clarify which attempt number the report is for (in the<br>case of resubmissions). If this field is omitted and no <code>file\\_id</code> is<br>given, the report will be created (or updated, if it exists) for the<br>first submission attempt with no associated file.</p>"
        }
      },
      "required": [
        "assignment_id",
        "submission_id",
        "originality_report[originality_score]"
      ]
    }
  },
  {
    "name": "put_assignments_assignment_id_submissions_submission_id_originality_report_id",
    "description": "**Scope:** `url:PUT|/api/lti/assignments/:assignment_id/submissions/:submission_id/originality_report/:id`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "assignment_id": {
          "type": "string",
          "description": "Path parameter: assignment_id"
        },
        "submission_id": {
          "type": "string",
          "description": "Path parameter: submission_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        }
      },
      "required": [
        "assignment_id",
        "submission_id",
        "id"
      ]
    }
  },
  {
    "name": "put_assignments_assignment_id_files_file_id_originality_report",
    "description": "**Scope:** `url:PUT|/api/lti/assignments/:assignment_id/files/:file_id/originality_report` Modify an existing originality report. An alternative to this endpoint is to POST the same parameters listed below to the CREATE endpoint. Returns an [OriginalityReport](#originalityreport) object. [Lti::OriginalityReportsApiController#show](https://github.com/instructure/canvas-lms/blob/master/app/controllers/lti/originality_reports_api_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "assignment_id": {
          "type": "string",
          "description": "Path parameter: assignment_id"
        },
        "file_id": {
          "type": "string",
          "description": "Path parameter: file_id"
        },
        "originality_report[originality_score]": {
          "type": "number",
          "description": "<p>A number between 0 and 100 representing the measure of the<br>specified file's originality.</p>"
        },
        "originality_report[originality_report_url]": {
          "type": "string",
          "description": "<p>The URL where the originality report for the specified<br>file may be found.</p>"
        },
        "originality_report[originality_report_file_id]": {
          "type": "number",
          "description": "<p>The ID of the file within Canvas that contains the originality<br>report for the submitted file provided in the request URL.</p>"
        },
        "originality_report[tool_setting][resource_type_code]": {
          "type": "string",
          "description": "<p>The resource type code of the resource handler Canvas should use for the<br>LTI launch for viewing originality reports. If set Canvas will launch<br>to the message with type 'basic-lti-launch-request' in the specified<br>resource handler rather than using the originality\\_report\\_url.</p>"
        },
        "originality_report[tool_setting][resource_url]": {
          "type": "string",
          "description": "<p>The URL Canvas should launch to when showing an LTI originality report.<br>Note that this value is inferred from the specified resource handler's<br>message \"path\" value (See <code>resource\\_type\\_code</code>) unless<br>it is specified. If this parameter is used a <code>resource\\_type\\_code</code><br>must also be specified.</p>"
        },
        "originality_report[workflow_state]": {
          "type": "string",
          "description": "<p>May be set to \"pending\", \"error\", or \"scored\". If an originality score<br>is provided a workflow state of \"scored\" will be inferred.</p>"
        },
        "originality_report[error_message]": {
          "type": "string",
          "description": "<p>A message describing the error. If set, the \"workflow\\_state\"<br>will be set to \"error.\"</p>"
        }
      },
      "required": [
        "assignment_id",
        "file_id"
      ]
    }
  },
  {
    "name": "get_assignments_assignment_id_submissions_submission_id_originality_report_id",
    "description": "**Scope:** `url:GET|/api/lti/assignments/:assignment_id/submissions/:submission_id/originality_report/:id`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "assignment_id": {
          "type": "string",
          "description": "Path parameter: assignment_id"
        },
        "submission_id": {
          "type": "string",
          "description": "Path parameter: submission_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        }
      },
      "required": [
        "assignment_id",
        "submission_id",
        "id"
      ]
    }
  },
  {
    "name": "get_assignments_assignment_id_files_file_id_originality_report",
    "description": "**Scope:** `url:GET|/api/lti/assignments/:assignment_id/files/:file_id/originality_report` Get a single originality report Returns an [OriginalityReport](#originalityreport) object. *** This documentation is generated directly from the Canvas LMS source code, available [on Github](https://github.com/instructure/canvas-lms). --- This documentation is published with GitBook. GitBook is the documentation platform designed so that both humans and AI agents can read, navigate, and reason over tech...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "assignment_id": {
          "type": "string",
          "description": "Path parameter: assignment_id"
        },
        "file_id": {
          "type": "string",
          "description": "Path parameter: file_id"
        }
      },
      "required": [
        "assignment_id",
        "file_id"
      ]
    }
  }
];

const handlers = {
  post_assignments_assignment_id_submissions_submission_id_originality_report: async (client, args) => {
    return genericHandler(client, "POST", "/api/lti/assignments/:assignment_id/submissions/:submission_id/originality_report", args);
  },
  put_assignments_assignment_id_submissions_submission_id_originality_report_id: async (client, args) => {
    return genericHandler(client, "PUT", "/api/lti/assignments/:assignment_id/submissions/:submission_id/originality_report/:id", args);
  },
  put_assignments_assignment_id_files_file_id_originality_report: async (client, args) => {
    return genericHandler(client, "PUT", "/api/lti/assignments/:assignment_id/files/:file_id/originality_report", args);
  },
  get_assignments_assignment_id_submissions_submission_id_originality_report_id: async (client, args) => {
    return genericHandler(client, "GET", "/api/lti/assignments/:assignment_id/submissions/:submission_id/originality_report/:id", args);
  },
  get_assignments_assignment_id_files_file_id_originality_report: async (client, args) => {
    return genericHandler(client, "GET", "/api/lti/assignments/:assignment_id/files/:file_id/originality_report", args);
  }
};

module.exports = {
  definitions,
  handlers
};
