// Auto-generated MCP Tools for Canvas LMS API
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const { genericHandler } = require("./helper");

const definitions = [
  {
    "name": "get_global_root_outcome_group",
    "description": "**Scope:** `url:GET|/api/v1/global/root_outcome_group`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      }
    }
  },
  {
    "name": "get_accounts_account_id_root_outcome_group",
    "description": "**Scope:** `url:GET|/api/v1/accounts/:account_id/root_outcome_group`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "account_id"
      ]
    }
  },
  {
    "name": "get_courses_course_id_root_outcome_group",
    "description": "**Scope:** `url:GET|/api/v1/courses/:course_id/root_outcome_group` Convenience redirect to find the root outcome group for a particular context. Will redirect to the appropriate outcome group's URL. [OutcomeGroupsApiController#index](https://github.com/instructure/canvas-lms/blob/master/app/controllers/outcome_groups_api_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "course_id"
      ]
    }
  },
  {
    "name": "get_accounts_account_id_outcome_groups",
    "description": "**Scope:** `url:GET|/api/v1/accounts/:account_id/outcome_groups`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "account_id"
      ]
    }
  },
  {
    "name": "get_courses_course_id_outcome_groups",
    "description": "**Scope:** `url:GET|/api/v1/courses/:course_id/outcome_groups` Returns a list of all outcome groups in the specified context. Returns a list of [OutcomeGroup](#outcomegroup) objects. [OutcomeGroupsApiController#link\\_index](https://github.com/instructure/canvas-lms/blob/master/app/controllers/outcome_groups_api_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "course_id"
      ]
    }
  },
  {
    "name": "get_accounts_account_id_outcome_group_links",
    "description": "**Scope:** `url:GET|/api/v1/accounts/:account_id/outcome_group_links`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "account_id"
      ]
    }
  },
  {
    "name": "get_courses_course_id_outcome_group_links",
    "description": "**Scope:** `url:GET|/api/v1/courses/:course_id/outcome_group_links` Returns a list of all outcome links in the specified context. Returns a list of [OutcomeLink](#outcomelink) objects. [OutcomeGroupsApiController#show](https://github.com/instructure/canvas-lms/blob/master/app/controllers/outcome_groups_api_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "outcome_style": {
          "type": "string",
          "description": "<p>The detail level of the outcomes. Defaults to \"abbrev\".<br>Specify \"full\" for more information.</p>"
        },
        "outcome_group_style": {
          "type": "string",
          "description": "<p>The detail level of the outcome groups. Defaults to \"abbrev\".<br>Specify \"full\" for more information.</p>"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "course_id"
      ]
    }
  },
  {
    "name": "get_global_outcome_groups_id",
    "description": "**Scope:** `url:GET|/api/v1/global/outcome_groups/:id`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "id"
      ]
    }
  },
  {
    "name": "get_accounts_account_id_outcome_groups_id",
    "description": "**Scope:** `url:GET|/api/v1/accounts/:account_id/outcome_groups/:id`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "account_id",
        "id"
      ]
    }
  },
  {
    "name": "get_courses_course_id_outcome_groups_id",
    "description": "**Scope:** `url:GET|/api/v1/courses/:course_id/outcome_groups/:id` Returns detailed information about a specific outcome group. Returns an [OutcomeGroup](#outcomegroup) object. [OutcomeGroupsApiController#update](https://github.com/instructure/canvas-lms/blob/master/app/controllers/outcome_groups_api_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "course_id",
        "id"
      ]
    }
  },
  {
    "name": "put_global_outcome_groups_id",
    "description": "**Scope:** `url:PUT|/api/v1/global/outcome_groups/:id`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        }
      },
      "required": [
        "id"
      ]
    }
  },
  {
    "name": "put_accounts_account_id_outcome_groups_id",
    "description": "**Scope:** `url:PUT|/api/v1/accounts/:account_id/outcome_groups/:id`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        }
      },
      "required": [
        "account_id",
        "id"
      ]
    }
  },
  {
    "name": "put_courses_course_id_outcome_groups_id",
    "description": "**Scope:** `url:PUT|/api/v1/courses/:course_id/outcome_groups/:id` Modify an existing outcome group. Fields not provided are left as is; unrecognized fields are ignored. When changing the parent outcome group, the new parent group must belong to the same context as this outcome group, and must not be a descendant of this outcome group (i.e. no cycles allowed). ```bash curl 'https:///api/v1/accounts/1/outcome_groups/2.json' \\ -X PUT \\ -F 'title=Outcome Group Title' \\ -F 'description=Outcome gr...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        },
        "title": {
          "type": "string",
          "description": "The new outcome group title."
        },
        "description": {
          "type": "string",
          "description": "The new outcome group description."
        },
        "vendor_guid": {
          "type": "string",
          "description": "A custom GUID for the learning standard."
        },
        "parent_outcome_group_id": {
          "type": "number",
          "description": "The id of the new parent outcome group."
        }
      },
      "required": [
        "course_id",
        "id"
      ]
    }
  },
  {
    "name": "delete_global_outcome_groups_id",
    "description": "**Scope:** `url:DELETE|/api/v1/global/outcome_groups/:id`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        }
      },
      "required": [
        "id"
      ]
    }
  },
  {
    "name": "delete_accounts_account_id_outcome_groups_id",
    "description": "**Scope:** `url:DELETE|/api/v1/accounts/:account_id/outcome_groups/:id`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        }
      },
      "required": [
        "account_id",
        "id"
      ]
    }
  },
  {
    "name": "delete_courses_course_id_outcome_groups_id",
    "description": "**Scope:** `url:DELETE|/api/v1/courses/:course_id/outcome_groups/:id` Deleting an outcome group deletes descendant outcome groups and outcome links. The linked outcomes themselves are only deleted if all links to the outcome were deleted. Aligned outcomes cannot be deleted; as such, if all remaining links to an aligned outcome are included in this group's descendants, the group deletion will fail. ```bash curl 'https:///api/v1/accounts/1/outcome_groups/2.json' \\ -X DELETE \\ -H \"Authorization:...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        }
      },
      "required": [
        "course_id",
        "id"
      ]
    }
  },
  {
    "name": "get_global_outcome_groups_id_outcomes",
    "description": "**Scope:** `url:GET|/api/v1/global/outcome_groups/:id/outcomes`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "id"
      ]
    }
  },
  {
    "name": "get_accounts_account_id_outcome_groups_id_outcomes",
    "description": "**Scope:** `url:GET|/api/v1/accounts/:account_id/outcome_groups/:id/outcomes`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "account_id",
        "id"
      ]
    }
  },
  {
    "name": "get_courses_course_id_outcome_groups_id_outcomes",
    "description": "**Scope:** `url:GET|/api/v1/courses/:course_id/outcome_groups/:id/outcomes` A paginated list of the immediate OutcomeLink children of the outcome group. Returns a list of [OutcomeLink](#outcomelink) objects. [OutcomeGroupsApiController#link](https://github.com/instructure/canvas-lms/blob/master/app/controllers/outcome_groups_api_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        },
        "outcome_style": {
          "type": "string",
          "description": "<p>The detail level of the outcomes. Defaults to \"abbrev\".<br>Specify \"full\" for more information.</p>"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "course_id",
        "id"
      ]
    }
  },
  {
    "name": "post_global_outcome_groups_id_outcomes",
    "description": "**Scope:** `url:POST|/api/v1/global/outcome_groups/:id/outcomes`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        }
      },
      "required": [
        "id"
      ]
    }
  },
  {
    "name": "put_global_outcome_groups_id_outcomes_outcome_id",
    "description": "**Scope:** `url:PUT|/api/v1/global/outcome_groups/:id/outcomes/:outcome_id`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        },
        "outcome_id": {
          "type": "string",
          "description": "Path parameter: outcome_id"
        }
      },
      "required": [
        "id",
        "outcome_id"
      ]
    }
  },
  {
    "name": "post_accounts_account_id_outcome_groups_id_outcomes",
    "description": "**Scope:** `url:POST|/api/v1/accounts/:account_id/outcome_groups/:id/outcomes`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        }
      },
      "required": [
        "account_id",
        "id"
      ]
    }
  },
  {
    "name": "put_accounts_account_id_outcome_groups_id_outcomes_outcome_id",
    "description": "**Scope:** `url:PUT|/api/v1/accounts/:account_id/outcome_groups/:id/outcomes/:outcome_id`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        },
        "outcome_id": {
          "type": "string",
          "description": "Path parameter: outcome_id"
        }
      },
      "required": [
        "account_id",
        "id",
        "outcome_id"
      ]
    }
  },
  {
    "name": "post_courses_course_id_outcome_groups_id_outcomes",
    "description": "**Scope:** `url:POST|/api/v1/courses/:course_id/outcome_groups/:id/outcomes`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        }
      },
      "required": [
        "course_id",
        "id"
      ]
    }
  },
  {
    "name": "put_courses_course_id_outcome_groups_id_outcomes_outcome_id",
    "description": "**Scope:** `url:PUT|/api/v1/courses/:course_id/outcome_groups/:id/outcomes/:outcome_id` Link an outcome into the outcome group. The outcome to link can either be specified by a PUT to the link URL for a specific outcome (the outcome\\_id in the PUT URLs) or by supplying the information for a new outcome (title, description, ratings, mastery\\_points) in a POST to the collection. If linking an existing outcome, the outcome\\_id must identify an outcome available to this context; i.e. an outcome o...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        },
        "outcome_id": {
          "type": "number",
          "description": "The ID of the existing outcome to link."
        },
        "move_from": {
          "type": "number",
          "description": "The ID of the old outcome group. Only used if outcome\\_id is present."
        },
        "title": {
          "type": "string",
          "description": "The title of the new outcome. Required if outcome\\_id is absent."
        },
        "display_name": {
          "type": "string",
          "description": "<p>A friendly name shown in reports for outcomes with cryptic titles,<br>such as common core standards names.</p>"
        },
        "description": {
          "type": "string",
          "description": "The description of the new outcome."
        },
        "vendor_guid": {
          "type": "string",
          "description": "A custom GUID for the learning standard."
        },
        "mastery_points": {
          "type": "number",
          "description": "The mastery threshold for the embedded rubric criterion."
        },
        "ratings[][description]": {
          "type": "string",
          "description": "The description of a rating level for the embedded rubric criterion."
        },
        "ratings[][points]": {
          "type": "number",
          "description": "The points corresponding to a rating level for the embedded rubric criterion."
        },
        "calculation_method": {
          "type": "string",
          "description": "<p>The new calculation method. Defaults to \"decaying\\_average\"<br>if the Outcomes New Decaying Average Calculation Method FF is ENABLED<br>then Defaults to \"weighted\\_average\" Allowed values: <code>weighted\\_average</code>, <code>decaying\\_average</code>, <code>n\\_mastery</code>, <code>latest</code>, <code>highest</code>, <code>average</code></p>"
        },
        "calculation_int": {
          "type": "number",
          "description": "The new calculation int. Only applies if the calculation\\_method is \"weighted\\_average\", \"decaying\\_average\" or \"n\\_mastery\". Defaults to 65"
        }
      },
      "required": [
        "course_id",
        "id",
        "outcome_id"
      ]
    }
  },
  {
    "name": "delete_global_outcome_groups_id_outcomes_outcome_id",
    "description": "**Scope:** `url:DELETE|/api/v1/global/outcome_groups/:id/outcomes/:outcome_id`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        },
        "outcome_id": {
          "type": "string",
          "description": "Path parameter: outcome_id"
        }
      },
      "required": [
        "id",
        "outcome_id"
      ]
    }
  },
  {
    "name": "delete_accounts_account_id_outcome_groups_id_outcomes_outcome_id",
    "description": "**Scope:** `url:DELETE|/api/v1/accounts/:account_id/outcome_groups/:id/outcomes/:outcome_id`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        },
        "outcome_id": {
          "type": "string",
          "description": "Path parameter: outcome_id"
        }
      },
      "required": [
        "account_id",
        "id",
        "outcome_id"
      ]
    }
  },
  {
    "name": "delete_courses_course_id_outcome_groups_id_outcomes_outcome_id",
    "description": "**Scope:** `url:DELETE|/api/v1/courses/:course_id/outcome_groups/:id/outcomes/:outcome_id` Unlinking an outcome only deletes the outcome itself if this was the last link to the outcome in any group in any context. Aligned outcomes cannot be deleted; as such, if this is the last link to an aligned outcome, the unlinking will fail. ```bash curl 'https:///api/v1/accounts/1/outcome_groups/1/outcomes/1.json' \\ -X DELETE \\ -H \"Authorization: Bearer \" ``` Returns an [OutcomeLink](#outcomelink) objec...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        },
        "outcome_id": {
          "type": "string",
          "description": "Path parameter: outcome_id"
        }
      },
      "required": [
        "course_id",
        "id",
        "outcome_id"
      ]
    }
  },
  {
    "name": "get_global_outcome_groups_id_subgroups",
    "description": "**Scope:** `url:GET|/api/v1/global/outcome_groups/:id/subgroups`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "id"
      ]
    }
  },
  {
    "name": "get_accounts_account_id_outcome_groups_id_subgroups",
    "description": "**Scope:** `url:GET|/api/v1/accounts/:account_id/outcome_groups/:id/subgroups`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "account_id",
        "id"
      ]
    }
  },
  {
    "name": "get_courses_course_id_outcome_groups_id_subgroups",
    "description": "**Scope:** `url:GET|/api/v1/courses/:course_id/outcome_groups/:id/subgroups` A paginated list of the immediate OutcomeGroup children of the outcome group. Returns a list of [OutcomeGroup](#outcomegroup) objects. [OutcomeGroupsApiController#create](https://github.com/instructure/canvas-lms/blob/master/app/controllers/outcome_groups_api_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "course_id",
        "id"
      ]
    }
  },
  {
    "name": "post_global_outcome_groups_id_subgroups",
    "description": "**Scope:** `url:POST|/api/v1/global/outcome_groups/:id/subgroups`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        }
      },
      "required": [
        "id"
      ]
    }
  },
  {
    "name": "post_accounts_account_id_outcome_groups_id_subgroups",
    "description": "**Scope:** `url:POST|/api/v1/accounts/:account_id/outcome_groups/:id/subgroups`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        }
      },
      "required": [
        "account_id",
        "id"
      ]
    }
  },
  {
    "name": "post_courses_course_id_outcome_groups_id_subgroups",
    "description": "**Scope:** `url:POST|/api/v1/courses/:course_id/outcome_groups/:id/subgroups` Creates a new empty subgroup under the outcome group with the given title and description. ```bash curl 'https:///api/v1/accounts/1/outcome_groups/1/subgroups.json' \\ -X POST \\ -F 'title=Outcome Group Title' \\ -F 'description=Outcome group description' \\ -F 'vendor_guid=customid9000' \\ -H \"Authorization: Bearer \" ``` ```bash curl 'https:///api/v1/accounts/1/outcome_groups/1/subgroups.json' \\ -X POST \\ --data-binary ...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        },
        "title": {
          "type": "string",
          "description": "The title of the new outcome group."
        },
        "description": {
          "type": "string",
          "description": "The description of the new outcome group."
        },
        "vendor_guid": {
          "type": "string",
          "description": "A custom GUID for the learning standard"
        }
      },
      "required": [
        "course_id",
        "id",
        "title"
      ]
    }
  },
  {
    "name": "post_global_outcome_groups_id_import",
    "description": "**Scope:** `url:POST|/api/v1/global/outcome_groups/:id/import`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        }
      },
      "required": [
        "id"
      ]
    }
  },
  {
    "name": "post_accounts_account_id_outcome_groups_id_import",
    "description": "**Scope:** `url:POST|/api/v1/accounts/:account_id/outcome_groups/:id/import`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        }
      },
      "required": [
        "account_id",
        "id"
      ]
    }
  },
  {
    "name": "post_courses_course_id_outcome_groups_id_import",
    "description": "**Scope:** `url:POST|/api/v1/courses/:course_id/outcome_groups/:id/import` Creates a new subgroup of the outcome group with the same title and description as the source group, then creates links in that new subgroup to the same outcomes that are linked in the source group. Recurses on the subgroups of the source group, importing them each in turn into the new subgroup. Allows you to copy organizational structure, but does not create copies of the outcomes themselves, only new links. The sourc...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        },
        "source_outcome_group_id": {
          "type": "number",
          "description": "The ID of the source outcome group."
        },
        "async": {
          "type": "boolean",
          "description": "<p>If true, perform action asynchronously. In that case, this endpoint<br>will return a Progress object instead of an OutcomeGroup.<br>Use the <a href=\"progress.md#method.progress.show\">progress endpoint</a><br>to query the status of the operation. The imported outcome group id<br>and url will be returned in the results of the Progress object<br>as \"outcome\\_group\\_id\" and \"outcome\\_group\\_url\"</p>"
        }
      },
      "required": [
        "course_id",
        "id",
        "source_outcome_group_id"
      ]
    }
  }
];

const handlers = {
  get_global_root_outcome_group: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/global/root_outcome_group", args);
  },
  get_accounts_account_id_root_outcome_group: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/accounts/:account_id/root_outcome_group", args);
  },
  get_courses_course_id_root_outcome_group: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/courses/:course_id/root_outcome_group", args);
  },
  get_accounts_account_id_outcome_groups: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/accounts/:account_id/outcome_groups", args);
  },
  get_courses_course_id_outcome_groups: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/courses/:course_id/outcome_groups", args);
  },
  get_accounts_account_id_outcome_group_links: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/accounts/:account_id/outcome_group_links", args);
  },
  get_courses_course_id_outcome_group_links: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/courses/:course_id/outcome_group_links", args);
  },
  get_global_outcome_groups_id: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/global/outcome_groups/:id", args);
  },
  get_accounts_account_id_outcome_groups_id: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/accounts/:account_id/outcome_groups/:id", args);
  },
  get_courses_course_id_outcome_groups_id: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/courses/:course_id/outcome_groups/:id", args);
  },
  put_global_outcome_groups_id: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/global/outcome_groups/:id", args);
  },
  put_accounts_account_id_outcome_groups_id: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/accounts/:account_id/outcome_groups/:id", args);
  },
  put_courses_course_id_outcome_groups_id: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/courses/:course_id/outcome_groups/:id", args);
  },
  delete_global_outcome_groups_id: async (client, args) => {
    return genericHandler(client, "DELETE", "/api/v1/global/outcome_groups/:id", args);
  },
  delete_accounts_account_id_outcome_groups_id: async (client, args) => {
    return genericHandler(client, "DELETE", "/api/v1/accounts/:account_id/outcome_groups/:id", args);
  },
  delete_courses_course_id_outcome_groups_id: async (client, args) => {
    return genericHandler(client, "DELETE", "/api/v1/courses/:course_id/outcome_groups/:id", args);
  },
  get_global_outcome_groups_id_outcomes: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/global/outcome_groups/:id/outcomes", args);
  },
  get_accounts_account_id_outcome_groups_id_outcomes: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/accounts/:account_id/outcome_groups/:id/outcomes", args);
  },
  get_courses_course_id_outcome_groups_id_outcomes: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/courses/:course_id/outcome_groups/:id/outcomes", args);
  },
  post_global_outcome_groups_id_outcomes: async (client, args) => {
    return genericHandler(client, "POST", "/api/v1/global/outcome_groups/:id/outcomes", args);
  },
  put_global_outcome_groups_id_outcomes_outcome_id: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/global/outcome_groups/:id/outcomes/:outcome_id", args);
  },
  post_accounts_account_id_outcome_groups_id_outcomes: async (client, args) => {
    return genericHandler(client, "POST", "/api/v1/accounts/:account_id/outcome_groups/:id/outcomes", args);
  },
  put_accounts_account_id_outcome_groups_id_outcomes_outcome_id: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/accounts/:account_id/outcome_groups/:id/outcomes/:outcome_id", args);
  },
  post_courses_course_id_outcome_groups_id_outcomes: async (client, args) => {
    return genericHandler(client, "POST", "/api/v1/courses/:course_id/outcome_groups/:id/outcomes", args);
  },
  put_courses_course_id_outcome_groups_id_outcomes_outcome_id: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/courses/:course_id/outcome_groups/:id/outcomes/:outcome_id", args);
  },
  delete_global_outcome_groups_id_outcomes_outcome_id: async (client, args) => {
    return genericHandler(client, "DELETE", "/api/v1/global/outcome_groups/:id/outcomes/:outcome_id", args);
  },
  delete_accounts_account_id_outcome_groups_id_outcomes_outcome_id: async (client, args) => {
    return genericHandler(client, "DELETE", "/api/v1/accounts/:account_id/outcome_groups/:id/outcomes/:outcome_id", args);
  },
  delete_courses_course_id_outcome_groups_id_outcomes_outcome_id: async (client, args) => {
    return genericHandler(client, "DELETE", "/api/v1/courses/:course_id/outcome_groups/:id/outcomes/:outcome_id", args);
  },
  get_global_outcome_groups_id_subgroups: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/global/outcome_groups/:id/subgroups", args);
  },
  get_accounts_account_id_outcome_groups_id_subgroups: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/accounts/:account_id/outcome_groups/:id/subgroups", args);
  },
  get_courses_course_id_outcome_groups_id_subgroups: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/courses/:course_id/outcome_groups/:id/subgroups", args);
  },
  post_global_outcome_groups_id_subgroups: async (client, args) => {
    return genericHandler(client, "POST", "/api/v1/global/outcome_groups/:id/subgroups", args);
  },
  post_accounts_account_id_outcome_groups_id_subgroups: async (client, args) => {
    return genericHandler(client, "POST", "/api/v1/accounts/:account_id/outcome_groups/:id/subgroups", args);
  },
  post_courses_course_id_outcome_groups_id_subgroups: async (client, args) => {
    return genericHandler(client, "POST", "/api/v1/courses/:course_id/outcome_groups/:id/subgroups", args);
  },
  post_global_outcome_groups_id_import: async (client, args) => {
    return genericHandler(client, "POST", "/api/v1/global/outcome_groups/:id/import", args);
  },
  post_accounts_account_id_outcome_groups_id_import: async (client, args) => {
    return genericHandler(client, "POST", "/api/v1/accounts/:account_id/outcome_groups/:id/import", args);
  },
  post_courses_course_id_outcome_groups_id_import: async (client, args) => {
    return genericHandler(client, "POST", "/api/v1/courses/:course_id/outcome_groups/:id/import", args);
  }
};

module.exports = {
  definitions,
  handlers
};
