// Auto-generated MCP Tools for Canvas LMS API
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const { genericHandler } = require("./helper");

const definitions = [
  {
    "name": "post_courses_course_id_quizzes_id_submission_users_message",
    "description": "**Scope:** `url:POST|/api/v1/courses/:course_id/quizzes/:id/submission_users/message` { \"body\": { \"type\": \"string\", \"description\": \"message body of the conversation to be created\", \"example\": \"Please take the quiz.\" }, \"recipients\": { \"type\": \"string\", \"description\": \"Who to send the message to. May be either 'submitted' or 'unsubmitted'\", \"example\": \"submitted\" }, \"subject\": { \"type\": \"string\", \"description\": \"Subject of the new Conversation created\", \"example\": \"ATTN: Quiz 101 Students\" } }...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        },
        "conversations": {
          "type": "string",
          "description": "- Body and recipients to send the message to."
        }
      },
      "required": [
        "course_id",
        "id"
      ]
    }
  }
];

const handlers = {
  post_courses_course_id_quizzes_id_submission_users_message: async (client, args) => {
    return genericHandler(client, "POST", "/api/v1/courses/:course_id/quizzes/:id/submission_users/message", args);
  }
};

module.exports = {
  definitions,
  handlers
};
