// Auto-generated MCP Tools for Canvas LMS API
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const { genericHandler } = require("./helper");

const definitions = [
  {
    "name": "post_accounts_account_id_shared_brand_configs",
    "description": "**Scope:** `url:POST|/api/v1/accounts/:account_id/shared_brand_configs` Create a SharedBrandConfig, which will give the given brand\\_config a name and make it available to other users of this account. ```bash curl 'https:///api/v1/accounts//shared_brand_configs' \\ -X POST \\ -F 'shared_brand_config[name]=Crimson and Gold Theme' \\ -F 'shared_brand_config[brand_config_md5]=a1f113321fa024e7a14cb0948597a2a4' \\ -H \"Authorization: Bearer \" ``` Returns a [SharedBrandConfig](#sharedbrandconfig) object...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        },
        "shared_brand_config[name]": {
          "type": "string",
          "description": "Name to share this BrandConfig (theme) as."
        },
        "shared_brand_config[brand_config_md5]": {
          "type": "string",
          "description": "MD5 of brand\\_config to share"
        }
      },
      "required": [
        "account_id",
        "shared_brand_config[name]",
        "shared_brand_config[brand_config_md5]"
      ]
    }
  },
  {
    "name": "put_accounts_account_id_shared_brand_configs_id",
    "description": "**Scope:** `url:PUT|/api/v1/accounts/:account_id/shared_brand_configs/:id` Update the specified shared\\_brand\\_config with a new name or to point to a new brand\\_config. Uses same parameters as create. ```bash curl -X PUT 'https:///api/v1/accounts//shared_brand_configs/' \\ -H \"Authorization: Bearer \" \\ -F 'shared_brand_config[name]=New Name' \\ -F 'shared_brand_config[brand_config_md5]=a1f113321fa024e7a14cb0948597a2a4' ``` Returns a [SharedBrandConfig](#sharedbrandconfig) object. [SharedBrandC...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        }
      },
      "required": [
        "account_id",
        "id"
      ]
    }
  },
  {
    "name": "delete_shared_brand_configs_id",
    "description": "**Scope:** `url:DELETE|/api/v1/shared_brand_configs/:id` Delete a SharedBrandConfig, which will unshare it so you nor anyone else in your account will see it as an option to pick from. ```bash curl -X DELETE https:///api/v1/shared_brand_configs/ \\ -H 'Authorization: Bearer ' ``` Returns a [SharedBrandConfig](#sharedbrandconfig) object. *** This documentation is generated directly from the Canvas LMS source code, available [on Github](https://github.com/instructure/canvas-lms). --- This docume...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        }
      },
      "required": [
        "id"
      ]
    }
  }
];

const handlers = {
  post_accounts_account_id_shared_brand_configs: async (client, args) => {
    return genericHandler(client, "POST", "/api/v1/accounts/:account_id/shared_brand_configs", args);
  },
  put_accounts_account_id_shared_brand_configs_id: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/accounts/:account_id/shared_brand_configs/:id", args);
  },
  delete_shared_brand_configs_id: async (client, args) => {
    return genericHandler(client, "DELETE", "/api/v1/shared_brand_configs/:id", args);
  }
};

module.exports = {
  definitions,
  handlers
};
