// Auto-generated MCP Tools for Canvas LMS API
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const { genericHandler } = require("./helper");

const definitions = [
  {
    "name": "get_accounts_account_id_sis_imports_id_errors",
    "description": "**Scope:** `url:GET|/api/v1/accounts/:account_id/sis_imports/:id/errors`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        }
      },
      "required": [
        "account_id",
        "id"
      ]
    }
  },
  {
    "name": "get_accounts_account_id_sis_import_errors",
    "description": "**Scope:** `url:GET|/api/v1/accounts/:account_id/sis_import_errors` Returns the list of SIS import errors for an account or a SIS import. Import errors are only stored for 30 days. Example: curl 'https\\://\\/api/v1/accounts/\\/sis\\_imports/\\/sis\\_import\\_errors'\\ -H \"Authorization: Bearer \\\" Example: curl 'https\\://\\/api/v1/accounts/\\/sis\\_import\\_errors'\\ -H \"Authorization: Bearer \\\" Returns a list of [SisImportError](#sisimporterror) objects. *** This documentation is generated directly from ...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        },
        "failure": {
          "type": "boolean",
          "description": "If set, only shows errors on a sis import that would cause a failure."
        }
      },
      "required": [
        "account_id"
      ]
    }
  }
];

const handlers = {
  get_accounts_account_id_sis_imports_id_errors: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/accounts/:account_id/sis_imports/:id/errors", args);
  },
  get_accounts_account_id_sis_import_errors: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/accounts/:account_id/sis_import_errors", args);
  }
};

module.exports = {
  definitions,
  handlers
};
