// Auto-generated MCP Tools for Canvas LMS API
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const { genericHandler } = require("./helper");

const definitions = [
  {
    "name": "get_accounts_account_id_temporary_enrollment_pairings",
    "description": "**Scope:** `url:GET|/api/v1/accounts/:account_id/temporary_enrollment_pairings` Returns the list of temporary enrollment pairings for a root account. Returns a list of [TemporaryEnrollmentPairing](#temporaryenrollmentpairing) objects. [TemporaryEnrollmentPairingsApiController#show](https://github.com/instructure/canvas-lms/blob/master/app/controllers/temporary_enrollment_pairings_api_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        },
        "include_deleted": {
          "type": "boolean",
          "description": "If true, include deleted pairings in the response. Defaults to false."
        }
      },
      "required": [
        "account_id"
      ]
    }
  },
  {
    "name": "get_accounts_account_id_temporary_enrollment_pairings_id",
    "description": "**Scope:** `url:GET|/api/v1/accounts/:account_id/temporary_enrollment_pairings/:id` Returns the temporary enrollment pairing with the given id. Returns a [TemporaryEnrollmentPairing](#temporaryenrollmentpairing) object. [TemporaryEnrollmentPairingsApiController#new](https://github.com/instructure/canvas-lms/blob/master/app/controllers/temporary_enrollment_pairings_api_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        }
      },
      "required": [
        "account_id",
        "id"
      ]
    }
  },
  {
    "name": "get_accounts_account_id_temporary_enrollment_pairings_new",
    "description": "**Scope:** `url:GET|/api/v1/accounts/:account_id/temporary_enrollment_pairings/new` Initialize an unsaved Temporary Enrollment Pairing. Returns a [TemporaryEnrollmentPairing](#temporaryenrollmentpairing) object. [TemporaryEnrollmentPairingsApiController#create](https://github.com/instructure/canvas-lms/blob/master/app/controllers/temporary_enrollment_pairings_api_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        }
      },
      "required": [
        "account_id"
      ]
    }
  },
  {
    "name": "post_accounts_account_id_temporary_enrollment_pairings",
    "description": "**Scope:** `url:POST|/api/v1/accounts/:account_id/temporary_enrollment_pairings` Create a Temporary Enrollment Pairing. Returns a [TemporaryEnrollmentPairing](#temporaryenrollmentpairing) object. [TemporaryEnrollmentPairingsApiController#destroy](https://github.com/instructure/canvas-lms/blob/master/app/controllers/temporary_enrollment_pairings_api_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        },
        "workflow_state": {
          "type": "string",
          "description": "The workflow state of the temporary enrollment pairing."
        },
        "ending_enrollment_state": {
          "type": "string",
          "description": "<p>The ending enrollment state to be given to each associated enrollment<br>when the enrollment period has been reached. Defaults to \"deleted\" if no value is given.<br>Accepted values are \"deleted\", \"completed\", and \"inactive\". Allowed values: <code>deleted</code>, <code>completed</code>, <code>inactive</code></p>"
        }
      },
      "required": [
        "account_id"
      ]
    }
  },
  {
    "name": "delete_accounts_account_id_temporary_enrollment_pairings_id",
    "description": "**Scope:** `url:DELETE|/api/v1/accounts/:account_id/temporary_enrollment_pairings/:id` Delete a temporary enrollment pairing Returns a [TemporaryEnrollmentPairing](#temporaryenrollmentpairing) object. *** This documentation is generated directly from the Canvas LMS source code, available [on Github](https://github.com/instructure/canvas-lms). --- This documentation is published with GitBook. GitBook is the documentation platform designed so that both humans and AI agents can read, navigate, a...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        }
      },
      "required": [
        "account_id",
        "id"
      ]
    }
  }
];

const handlers = {
  get_accounts_account_id_temporary_enrollment_pairings: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/accounts/:account_id/temporary_enrollment_pairings", args);
  },
  get_accounts_account_id_temporary_enrollment_pairings_id: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/accounts/:account_id/temporary_enrollment_pairings/:id", args);
  },
  get_accounts_account_id_temporary_enrollment_pairings_new: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/accounts/:account_id/temporary_enrollment_pairings/new", args);
  },
  post_accounts_account_id_temporary_enrollment_pairings: async (client, args) => {
    return genericHandler(client, "POST", "/api/v1/accounts/:account_id/temporary_enrollment_pairings", args);
  },
  delete_accounts_account_id_temporary_enrollment_pairings_id: async (client, args) => {
    return genericHandler(client, "DELETE", "/api/v1/accounts/:account_id/temporary_enrollment_pairings/:id", args);
  }
};

module.exports = {
  definitions,
  handlers
};
